### ISSUE TITLE
Simulated Lensed UDF source (AGN and SN host) galaxies.

### ISSUE THREAD

**Issue by linan7788626** [DarkEnergyScienceCollaboration/Twinkles#10]
Hi, 
My name is Nan Li , I am a joint postdoc at KICP and Argonne National Lab. I make advanced strong lensed image simulations like Figure1, which includes lensed arc and the galaxies on the line of sight so far, member galaxies of the lens will be involved soon.  I'd love to do my bit for this project, if needed. 

All the best,
Nan Li

![figure1](https://cloud.githubusercontent.com/assets/1016652/4797556/9b7c6730-5e0c-11e4-908c-ec0bd611d8bd.jpeg)

**Comment by linan7788626** [comment]
Hi Phil,

I have uploaded an updated simulated lensed image, it includes member galaxies ( most of the yellow ones), galaxies on the line of sight, foreground stars (e.g., the very bright one around the top right ). This image is for Megacam, so we also convolved with the PSF and added noise according to the PSF model and noise mode of Megacam. So far, this is a result for cluster size lensing system, If we want to play with galaxies scale lensing systems, there are some topics we need to discuss during the telecon tomorrow, for example, how many particles and how high the resolution of the images are good enough, what galaxies we want to use as input sources and so on. Should you have any questions, please feel free to let me know.  Thanks.

All the best,
Nan Li

![sample_image_for_twinkles](https://cloud.githubusercontent.com/assets/1016652/5928472/1eaa3ac0-a641-11e4-8fb7-c743d4aa7d64.jpg)

**Comment by drphilmarshall** [comment]
Closing this, so we can focus on #52 !
