### ISSUE TITLE
Monitor code, for light curve extraction and validation

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#103]
In DC1, light curve extraction is pretty easy - but we should start developing the  Monitor to do it anyway. It'll help us keep our light curve validation code together, and be prepared for the possibility of doing more than just accepting level 2 forced photometry. @jbkalmbach signed up at Argonne to lead this task - want to start a Monitor repo so we can start discussion, Bryce? I just made one for the [SLTimer](https://github.com/DarkEnergyScienceCollaboration/SLTimer), and it reminded me that we need  an SLMonitor too, that inherits from a more fundamental Monitor.

**Comment by jbkalmbach** [comment]
@drphilmarshall Repo in place [here](https://github.com/DarkEnergyScienceCollaboration/SLMonitor). Do you mind if I just copy over the skeleton you used in SLTimer?

**Comment by drphilmarshall** [comment]
Not at all! I believe it is licensed as such :-) BTW can you please change
your repo name to "Monitor" so that we can do the SN group a solid and work
on their light curve extraction problem too? Thanks! :-)

**Comment by jbkalmbach** [comment]
Name change is done and skeleton is in place.

**Comment by drphilmarshall** [comment]
Nice! :-)
