### ISSUE TITLE
Please add names to the SSim SRM table for CatSim related Twinkles work

### ISSUE THREAD

**Issue by cwwalter** [DarkEnergyScienceCollaboration/Twinkles#104]
Hi All,

Could someone put names in to 1.1.3. and 1.1.4 for the CatSim related SSim twinkles work.  I think this is @danielsf and @rbiswas4  but would like a definitive answer.

Table is here:

https://confluence.slac.stanford.edu/display/LSSTDESC/SSim_SRM_Table

Thanks! 

-Chris

**Comment by danielsf** [comment]
I added myself, @rbiswas4 and @jbkalmbach

**Comment by cwwalter** [comment]
Great. Thanks! I forgot to add… can you add a reasonable due date to those tasks given the Twinkles schedule?

**Comment by drphilmarshall** [comment]
Done! This'll be completed this month - the task force is delivering! :-)

**Comment by cwwalter** [comment]
Thanks all!
