### ISSUE TITLE
repository reorganization

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#105]
It's probably worth re-organizing this repository in order to provide an example for other DESC repos.  
One thing to consider is making a python folder and putting any code that is mean to be imported from a `twinkles` module to live as a subfolder.    This will make it easier/possible for whatever package management tool we use, e.g., eups, to know what to add to the user's PYTHONPATH when setting up the package.  The same would apply to the new [Monitor](https://github.com/DarkEnergyScienceCollaboration/Monitor) and [SLTimer](https://github.com/DarkEnergyScienceCollaboration/SLTimer) repos.  
@SimonKrughoff You mentioned that you were going to look into reorganizing this repo.  I'm wondering if we should just make it eups-compliant.

**Comment by SimonKrughoff** [comment]
@jchiang87 thanks for the nudge.  I have been thinking a little about this.  I have a task on my plate to re-organize the repo and was wondering whether we want to copy DM's namespace conventions.  I.e. twinkles goes to `lsst.twinkles` or `desc.twinkles`.  Either way, I think having a python directory with the code inside that would be a big win if we can standardize on it.

**Comment by jchiang87** [comment]
I think that `desc.twinkles` would be a good convention to adopt, but we should probably not going any deeper than that to avoid the tendency towards overly large packages with lots of subcomponents, e.g., afw.

**Comment by wmwv** [comment]
I agree that `desc.` should be the base.

**Comment by drphilmarshall** [comment]
Me too. Thanks Jim.

On Tue, Feb 2, 2016 at 6:49 AM, Michael Wood-Vasey <notifications@github.com

**Comment by drphilmarshall** [comment]
Thoughts from discussion between @rbiswas4 and @jchiang87 : provide setup script to set environment variables. Implement importable python structure as discussed. Do this in a branch so we can read the new README and view the proposed structure?

**Comment by jchiang87** [comment]
Closed by #147
