### ISSUE TITLE
Generate unique IDs for images of same object

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#106]
Currently, lens images have the same id number in the catalog. We will need to create new unique IDs that also contain information indicating they are different images of the same lens.

**Comment by jbkalmbach** [comment]
This happens now with the merging of #119 . But I want to include information for which OM10 we are using. I wanted to include information on OM10 lens id but the numbers were too big. However, when Phil gets #117 lenses I will give them a "Twinkles ID" since there will only be ~200 that will translate to the OM10 lens id so when can match Phosim instance catalog information to OM10 information.

**Comment by drphilmarshall** [comment]
Alright Bryce - #117 is cooked so you can tuck into the TDC lenses now. Have fun!

**Comment by jbkalmbach** [comment]
Implemented in #125
