### ISSUE TITLE
Hacking the Run 1 dataset validation at the March collaboration meeting?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#108]
@DarkEnergyScienceCollaboration/twinkles 

Check this out: the [collaboration meeting hack day web page](https://confluence.slac.stanford.edu/display/LSSTDESC/SLAC+2016+-+Friday+Hack+Day) is up, and I set a good example to the collaboration by pitching the following opportunity:

> **Explore the LSST Sim Universe with Twinkles** - (Twinkles Task Force) We'll make our Run 1 images and catalogs available for anyone to investigate.

I guess a few thumbdrives would be the best way to provide the data at this point (although a web-based data store would be better), and then presumably our validation code (such as it is) will be available for people to hack on. We could encourage people to fork this repo and have fun making plots etc, and then we can collect their code snippets into a more extended validation suite later. What do you think?

**Comment by drphilmarshall** [comment]
PS. The wider advertisement of the hack day confluence page will go out later today, so we have time to amend our project description :-)

**Comment by jchiang87** [comment]
We should try to get the SLAC Data Catalog to serve up those files (though having thumb drives also available would be wise).

**Comment by drphilmarshall** [comment]
Data Catalog ingestion now issued at #135 and referred to in #136
