### ISSUE TITLE
Validation plots of SL images, light curves

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#109]
We need to convince ourselves that light curves from real OM10 systems are being realized correctly in Twinkles. Thus, we should produce a set of validation plots to do this.

**Comment by drphilmarshall** [comment]
Renamed to include image plotting checks, as mentioned in #111

**Comment by jbkalmbach** [comment]
Here's a notebook with a comparison of OM10 plots and plots from catalog output.
https://gist.github.com/jbkalmbach/6c3f2c563d0baba6b1c9

**Comment by jbkalmbach** [comment]
I'll try to get Phosim going on my computer and see what these look like in images.

**Comment by drphilmarshall** [comment]
Looks good! Nice work, @jbkalmbach :-)

**Comment by drphilmarshall** [comment]
We should be able to see them in @TomGlanzman's images soon as well.
