### ISSUE TITLE
Run 1 Plan

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#110]
I brought the Run 1 plan up to date [here](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Run1.md), but it needs some gaps filling in.

* [x] @jbkalmbach can you please edit the lens sprinkling paragraph for accuracy? We should say roughly how many lenses are being put in.
* [x] @rbiswas4 can you please add a paragraph with what your plan is for including SNe in the Run 1 images? 
* [x] @TomGlanzman based on your experience with generating images, can you please add a statement of how many images we can expect to be able to generate, in, say, one week? 
* [x] @jchiang87 @danielsf Since we are running short on time, we might want to thin out the visit dates somehow: it would be annoying to generate 100 images and find that they were all taken in the same night. What's the easiest way to make a small image set that spans a whole 4-5 month season? Choose only the WFD visits? Or randomly downsample the list of visits?
* [x] @wmwv @SimonKrughoff can you please check through the plan and edit to fit? We need a link to the physics over-ride file, the name of the OpSim database we're using, maybe some more on what tests we *must* do before we show up at SLAC in March.
* [x] @tony-johnson So far we don't say anything about workflow development, but we should. Can you please add a few sentences on how we are using the workflow engine, for posterity?

Thanks!

**Comment by danielsf** [comment]
If you are using CatSim's ObservationMetaData generator to turn OpSim runs into CatSim pointings, it would be pretty easy to just query for all of the pointings that are on your desired patch of sky and then loop through them and only generate images from disparate nights.  I am imagining something that keeps track of the MJD of all previously generated images and refuses to generate an image for a specific pointing if its MJD is closer than some threshold to a previous image.

Are the images originating from Simon's generatePhoSimInput.py script in the Twinkles repo?  If so, I can put a pull request on that implementing what I have just described.

**Comment by jchiang87** [comment]
@danielsf Feel free to submit the PR, but what you propose sounds simple enough that we would just implement it ourselves as we'd need to generate the instance catalogs fairly soon, i.e., by some time early next week.

**Comment by TomGlanzman** [comment]
Based on rather limited experience (timing tests and pipeline workflow development), generating 1000 phoSim runs/images/visits over the course of a work week is a conservative estimate.  If there are no serious break-downs or resource bottlenecks, that number could be significantly larger, say x5 to x10, although the upper end of that range is speculative.  For the purposes of planning, please use 1000, but let's be prepared for 5000 in case we are lucky.

**Comment by jchiang87** [comment]
Here are plots of the cumulative number of visits for each band in `kraken_1042` for our DDF (fieldID=1427).   Without downselecting:
![all_visits_kraken_1042_fieldid_1427](https://cloud.githubusercontent.com/assets/1994473/12862358/b775f7a8-cc1f-11e5-9dc3-099da0dc3a60.png)
and limiting to one visit per night per band:
![one_visit_per_night_kraken_1042_fieldid_1427](https://cloud.githubusercontent.com/assets/1994473/12862365/d1fc1e22-cc1f-11e5-80d3-f15e11fd3fde.png)
We get about 40-50 visits per band per season (the vertical lines are at 150d intervals), so if we can generate ~1000 images, this corresponds to about 3 seasons.

**Comment by tony-johnson** [comment]
I have added a [paragraph](https://github.com/DarkEnergyScienceCollaboration/Twinkles/commit/1f0058bc66e8c680129bfa4ca6f9c8d1940f8475) on workflow and dataflow.

**Comment by drphilmarshall** [comment]
That's a lot of DDF visits: 25000 in 10 years! And so, about 2500 visits
per year, or (on average) about 400 visits per filter per year.

So, if we have the capacity to make a few thousand images between now and
the collaboration meeting, it looks as though we have a few good options:

1) Full DDF, from survey start to the end of season 1 (MJD 60000) - c. 2500
visits

2) 3 seasons of WDF (c. 300 visits) plus 1 season of DDF ugriz (c. 2000
visits)

3) 10 seasons of nightly downsampled DDF (c. 2500 visits)

4) Some other permutation?

@wmwv @rbiswas4 What would be best for the early SN tests you'd want to do,
before or at the collaboration meeting? Do you need the DDF time sampling?
Or multiple seasons? I like option 2, because it shows us what the WDF
(main survey) cadence looks like. I'm not sure how important the y band is
to you though (you could always drop a different one - or go with less than
a season - etc)

**Comment by drphilmarshall** [comment]
BTW: another nice feature of option 2 is that it would get us into the
habit of switching between the WFD and DDF proposals in our analysis.

**Comment by drphilmarshall** [comment]
@rbiswas4 @jchiang87 @TomGlanzman Let's look at the Run 1 plan together on Thursday. I think we can finalize the plan and close out this issue without anyone else's help at this point!

**Comment by drphilmarshall** [comment]
OK, I *think* the [Run 1 plan](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Run1.md) is more or less complete. Please take a look and see what you think, edit as you see fit - I added notes from today's hangout on the tests we think we want to do on the light curves (kept as simple as possible to get started).

**Comment by drphilmarshall** [comment]
Declaring victory, only 27 days after Run 1 was released!
