### ISSUE TITLE
Run 1 Progress Report: meet today at **12:30pm**?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#111]
Hi @DarkEnergyScienceCollaboration/twinkles 

I just tidied up our [Run 1 Plan](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Run1.md), and posted an issue on filling in its gaps ( #110 ). I'm wondering: should we meet next week to catch up on where we are with the image generation, sprinkling, DM processing etc? We are only 4 weeks away from the collaboration meeting now, and our stated goal is to show up with a good set of images, catalogs and validation proto-code - so it's probably a good idea to all check in and show where we are en route to this. How about towards the end of next week, perhaps on Thursday at 12 noon, in the dormant DM Reading Club slot?

**Comment by wmwv** [comment]
Yes, sounds good, let's meet and discuss.
I've reserved Thu, Feb 11 @ 3pm EST (noon PST) in my calendar.

**Comment by cdfassnacht** [comment]
Hi all,

Sorry I'll miss this.  We're interviewing faculty candidates now and that
slot is filled with a colloquium by one of the candidates.

   Chris

On Fri, Feb 5, 2016 at 8:31 AM, Michael Wood-Vasey <notifications@github.com
> wrote:

> Yes, sounds good, let's meet and discuss.
> I've reserved Thu, Feb 11 @ 3pm EST (noon PST) in my calendar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/111#issuecomment-180430093>
> .
>



-- 
Chris Fassnacht
Professor, Physics Dept.
UC Davis
1 Shields Ave.
Davis, CA 95616
+1-530-554-2600

**Comment by drphilmarshall** [comment]
Hi all!

Looking forward to catching up on Twinkles progress tomorrow at 12 noon PST! We'll use [BlueJeans](http://bluejeans.com), meeting room number 476071800

I have a suggestion for how we might look at things together: let's update the slides I made for the CI meeting on Monday with anything else you want to show/discuss tomorrow. [Here's the link to the Google presentation](https://docs.google.com/presentation/d/1lBeRriJdGWUrBZQrW3gWVMIWbsfwX9nJeS3El8x3M1k/edit#slide=id.g832d62438_0_0), left open on an empty slide entitled "Sprinkling" :-) @jbkalmbach @rbiswas4 @SimonKrughoff It would be *great* if you could give us an update on the lenses and SNe, using whatever words and pictures you need. Others, please take a look at what's already there and make updates as necessary. 

One thing we might like to do more of is supply more hyperlinks: if there's a plot, code snippet, issue thread or whatever that you want to discuss, please add a link to it in the slides. 

At 1000 PST I'll be attending the SSim meeting and giving them the same update I gave the CI group - but I'll use the same presentation, so anything you get in there before 10am will also propagate to the SSim group, which would be cool. 

Thanks - and see you tomorrow!

Phil

**Comment by drphilmarshall** [comment]
Hi all! 

Thanks for adding to the [slides](https://docs.google.com/presentation/d/1lBeRriJdGWUrBZQrW3gWVMIWbsfwX9nJeS3El8x3M1k), I think the SSim report in 30 mins should be good. 

We have a LIGO discussion here at 12 noon (right after out colloquium), so I think it's going to be hard for us to tear ourselves away. Could we reschedule to 12:30pm PST = 3:30pm EST please? Is this OK, @wmwv? 

Thanks!

Phil

**Comment by SimonKrughoff** [comment]
Where are we meeting?

**Comment by drphilmarshall** [comment]
[BlueJeans](http://bluejeans.com), meeting room number 476071800 - heading there now!

**Comment by drphilmarshall** [comment]
Good to see you all! And great that the cosmological objects are flooding in :-)
Issues arising:

* [ ] @rbiswas4 We need to adjust the supernova density so that we get a "sample" of a few hundred
* [ ] @drphilmarshall We need to dig out the right 200 lenses, from TDC1
* [ ] @jbkalmbach We need to verify the OM10 lenses using the OM10 plotting routine
* [ ] @rbisaws4 We need to check that the 1 visit per night per filter for 1 season plan checks out, in terms of total number of visits (few thousand or less) and total number of seasons (1). 
* [ ] @SimonKrughoff We need to make the Run 1 instance catalogs
* [ ] @TomGlanzman We need to prepare for Run 1 image generation to start on Thursday 2/18
* [ ] @tony-johnson We need to prepare for Run 1 DM Level 2 processing to start a week (or so) after that, c. 2/25
* [ ] @tony-johnson @TomGlanzman We need to be piping data outputs (most importantly the ForcedSource photometric catalogs) into the Data Catalog so they are accessible by all, over the web
* [ ] We need to work on our validation analysis code - which should query the Data Catalog. Light curve plotting and postage stamp image visualization will be important.

Would you mind issuing yourselves with these, please? I may not have used the right words.... Thanks! :-)

**Comment by drphilmarshall** [comment]
Alright Task Force, our issue list is looking in good shape! I made a new milestone, [Twinkles 1 Run 1 Data Generation Start](https://github.com/DarkEnergyScienceCollaboration/Twinkles/milestones/Twinkles%201%20Run%201%20Data%20Generation%20Start), with deadline next Thursday: these are the things that we need to do before we start the Run 1 data generation. When making new issues to add to this list, please assign them to this milestone - and if you see something that has already been done, please close the issue out and bask in its warm glow of tiny achievement :-)

Also, as you complete your issues, please do keeping posting links to notebooks, images, etc - we all want to see your results! :-)
