### ISSUE TITLE
Update DM workflow to pull input from output of phosim workflow

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#113]
Using the data catalog

**Comment by tony-johnson** [comment]
Tom is putting his output here:

http://srs.slac.stanford.edu/DataCatalog/?folder=14603345

**Comment by tony-johnson** [comment]
How do I know which and_files to use when processing these?

**Comment by jchiang87** [comment]
We should settle on some metadata (e.g., from the instance catalog, override file, etc.) to register these files with.

**Comment by tony-johnson** [comment]
![twinklesdm](https://cloud.githubusercontent.com/assets/11215747/13516518/d3ce9602-e16f-11e5-9357-c9d2b8a541a4.gif)

Workflow updated for multiple filters.

**Comment by drphilmarshall** [comment]
Sweet! :-)
