### ISSUE TITLE
Ten years worth of 10 arc-minute patches determined by OpSim: how much CPU is that for PhoSim?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#12]
Question from Richard, pre-hangout.

**Comment by drphilmarshall** [comment]
Debbie's answer: 

I can answer the first question, at least - ten arc-min of sky is roughly a single CCD (I presume it'll be dithered). If we want a single filter band over 10 years, that's 825 exposures (from the SRD). One exposure is roughly 6 CPU hours (~1 hour wall clock) if you don't have any bright stars in the field, so we're looking at 4950 CPU hours to do one chip in filter over ten years. In my experience, that would take ~1 day running at SLAC (and would require ~55GB disk space for the output image files).

**Comment by connolly** [comment]
Number of exposures for a single filter for one field would depend on the
filter but will be about 184x2 exposures for the r band (825 visits is for
all bands)

cheers
Andy
