### ISSUE TITLE
OM10 lens galaxies all have 1" effective radius 

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#120]
As hacked by @jbkalmbach and pointed out in #57. This needs fixing in the OM10 package, [issued here](https://github.com/drphilmarshall/OM10/issues/33). I am duplicating it so that I don't let this slip through the cracks.

**Comment by drphilmarshall** [comment]
Sonnenfeld and I worked on this during the Hack Day, and made some good progress I thought. We'll see if we can get a better OM10 in time for Run 2.

**Comment by drphilmarshall** [comment]
Update: we are planning to use CatSim galaxies in place of OM10 lens galaxies, matching by redshift and velocity dispersion #310

**Comment by jbkalmbach** [comment]
Closed by Merging of #334 to close #310
