### ISSUE TITLE
Run 1 Data Generation Start

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#129]
Hi @DarkEnergyScienceCollaboration/twinkles 

Lots of progress from Bryce, Rahul, Simon and Scott on the instance catalog prep, but are we ready to start data generation? Shall we meet up at 12:30pm PST today to assess the situation? We said we would, and time is getting very short... 

[Here's our to-do list from last time](https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/111#issuecomment-183081313): what still needs to be done to start the PhoSim runs?

**Comment by drphilmarshall** [comment]
Here's the [issue list associated with this milestone](https://github.com/DarkEnergyScienceCollaboration/Twinkles/milestones/Twinkles%201%20Run%201%20Data%20Generation%20Start) - 17 are still open!

**Comment by rbiswas4** [comment]
Which room is this?

**Comment by drphilmarshall** [comment]
Apologies, got held up. We'll use CI BlueJeans room,
http://bluejeans.com/476071800
See you there in a few minutes!

**Comment by drphilmarshall** [comment]
Good: Rahul, Bryce, Scott, Tom and I had a 45 minute huddle and came up with a plan for getting the Run 1 instance catalogs and SED tarballs from UW to SLAC, so that Tom can start running PhoSim on them. Bryce and Rahul have made about 100 visits' worth of inputs, and will make them available today. Watch out for issues regarding this data transfer. 

Also, the group will close as many issues as possible to keep our milestones clear.
