### ISSUE TITLE
Are SNe’s now available to CatSim? 

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#13]

**Comment by drphilmarshall** [comment]
Hey @rbiswas4 - I think you are very close to being able to close this issue, and also #26. Please do so as soon as you can, with the cheers of your grateful colleagues ringing in your ears! :-) :-)

**Comment by rbiswas4** [comment]
@drphilmarshall 

SNe Type Ia are now available in catsim releases. 

However, note that those are not the supernovae that we are planning on using in the sprinkler for Twinkles, though much of that architecture will be used. Let me clarify the situation:

- Current releases: 
SNIaCatalog: This has a basic implementation (there needs to be more input on distributions) SNIa catalog in much the same way I have planned before. This means you have SN whose properties (model parameters) are generated in situ drawing from distribution functions with a random seed specified by the host galaxy.
- FrozenSNCat: This is an implementation where the random generation is done by a separate program which outputs the the SN model parameters associated with the hosts of catsim. The database of SN model parameters is then stored on fatboy much the same way the galaxy parameters are stored. So the model parameters are frozen in the database. This is implementation that exists in a branch, but is not yet merged with catsim master. 

I believe that there are relative strengths and weaknesses of both implementations and it is possible that we will use both of them for different purposes. For the current Twinkles run, we will use FrozenSNCat.

So, perhaps the question of whether this should be closed yet in a Twinkles issue is unclear.

**Comment by drphilmarshall** [comment]
Excellent! Since the answer to the question in the issue title is now in
the issue thread, I say: close it out. Can you please update the Run 1 plan
file with the Run 1 supernova plan, please? Thanks! :-)

**Comment by rbiswas4** [comment]
ok. thanks. I am closing this then. But I have filled out the Run1 plan

**Comment by drphilmarshall** [comment]
Excellent, thanks Rahul! And thanks for cleaning up the SL part too,
@jbkalmbach . The plan is looking much better! :-)

https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Run1.md
