### ISSUE TITLE
We need to adjust the supernova density so that we get a "sample" of a few hundred

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#130]
A slightly different SN simulation on the Twinkles volume

**Comment by drphilmarshall** [comment]
Is this now in place? How many distinct supernovae do you expect to *detect* per year in the Run 1 images? And how many do you expect to have *good light curves* in the Run 1 images?

**Comment by rbiswas4** [comment]
> Is this now in place?
Well, the simulation is essentially in https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/SN_sims/kraken_sim.csv
You can also access it from the catsim database on fatboy thanks to  @yalsayyad

> How many distinct supernovae do you to detect per year in the Run 1 images?
https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/SN_sims/fiveSigmaDepths.ipynb
(This is a slow notebook)
output 110 has an approximate answer, It is approximate largely in that I neglected MW extinction, but it is relatively low in the Twinkles field. It plots the number of SN with SNR > 5. I believe that the SN are distinct, but will check more carefully. 

> And how many do you expect to have good light curves in the Run 1 images?
They should be as good in terms as the SN DDF in terms of cadence, but less in SNR by a factor of 4-5.

**Comment by drphilmarshall** [comment]
Thanks Rahul! From your plots, I guess you should get at least a handful of
SNe with SNR at peak brightness around 50, right? They should have good,
fittable light curves. (BTW this is all assuming that when you say "a SN
with SNR of 5" you mean a SN with brightness at peak corresponding to an
SNR of 5. If SNR means something different than that, let us know!)

**Comment by drphilmarshall** [comment]
@rbiswas4 This is another issue we can close on Thursday, I think.
