### ISSUE TITLE
We need to check that the 1 visit per night per filter for 1 season plan checks out, in terms of total number of visits (few thousand or less) and total number of seasons (1).

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#131]

**Comment by drphilmarshall** [comment]
I heard in our meeting that this was all good, right @rbiswas4 ? 1600 visits in 10 years in all filters should give pretty good (ie DDF) light curve coverage - the only thing we are losing is depth per night. You should close this if you're happy with your Run 1 instance catalogs!

**Comment by rbiswas4** [comment]
yes, as suggested by you, I am closing this issue.
