### ISSUE TITLE
Add a limit of r>11. to the genPhosimInput script

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#132]

**Comment by drphilmarshall** [comment]
@rbiswas4 are we making instance catalogs without that 10.5 mag star in them? I hope so! 

A possible hack is of course to `grep -v` the offending object out of each instance catalog we download from you. Is this a good idea?

**Comment by SimonKrughoff** [comment]
I believe this was done.  I'm closing it unless @rbiswas4 disagrees.
