### ISSUE TITLE
Discussion: generating PhoSim inputs outside UW

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#134]
OK, now that the sprinkling code has been completed (at least up to Run 1 functionality), we should figure out what needs to be done to get the PhoSim input generation running at SLAC (or NERSC, or wherever). In an ideal world, we would just `git pull` and then add one more script to the workflow - but it's bound to be more complicated than that. 

@danielsf you mentioned that remote CatSim access was available - are we using that, or why not?

I think we'll need to have  a local copy of the relevant OpSim database.

We not only need to make instance catalogs, we also need to make SED files - @rbiswas4 what are the roadblocks here?

It looks as though the [cookbook](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/twinkles_cookbook.md) has fallen behind, in that it doesn't mention any sprinkling steps. This file needs updating or replacing, I think. Probably we should spend some serious time before and at the collaboration meeting planning and/or working on our documentation...

**Comment by rbiswas4** [comment]
> I think we'll need to have a local copy of the relevant OpSim database.

That is easy to download. : https://confluence.lsstcorp.org/display/SIM/Operations+Simulator+Benchmark+Surveys

> We not only need to make instance catalogs, we also need to make SED files - @rbiswas4 what are the roadblocks here?

The code in catsim (package: sims_catUtils, branch: newTwinklesCatalog, not merged to master yet ) that I am currently using for this process allows you to specify a 'prefix' and all spectra files are written to 
prefix_identifier.dat. Identifier is a combination of the SN id, MJD to a precision of 0.0001 (8 secs, so each visit/snap is identified) and bandpass for convenience. As you have seen, Once we are in communication with the catsim database, this functionality will work just as well as it has been working for me. Of course, improving my at this point hacky zipping, cleanup, transfer scripts  etc. would be useful.

**Comment by johnrpeterson** [comment]
On Feb 18, 2016, at 4:40 PM, Phil Marshall <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, now that the sprinkling code has been completed (at least up to Run 1 functionality), we should figure out what needs to be done to get the PhoSim input generation running at SLAC (or NERSC, or wherever). In an ideal world, we would just git pull and then add one more script to the workflow - but it's bound to be more complicated than that.

Phil, not to be a broken record on this, but all you need to do it a git pull followed by a “phosim catalog -g condor”.  this is what we’ve been doing for years on the HTC grids.

john

**Comment by drphilmarshall** [comment]
That has indeed been noted! I was actually referring to more mundane
things, such as getting the sprinkling code working here, and getting
remote access to CatSim and local access to OpSim, etc.

**Comment by drphilmarshall** [comment]
Re-assigning to Tony as part of his ongoing workflow dev effort. We'll discuss more next week!

**Comment by jchiang87** [comment]
With the SLAC and NERSC computers whitelisted at the UW db servers, and with the new w.2016.40 sims distribution, this is done.

**Comment by danielsf** [comment]
@jchiang87 are we sure that the NERSC computers that we will be using have been whitelisted?  I know we whitelisted Cori.  I don't think we whitelisted Edison (unless you have experimental evidence that we did).

Basically: I am asking if I need to add something to the whitelist.

**Comment by jchiang87** [comment]
I haven't checked for Edison.  I think we probably do want to add the Edison machines.  @tony-johnson @djbard Any thoughts?

**Comment by djbard** [comment]
The IP addresses for Cori nodes will have changed after integration - will the whitelist require updating? 
I think whitelisting Edison is a good idea.

**Comment by danielsf** [comment]
@djbard Yeah.  We are going to have to update the whitelist.  I will contact the help desk.

**Comment by danielsf** [comment]
Edison nodes have now been whitelisted for fatboy access
