### ISSUE TITLE
Serve Run 1 data via Data Catalog

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#135]
Hi @TomGlanzman - are you set up to ingest the Run 1 visit eimages into the Data Catalog as they are made? @jbkalmbach wants to see how his lenses turn out!

Here's the link to the [Twinkles Data Catalog](http://srs.slac.stanford.edu/DataCatalog/?folder=14603345) - looks like its currently empty, after the test files were cleared away I guess. Great if you can fill this up in some intuitive way, Tom!

**Comment by TomGlanzman** [comment]
The data catalog is currently empty.  Given inevitable start up glitches, do not expect anything sensible until I publish a URL.

**Comment by drphilmarshall** [comment]
Got it. Stand by, Bryce!

**Comment by drphilmarshall** [comment]
Re-posting from @TomGlanzman 's https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/137#issuecomment-189335922:

> Five test runs are now complete and the data are available via the data catalog. Navigate to http://srs.slac.stanford.edu/DataCatalog/?experiment=LSST-DESC then to /LSST-DESC/Twinkles/Twinkles-phoSim/singleVisit. The five complete runs include task streams 0,1,2,5,13. The remaining 12 jobs are still running at this time. Note that stream 0 (corresponding to Opsim_obhistid 484933) had its instance catalog stripped down to four sources; at some point, I should rerun that one with the full catalog.

So we are halfway to closing this one :-) @tony-johnson Let us know when there are DM Level 2 products to be browsed as well!

**Comment by tony-johnson** [comment]
We did not make the DM level 2 products available via the data catalog at present, because it is not obvious how to marry the butler and data catalog. This is an issue which we will follow up with the DM team at SLAC.

**Comment by drphilmarshall** [comment]
Sounds good. Thanks!
