### ISSUE TITLE
DM Level 2 processing of Run 1 images

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#136]
Hi @tony-johnson - as you may have seen, @TomGlanzman is starting the Run 1 data generation! I guess the first images will be coming in later today, and within a week or so we should have the first few seasons done (c. few hundred images). What's the status of our DM Level 2 processing pipeline? Can we be ready to analyze the first 3 seasons of images in about a week? And how long will the DM processing take, do you think?

I guess there are some open issues still, relating to the analysis pipeline and workflow itself ( #112 and #113 ), plus we might need another one to help us get the DM products into the data catalog, analogous to #135. Do you need help from anyone on these?

**Comment by tony-johnson** [comment]
Done, but need to update files in github still.

**Comment by drphilmarshall** [comment]
Coooooool. How many Visits, how many ForcedSources?

**Comment by tony-johnson** [comment]
Actually my "done" meant that the workflow is set up. I used it to process the first 817 visits last night, but encountered some problems (#161, #162, #163). All of these can be worked around, for example by skipping problematic visits (at the risk of introducing some bias) but mean it will take a little longer before the data processing is complete.

**Comment by drphilmarshall** [comment]
I see! 800 visits is a pretty nice campaign, 7 years or so I guess (if we
are indeed processing in MJD order). Has the frces photometry been done on
these 800, or is the engine waiting forall image processing to finish?

**Comment by tony-johnson** [comment]
This was done for the collaboration meeting. We should create new issues for any future processing.
