### ISSUE TITLE
Avoid using the same CatSim galaxies for both SNe and lensed AGN

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#139]
Sounds obvious but apparently we aren't doing this yet. Are we, @jbkalmbach ?

**Comment by jbkalmbach** [comment]
No, I could make a list of galid numbers that are currently lensed. @rbiswas4 is there any way you can make a list of the galid numbers that get SNe so we can compare? If there's no problem in the current run then we can fix this before the next run, but if it's a problem in the current catalogs it would be good to know so we can fix it right away.

**Comment by rbiswas4** [comment]
Yes, I can also easily find the galids for SN hosts. So, technically, right now, the easy thing to do is filter by common hosts. As @drphilmarshall  was mentioning here, this does not preclude nearby objects, but we can ignore those till we know they are in fact an issue.

**Comment by wmwv** [comment]
How many times is this actually happening?  I've just always assumed it's < 1% and chosen not to worry about it, certainly not until Twinkles 2.

**Comment by rbiswas4** [comment]
@wmwv That might be true, we have not looked. I had not even thought about the possibility till @drphilmarshall mentioned it the other day, and it would be good to at least have this an explicit issue  and develop a flag to catch such occurances. Right now, our method to find out whether this happened is more roundabout that I would like.

**Comment by jbkalmbach** [comment]
Closed by #356 and plan to move forward with a csv file containing the ids to avoid when adding supernovae [`agn_lens_ids.csv`](../tree/master/data/agn_lens_ids.csv).
