### ISSUE TITLE
How much of the DM stack is available today to get to a catalog?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#14]
Do we know what steps we would execute?

Questions from Richard, pre-hangout.

Having a sense of which basic measurements are possible right now is a good idea. Maybe @SimonKrughoff can summarize, or point us to a good DM README?

**Comment by drphilmarshall** [comment]
Robert Lupton told me earlier that the current activity on the DM stack is in merging the HSC release into LSST master - and that while this will not include MultiFit, it will include forced photometry. Which means we should be able to start trying to extract lightcurves sooner rather than later!

**Comment by wmwv** [comment]
Things currently easily available in the DM stack include:
Source detection
Measurements of sources: PSF flux, elliptical aperture flux, centroids, basic shape information

**Comment by wmwv** [comment]
I have tested out basic image subtraction and it seems to work fine.  It can be a bit sensitive to the quality of the input star catalog and may need some parameter tweaking for the allowed Alard-Lupton spatial variation, but this should be straightforward.

**Comment by drphilmarshall** [comment]
Great! That makes the diffsource catalog pretty interesting. Is forced
photometry available yet?

**Comment by djbard** [comment]
Yes, forced photometry is available - it's described in the SDSS example [here][sdss]:  but it doesn't seem to be as well documented as some of the other tasks. There's a pipe_task [here][pt]
[sdss]: https://confluence.lsstcorp.org/display/LSWUG/Process+SDSS+Stripe+82+Images
[pt]: http://lsst-web.ncsa.illinois.edu/doxygen/x_masterDoxyDoc/classlsst_1_1pipe_1_1tasks_1_1forced_phot_1_1_forced_phot_task.html

**Comment by drphilmarshall** [comment]
We know a lot more about this now - see notes in #54
