### ISSUE TITLE
SED file overload, organization

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#145]
So many SED files! Strategy for dealing with this have been discussed, implementation of a solution appropriate to Run 1 is required.

**Comment by TomGlanzman** [comment]
Given the unreliability of phoSim to read gzipped instance catalogs, I have rolled that issue into this one.  The solution implemented uncompressed the instance catalog into a temporary scratch space, along with the unpacked (and uncompressed) SED files ("spectra_files").  The remaining bit is to create a symlink directory mirroring the normal phoSim SED file library and inserts a link to "spectra_files".  This appears to be working.

**Comment by rbiswas4** [comment]
I think a decent solution to this problem would be to write all of the spectra to a hd5 file in different tables.
This would result in 
Pros
- As single spectrum file seen by the unix filesystem
- fast (if required parallel IO) on the entire set of spectra. I personally believe this will help the step of writing out instance catalogs in cases like Twinkles where we are writing out too many spectra.
- Space required will be much less that the curren ASCII representation
Cons:
- No easy less like functionality to read easily

Of course, this will require work on both the catsim end (write out the spectra as hdf files)and phosim end (reading hdf files for spectra) to work. As API to write and read hdf are available in C/ python this should be easy in principle. Is this something we want to do and would like to put in a request this feature in phosim?

**Comment by TomGlanzman** [comment]
The scheme described in my post above worked well for Run 1.  Unless others with to continue discussion or offer alternatives, will close this issue.
