### ISSUE TITLE
Investigate globus instance catalog file transfer

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#151]
As suggested in https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/133

**Comment by TomGlanzman** [comment]
This works fine and was used to transfer ~80 GB of instanceCatalogs/SEDs from NERSC to SLAC for Twinkles Run 1.

**Comment by cwwalter** [comment]
What is the relevant SLAC globes endpoint for future reference?

**Comment by TomGlanzman** [comment]
I used slac#osg but have been using this for BNL data transfers for a couple of years, and do not recall what hoops I jumped through to use this endpoint.

**Comment by cwwalter** [comment]
OK as test I tried to access it.  It asks to authenticate through osgmyproxy.slac.stanford.edu

I tried using my SLAC unix credentials but they don't work.

**Comment by TomGlanzman** [comment]
Chris, if you need to use this endpoint, please contact Wei Yang, the gatekeeper: yangw@slac.stanford.edu.

**Comment by cwwalter** [comment]
Thanks.  I don't need it now but wanted to check/document it for the future.
