### ISSUE TITLE
What do the Run 1 lensed quasars look like?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#155]
Hey @jbkalmbach did you see @jchiang87 's postage stamp code in #149 ? Since you know the lens RAs and dec's, I guess you could start pulling out our targets from @TomGlanzman 's images ( #137 ) and displaying their images. Show us some lenses! :-)

**Comment by jbkalmbach** [comment]
I started to look at the images on the data catalog online but wasn't getting what I expected when I tried to make postage stamps. So, I looked at the centroid files and noticed that the ids for the sprinkled AGN from the instance catalogs are not in the 'SourceID' column in the centroid files. There are some 'SourceID' values that look similar but do not match the instance catalog. Does anybody have any idea why this might be?

**Comment by drphilmarshall** [comment]
Hmmm. This does not sound good! Are the supernovae IDs in the centroid
files?

**Comment by jbkalmbach** [comment]
Rahul and I took a look at this and it seems that it might be caused by a precision error when phosim converts all ids to a float. We looked at a small example phosim output and found that the id of an object was off by a small integer number of values in the centroid file from the phosim catalog.

**Comment by jbkalmbach** [comment]
However I was able to use @jchiang87 to get a postage stamp image of where a lens system is located. Here it is! Obviously not ideal, but definitely gives us something to talk about in the morning.
![stamp_0](https://cloud.githubusercontent.com/assets/4755090/13630905/a27d15b2-e596-11e5-8bd9-3d5ca98bb6fd.png)

**Comment by jbkalmbach** [comment]
However, one comment about the postage stamps I want to make is that it should at least be centered on the bright part of the image since I gave it the catalog values for the lens galaxy, but it seems to be off. Is there a reason why the coordinates from the catalog and from the image might be slightly different?

**Comment by jbkalmbach** [comment]
Here's another fun one: 
![stamp_1](https://cloud.githubusercontent.com/assets/4755090/13631903/e8dede00-e59b-11e5-9b32-a859240dcf41.png)

**Comment by drphilmarshall** [comment]
I SEE AGN TWICE! :-) :-) :-) See how much more fun this project is with
lensed quasars than without? I was putting a brave face on it yesterday
evening. Well done for tracking them down, Bryce.

There should be some fainter systems where the lens galaxy is bright and
visible (maximal OM10 velocity dispersion at z > 0.2) compared to the faint
AGN images (high OM10 image magnitudes)  - I'd go after some of those next.
A gallery of color images would be really helpful - the red colors of the
lenses should pop out.

**Comment by SimonKrughoff** [comment]
@jbkalmbach If you are just using the WCS that comes from phosim, I don't think it's good to more than a few tens of pixels.  We didn't turn of tracking errors, so there is some wobble in the boresite.  That may be what you are seeing.  It should get much better after running through the DM pipelines.

**Comment by danielsf** [comment]
@jbkalmbach Also worth noting that the InstanceCatalog RA and Dec are unrefracted.  PhoSim applies atmospheric refraction, which will be another shift in object positions.

**Comment by jbkalmbach** [comment]
Ok, as these were single epoch images I will check for consistency in the coadds. @danielsf does that get taken care of in dm processing?

**Comment by drphilmarshall** [comment]
@jbkalmbach @danielsf I have a feeling this issue could be closed, if the problems identified are correctly issued elsewhere and referred to here. Can you make sure of this and then shut this down please, Bryce? Thanks!

**Comment by jbkalmbach** [comment]
Yes, I think this can be closed. Problems from this are related to issues #175 and #168 and can be discussed there.
