### ISSUE TITLE
Impromptu Twinkles analysis discussion, this afternoon

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#156]
Hey @DarkEnergyScienceCollaboration/twinkles 

If you're around at 2pm PST, why don't we meet up in [the CI group BlueJeans room](http://bluejeans.com/476071800) and chat about Twinkles Run 1 analysis? Rahul has been out of action for a couple of days, and needs to be caught up - and we can use the time to run ideas for analyses past each other. Sound good? See you in 90 minutes if so!

**Comment by tony-johnson** [comment]
Jim and I are in the room, but it is very quiet.

**Comment by cwwalter** [comment]
You should try talking :)

**Comment by rbiswas4** [comment]
Having a hard time reconnecting from both Simon and my computer.

**Comment by drphilmarshall** [comment]
I wish GitHub had a "like" button, so I could appreciate Walter's little gems. 
We had a nice little tag up, @SimonKrughoff dropped in and cleared up some things for us, not least that we now expect Tony's `ForcedSources` to have the same `object_id` in all filters, which shoudl make life easier. I'm doing some issuing based on the meeting now.
