### ISSUE TITLE
Mirror PhoSim / DM Level 2 output folders at NERSC

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#158]
Well, we should start with the DM outputs, so that @jbkalmbach and @rbiswas4 can do all the analysis they want. Thanks @tony-johnson !

**Comment by wmwv** [comment]
What's the status of providing output data from the DM processing?

**Comment by tony-johnson** [comment]
The 10 visit data was posted a few days ago, see #137. A run of 985 visits is currently running:

http://srs.slac.stanford.edu/Pipeline-II/exp/SRS/task.jsp?task=41342594

and will hopefully be finished later today, but see issue #166 for some concerns. My NERSC account is not currently active (apparently I did not send them an updated user agreement) so I am not sure if I will be able to copy the output to NERSC before Monday.

Tomorrow I expect to start the final processing of all the phosim runs which complete successfully.

**Comment by tony-johnson** [comment]
Unfortunately the 985 visit level 2 output has run into problems, the measureCoaddSources ran for 24 hours and then ran out of CPU limit. I will resubmit it, but unless I can find a way to speed it up (using multiple threads?) that means it will be at least another 24 hours and perhaps much longer before it will finish.

Meanwhile I do have the output from a 100 visit test run that I did yesterday. I will look today at copying the output from that somewhere other can access it.

**Comment by drphilmarshall** [comment]
Thanks Tony: 100 visits is close to a whole season, so that's good. (Did
you choose a sequential block of MJD's?) Interested to see what's causing
the long CPU times! Seems like a good bug to catch :-)

**Comment by wmwv** [comment]
@tony-johnson Can you kindly point me to the results from the 100-visit test?

**Comment by tony-johnson** [comment]
@wmwv At SLAC the 100 visit run is in:

/nfs/farm/g/lsst/u1/users/tonyj/Twinkles/run1/100visits

the 965 visit run is almost finished and will hopefully be copied to a parallel location soon. I will then be copying them both to NERSC later this morning.

**Comment by wmwv** [comment]
@tony-johnson Great.  Thank you.  Starting to look at these now.

**Comment by jchiang87** [comment]
Hey @tony-johnson, 

Do you have runs that have the forced source output?  I've been reimplementing Simon's plot of stdev(mag)/med(mag) and I need the forced sources results for that.   I didn't see any `forced` folder in the work area last night.

**Comment by tony-johnson** [comment]
@jchiang87 There should be forced sources in the 100 visit output I pointed to above:

/nfs/farm/g/lsst/u1/users/tonyj/Twinkles/run1/100visits

Tony

**Comment by tony-johnson** [comment]
The 985 visit processed data is now available at SLAC in:

/nfs/farm/g/lsst/u1/users/tonyj/Twinkles/run1/985visits/

In addition the 100 visit data has been copied to NERSC and is in:

/global/homes/t/tony_j/Twinkles/100visits

Once I find a location with more disk space (@djbard?) I will also copy the 985visit data to NERSC.

**Comment by djbard** [comment]
Hi tony,
 you can use your $SCRATCH space - which has 20TB of space on Cori. This is
purged every 12 weeks, so keep an eye on that.
 FYI: we have a convenient script to make everything in a directory
accessible to your group (by default it is not, of course).
> fix_perms -g lsst /path/to/the/dir
might be useful :)
 -Debbie

**Comment by tony-johnson** [comment]
The 985 visit run data is now also copied to NERSC (cori) in:
/global/homes/t/tony_j/Twinkles/985visits
(actually a symlink to $SCRATCH).

@djbard -- the fix_perms was not entirely successful, it generated many messages of the form:

/bin/chgrp: changing group of `985visits/': Operation not permitted

although it also appeared to make all the files world readable.

**Comment by djbard** [comment]
OK, I can't actually see into that directory so evidently something didn't
work for fix_perms. It looks like you're not actually a member of group
"lsst", although you are a member of "m1727", which is the name of the DESC
repo. It looks like these are two different unix groups associated with our
repo at NERSC - lsst and m1727 (I note that I am not a member of m1727).
This is confusing (and points out a larger issue of confusion between
"lsst" and "desc" repos - which are the same thing but are multiply named).
The PIs (Richard and Peter) probably need to figure out if they want to
consolidate this.
 Anyway, I've added myself to unix group m1727 and will see if I can access
your files once that change propagates to Cori.
 -Debbie

**Comment by djbard** [comment]
ah - I think I see the/another problem Tony. Your scratch directory does
not have group access permissions set, so I can't see inside it (even
though the interior directories have read permissions).

**Comment by tony-johnson** [comment]
I think I have now set world rx permissions on my scratch folder and the Twinkles folder inside

**Comment by djbard** [comment]
great - I can see all your files and I expect others can too.
