### ISSUE TITLE
Where should the Twinkles images and DM catalogs be generated?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#16]
From Richard:

For simulations resources, I assume we could use grid resources and/or SLAC. NERSC is still problematic in general for PhoSim, though it could be that the postage stamps are sufficiently similar that the block booking of MPI nodes would be efficient. Tom can explain better in person.

**Comment by drphilmarshall** [comment]
At the hangout today Scott reported that they are successfully running end-to-end simulations and DM analyses at NERSC, using a set of shell scripts to link the parts together. Comparing notes could be both interesting and helpful, given Tom's parallelisation difficulties.

I guess this could also be a Run-specific question: if we make Run 1 the Simplest Thing, that might well dictate how and where the data are generated. We talked about the need for a high level of reproducibility in the Run 1 scripts, so that they can be both easily re-run, and helpfully compared with alternatives. Hopefully this will all help drive the development of various software frameworks, workflow engines etc etc .

**Comment by drphilmarshall** [comment]
Richard added in his email, that:

"We think using the pipeline/catalogue system developed for Fermi could work well, but there still need to be discussions with JimK and Saba on how this might fit with their end-to-end work with Galaxy and CosmoSIS."

**Comment by wmwv** [comment]
I think a more fair statement is that "PhoSim is not designed to run efficiently on typical clusters."  It is perfectly runnable at NERSC.  It's just inefficient and one feels a bit silly when doing so.

A technical improvement that a different cluster might provide is longer wall clock times in serial queues.  But this is pretty specific and the pseudo-checkpointing in PhoSim is sufficient to work around any of the current limitations.  We could also just ask NERSC for an increase in this limit if that made a significant difference.

The overall issue is that there's no way to make PhoSim run in a really short amount of total time using a large number of cores.  But if your time unit is a day, that's OK you can just run each chip (or in this case each epoch) in parallel.

**Comment by drphilmarshall** [comment]
Certainly for Run 1 I am in favour of continuing to work in "pleasingly
parallel" mode, as Richard calls it :-)
