### ISSUE TITLE
Centroid file SourceID numbers for lensed AGN differ from Phosim Input Catalog id numbers

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#168]
Quoting from #155:

> @rbiswas4 and I took a look at this and it seems that it might be caused by a precision error when phosim converts all ids to a float. We looked at a small example phosim output and found that the id of an object was off by a small integer number of values in the centroid file from the phosim catalog. Rahul, I think you mentioned that you saw this before?

Is this in fact the problem? And if so, what can we do about it?

**Comment by drphilmarshall** [comment]
[ShakesFistAtHeavens]

**Comment by cwwalter** [comment]
:+1: (See Phil, it is possible) :)

**Comment by drphilmarshall** [comment]
Hey @jbkalmbach , is this problem now resolved?

**Comment by tony-johnson** [comment]
@jbkalmbach Can this issue be closed? Moving to "Post Run 2 Tasks" milestone for now.

**Comment by jbkalmbach** [comment]
Now a phosim ticket: https://jira.lsstcorp.org/browse/PHOSIM-27

**Comment by jbkalmbach** [comment]
@rbiswas4 @danielsf I think #340 sufficiently works around this problem and we can close this, what do you think?

**Comment by rbiswas4** [comment]
We should close this for the current run (solved), but I don't think we have a general solution since this will fail on all sky runs. Maybe this gets added to lessons learned?

**Comment by danielsf** [comment]
Agreed.

I don't think there's anything we can do for all sky runs.  That's on PhoSim.
