### ISSUE TITLE
Connect Twinkles to Travis CI using Mario's conda install script for lsst-sims

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#169]
Mario describes this work over at [community.lsst.org](https://community.lsst.org/t/how-to-use-the-stack-with-travisci/587) and in his [github repo](https://github.com/mjuric/lsst-travis-demo).

We should also rewrite `python/desc/twinkles/__init__.py` so that it doesn't import everything by default to save some time for client code that doesn't need the catsim tools.

**Comment by mjuric** [comment]
@jchiang87 et al: I'd be happy to consult & help!

**Comment by jchiang87** [comment]
@mjuric Thanks for putting the travis-ci demo and conda distribution together! I think they will be a big help in getting the DESC repos working with travis-ci. 

I was able to get things working over in my fork (where I have admin privileges to hook up to travis-ci) and issued the PR (#170).  I  did need to install `pandas` (and `nose`) on top of the conda python, but other than that, everything else basically worked out of the box.

**Comment by jchiang87** [comment]
Hey Phil!  Please hook us up to Travis CI.   You can close this once we get a travis passing badge on the readme! ;-)

**Comment by drphilmarshall** [comment]
Done! [Check it out.](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/README.md#latest-news)
