### ISSUE TITLE
End to End workflow for producing observed DM catalogs from input PhoSim catalogs

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#17]
This has overlap with some other issues, but I want to put down my thoughts on how to do this coherently and we can merge/close issues if they are obsolete.  Since twinkles will have to do this, it seems only natural that we at least consider how to solve the problem in general.

It came up in the Computing session today, Feb 3, that making it easy to do the things that everyone has to do to execute a data challenge would be helpful.  In a data challenge, everyone has to produce the data.  In very general terms, this typically involves taking a truth catalog (eg a catalog of strong lenses) and producing an output catalog of observed quantities.  @wmwv and @rmjarvis agreed that making this functionality easy would be of general use to the project.  We discussed it some and came up with the following thoughts on the issue.

How do we provide this functionality?  One way is to have scripts that:
1. Parse input user-defined text file
2. Create input to phosim from user-defined catalog and possibly other catalogs
3. Run phosim on input files
4. Put phosim outputs in a format the DM stack understands
5. Run DM calibration, detection and measurement
6. Possibly post-process the outputs of DM processing

These scripts exist in one form or another, but they are ad-hoc, hard to parallelize, and hard to configure.  Further, people may not want to do the phosim -> DM -> output catalogs part.  They may only need a rough idea of the error properties on the measurements, or they may want to run GalSim instead.  This implies the output catalog generation should be pluggable.  Since this could span many orders of magnitude in compute time, the parallelization mechanism should also be flexible and transparent to the user.

In summary, we have all the functionality in place to do this task, but it needs to be better.  Requirements are:
* The system will take (a) catalog(s) and produce observed quantities consistent with the LSST system.
* Distributed computing credentials and configuration should be transparent at least on the resources commonly available to DESC members.
* The mechanism should be able to run on clusters or on the local resources transparently.
* The algorithm for producing observed measurements from input catalogs should be configurable and easy to implement.
* We will have to do something about delivering the output catalogs.

I have very little idea of how hard this is.  The workflow products we have seen can do some of this, but I don't think they are a complete solution.  The main thing is that this has to be very easy to use.

**Comment by wmwv** [comment]
I think it's also important to make the images accessible as well.  In priority order, I think users will want access to
1. Merged catalogs
2. Image catalogs
3. Input catalogs
3. Calibrated images after processing by DM
4. Raw images as simulated

**Comment by richardxdubois** [comment]
We can look at using the catalogue Tony described yesterday in the SW session. It should handle all of this, including metadata. Jim Chiang also wrote an interface between the catalogue and DM's butler.

Richard

**Comment by drphilmarshall** [comment]
@TomGlanzman @tony-johnson @SimonKrughoff and I discussed briefly an end-to-end workflow today. We noted that @cwwalter made a good point about needing to keep the Image Simulation workflow separate form the DM Processing workflow, because one day we might have the Universe plus one of its telescopes replace the Image Simulation one while the DM Processing one remains (in principle!) the same. However, connecting the two workflows together is clearly something we'll be trying desperately to do in the last week of August before the DC1 DG deadline. For now, I'm going to close this, so we can open a "Connect Sim and DM workflows together" later, perhaps when we are ready to go into serious production.
