### ISSUE TITLE
Upgrade stack on the cluster

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#172]
We appear to be using a reasonably old stack (mid Jan).  I noticed that one of the defaults was wrong and has been fixed on a more recent version of the stack.  Not super high priority, but I think we will want to run Run 1 again and it would be good to do it on a more modern stack.

**Comment by wmwv** [comment]
Rerun the DM stack processing of Run 1.

Not a request to re-run the PhoSim generation of the images.

**Comment by jchiang87** [comment]
I installed  a new version here:
```
/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/
```
but I had some problems building against the needed branch of `obs_lsstSim`, and also couldn't get the multiwaveband version of the cookbook to run using it.   @SimonKrughoff  Can you try whatever tests you may have on it please?

**Comment by SimonKrughoff** [comment]
We may also want to rerun the phosim generation depending on how many lens systems ended up making it into the images.  I get the impression most were tossed out because of the id problem.

**Comment by SimonKrughoff** [comment]
@jchiang87 Thanks.  I'll have a look.

**Comment by jchiang87** [comment]
To run on a rhel6-64 machine at slac, run the script
```
/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/run_obs_lsstSim_setup
```
This will create a bash shell with devtoolset-3 with obs_lsstSim set up.

**Comment by SimonKrughoff** [comment]
I just updated the ticket branch to bring it in line with DM-4692.

I also removed the offending test that was failing because it was testing deprecated functionality.  All tests should pass and processEimage should run.  I have not tested further.  It will require a reclone since I had to rebase and force push.

**Comment by jchiang87** [comment]
Thanks @SimonKrughoff .   I've cloned the new version of `obs_lsstSim` and rebuilt.  The tests all worked (yay.) so this stack install should be ready for further testing.

**Comment by tony-johnson** [comment]
I used Jim's updated DMstack install to re-run the 10 visits which failed in processEimage, but they all failed still. The output can be found here:

http://srs.slac.stanford.edu/Pipeline-II/exp/SRS/process.jsp?status=FAILED&pstream=41348677&process=41342608
