### ISSUE TITLE
Doodle Poll for Twinkles Retreat

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#179]

**Comment by SimonKrughoff** [comment]
This will be closed when @jbkalmbach manages to publish the link.

**Comment by jbkalmbach** [comment]
@DarkEnergyScienceCollaboration/twinkles here is a link to a poll with possible weeks for a twinkles retreat. Please respond with your availability.

**Comment by drphilmarshall** [comment]
Many of us here are at SLAC are at the Fermi Collaboration meeting this
week, so response may be a little slow! You might ping this thread again in
a week's time, Bryce. Thanks!

**Comment by jbkalmbach** [comment]
@DarkEnergyScienceCollaboration/twinkles here is the link again for the doodle poll for a Twinkles retreat in the fall.

http://doodle.com/poll/xpdcrkdzhaverii2

**Comment by drphilmarshall** [comment]
Thanks for filling out the retreat doodle poll at http://doodle.com/poll/xpdcrkdzhaverii2 - @wmwv @richardxdubois have not filled this out yet, perhaps because they weren't there at the Hack Day lunch when we started talking about this... We'll talk about it at Thursday's meeting!

**Comment by wmwv** [comment]
@wmwv doesn't think he'll be able to make it due to teaching commitments.

**Comment by drphilmarshall** [comment]
@richardxdubois @tony-johnson @TomGlanzman The [CHEP2016](http://chep2016.org/) meeting is October 8-14. What do you think about having the Twinkles retreat the week right after that? Could be a nice change, no? :-) 

The week of October 17-21 is currently the most popular week on the [doodle poll](http://doodle.com/poll/xpdcrkdzhaverii2), although Richard still hasn't voted. The update from Michael is that he'll try and join for a couple of days, whenever we have it.

**Comment by drphilmarshall** [comment]
A couple of weeks ago we settled on the week of October 17th for the Twinkles Retreat. Should be a nice break from CHEP2016 the week before. Mark your calendars!
