### ISSUE TITLE
WorkFlowChart

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#18]
Tony and Saba?

**Comment by sabasehrish** [comment]
Yes. There are two possible projects we can look into.

1. What it takes to run some of the components from the  end to end use case (the one we used in Galaxy and Python-based approach) presented in SW1 session to EXO pipeline? That may lead to the integration of the two systems, may be?

2. Get a complete workflow of twinkles in as much detail as possible and try to make a workflow figure of the complete 6 steps with possibly more steps added in place of step 6. This may lead to its implementation using Galaxy.

Saba

Sent from my iPhone

On Feb 5, 2015, at 11:33 PM, Phil Marshall <notifications@github.com<mailto:notifications@github.com>> wrote:


Tony and Saba?

**Comment by tonyj321** [comment]
The first thing we need is to understand the end-to-end workflow for Twinkles, and I don't think this is something that Saba and I can do alone, we will need detailed discussion with all of the experts to understand what are the steps involved, what is the input and output from each stage, how much computing time would be needed etc.

**Comment by drphilmarshall** [comment]
Good: that means that you should start the day shadowing @SimonKrughoff and me as we get started on #19!

**Comment by drphilmarshall** [comment]
Hey @tonyj321 can you provide a link to the flow chart confluence page, please? And maybe paste a png snapshot into this issue thread for presentation purposes?

**Comment by tonyj321** [comment]
The workflow confluence page can be found here:

https://confluence.slac.stanford.edu/x/vY8lCw
