### ISSUE TITLE
Get Twinkles On The Sky

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#19]
Do whatever it takes to produce the first Twinkles image. @drphilmarshall is in.

**Comment by SimonKrughoff** [comment]
This is where we [start](https://stash.lsstcorp.org/projects/SIM/repos/sims_catutils/browse/examples/generatePhosimInput.py)

We also need to get code setup on a machine so we can run this.  See [here](https://confluence.lsstcorp.org/display/SIM/Catalogs+and+MAF) for install instructions.

**Comment by drphilmarshall** [comment]
I have all this installed. That looks like a useful recipe. Is the idea that we cut, paste and edit it for our purposes before checking it in here? I notice it is neither a def nor a class - we might need to spend some time talking about that.

**Comment by drphilmarshall** [comment]
I don't have phosim installed though. This might mean you driving on your own machine, with me navigating :-)

**Comment by SimonKrughoff** [comment]
The script I pointed to is meant to be run from the command line as an example.  I think a great thing to do would be to extend that script to include an argument parser and such and submit a pull request back to catUtils.

**Comment by drphilmarshall** [comment]
OK, let's see what we need to change in it, tomorrow :-)

**Comment by SimonKrughoff** [comment]
O.K.  So, I followed the instructions above.  This is essentially:
```
$> mkdir stack
$> cd stack
$> curl -O https://sw.lsstcorp.org/eupspkg/newinstall.sh
$> chmod 700 newinstall.sh
$> ./newinstall.sh
#Answer yes to the two questions
$> source loadLSST.bash
$> eups distrib install lsst_sims -t sims
$> setup lsst_sims -t sims
$> mkdir ~/TwinklesData
$> cd ~/TwinklesData
$> python $SIMS_CATUTILS_DIR/examples/generatePhosimInput.py
#produces a file phosim can run
$> cd ~/repos
$> git clone https://stash.lsstcorp.org/scm/sim/sims_phosim.git
$> setup cfitsio
$> setup fftw
$> ./configure
#you'll have to point to the correct cfitsio and fftw3 libraries and headers
$> make
$> ./phosim ~/TwinklesData/phoSim_example.txt --sensor="R22_S11" -c examples/nobackground
#Images show up in the output directory
```

**Comment by drphilmarshall** [comment]
Excellent! We'll need to put the "first light" images on the web somewhere. And then display them in a notebook, perhaps?

**Comment by SimonKrughoff** [comment]
Here is the first one:
http://www.astro.washington.edu/users/krughoff/data/booring.fits

**Comment by drphilmarshall** [comment]
Alright! Here's the [notebook showing off @SimonKrughoff's first light images](http://nbviewer.ipython.org/github/DarkEnergyScienceCollaboration/Twinkles/blob/master/notebooks/First%20Light.ipynb). We can close this, I think - but the commands above need capturing into some sort of repeatable script...
