### ISSUE TITLE
_parent directory has incorrect link

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#194]
On the Nersc Computers: /global/homes/t/tony_j/Twinkles/985visits/985visits has a _parent directory which is probably the _mapper which is empty and probably has a link. Can we replace this file from the processing runs/ phosim output?

**Comment by jchiang87** [comment]
@rbiswas4 I made a symlink to the files in  `/global/homes/t/tony_j/Twinkles/985visits/985visits` here:

```
/global/u1/j/jchiang8/twinkles/985visits
```
and replaced the `_parent` symlink with one that points to directory with the `_mapper` and `registry.sqlite3` files.  I *think* that is all that is needed to start using those data with `Twinkles`, `Monitor`, etc..  If you need the eimages, etc. also, let me know I and I can copy them over.

Is there a sharable installation of the Stack and lsst_sims that I could use at NERSC?

**Comment by rbiswas4** [comment]
@jchiang87  Thank you. But I do not have permissions to access  this directory.

**Comment by jchiang87** [comment]
@rbiswas4 Can you try again?  I *think* I've set the permissions correctly.

**Comment by rbiswas4** [comment]
@jchiang87  Yes, I can get it now. Thanks! I will close this issue
