### ISSUE TITLE
Can we run a dbserve instance for Twinkles?

### ISSUE THREAD

**Issue by wmwv** [DarkEnergyScienceCollaboration/Twinkles#195]
@tony-johnson @jchiang87 @TomGlanzman  @drphilmarshall 

Can you talk with Jacek Becla and perhaps Fritz Mueller to learn what the current status of DBserve is and whether or not we could stand up a prototype to ingest Twinkles data products?

I have specifically in mind the single-frame and coadd-measurement catalogs.  The image and processing metadata would be a secondary, but less important goal.

**Comment by jchiang87** [comment]
Sure, I asked @brianv0 to set up a time next week when Tony and Jacek are back from travels.

**Comment by brianv0** [comment]
I'm actually the developer on dbserv and metaserv (aka the web interfaces to databases).

I can set up an instance of it most anywhere. We'd need to plug in some security because dbserv allows you to perform any SQL queries against it, but I can get it set up relatively quickly.

(Unless you're actually talking about qserv, in which case that's a different issue)

What is it specifically you'd like to do?

**Comment by drphilmarshall** [comment]
Or to put @brianv0 's question another way, how does this relate to #191, "Set up world accessible MySQL database at SLAC to serve up Twinkles Level 2 data"? I know there have been discussions about our setting up and using databases, but I don't see any comments on threads yet. @wmwv If you haven't seen @jchiang87 's initial SQL foray, it's in PR #184

**Comment by wmwv** [comment]
Yes, for the purposes of Twinkles, this is a duplicate of #195 (although "MySQL" and "SLAC" don't seem to be key parts).  Thanks @drphilmarshall for the pointer to this.  I searched for dbserve, qserv, but not database when looking for duplicates.

@brianv0  What @jchiang87 was doing in #184 is exactly what we would want to use dbserve to do.

Take a set of source measurements from the output of running single-frame or co-add forced photometry measurement and load them into a database that looks like how the LSST catalog database will look.

There's a larger goal of trying to get the actual LSST DB-related products in active use, which is why I'm specifically interested in doing things through dbserve instead of a separate custom database.

**Comment by tony-johnson** [comment]
We are working to get a QServ instance set up at SLAC (and accessible from anywhere). @brianv0  has arranged a meeting for today to discuss more details about how this will be set up and when it will be available.

**Comment by wmwv** [comment]
+1

**Comment by drphilmarshall** [comment]
I'm going to close this out, trusting that we are all agreed that a QServ instance would be great, and that working with PServ in the meantime is cool.

**Comment by tony-johnson** [comment]
Hi Phil, I think we should either reopen this to track the work we are doing on setting up QServ at SLAC, or open a new issue for that. Which do you prefer?

**Comment by drphilmarshall** [comment]
A new one, please. This one was a question which is now answered, and the
new one will likely be an epic, with a checklist in the first comment.
Thanks!

**Comment by tony-johnson** [comment]
Issue #257 created.
