### ISSUE TITLE
Twinkles 1 Analysis Retreat

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#198]
Organizing a beano is an epic task. We need to:

* [x] Agree on a location #181 
* [x] Agree on a date #179
* [x] Book a venue

**Comment by rbiswas4** [comment]
I am not sure which of the retreat threads to write this in, but as we discussed in the meeting, I am putting down my plans in Nov around the hack week time.
1. I plan to be at the hack week
2. I have a meeting in Pittsburgh on Nov 16-18 th (https://sites.google.com/site/lsstdescsn/ Supernova/LSST/DESC related, and maybe more Twinkles people will be interested in it too?)

**Comment by drphilmarshall** [comment]
Good, thanks Rahul! I see from my email that the DESC Hack Week is November 7-11 (Mon-Fri). That means that Monday+Tuesday 11/14 and 11/15 are open, between the hack week and the SNe meeting - so we could potentially work on Twinkles stuff then. Alternatively we could meet as a Task Force the week before the hack week, say Wed-Fri November 2-4 - but this would make it a very long trip for you. I *think* it makes more sense scientifically for the Twinkles SN/SL team to meet before the hack week to discuss our analysis plans, and then work on them with the DM and CI teams at the hack week. What do you all think? @jbkalmbach @danielsf @SimonKrughoff @jchiang87 @TomGlanzman @tony-johnson @sethdigel @richardxdubois @heather999 @wmwv

**Comment by jchiang87** [comment]
I'm on vacation from Nov 9-20, so I'd only be available to participate in the task force before Hack Week.  Since I won't be going to Pittsburgh, I'd be joining remotely.

**Comment by heather999** [comment]
Thanks for including me @drphilmarshall. My understanding is that there are no funds for me to attend.  I could join in remotely or possibly be persuaded to show up if I randomly found myself in Pittsburgh for a road trip :)

**Comment by wmwv** [comment]
I will be in Pittsburgh for both the DESC Hack Week and the Supernova Meeting and will fully participate in both.  I will be happy to host people who want to work on Twinkles (or really anything) at Pitt on the Mon+Tue in between.

**Comment by danielsf** [comment]
Is there a reason we are not talking about doing our Twinkles work on Saturday/Sunday November 12-13 so that people can get home sooner, should they so desire?

**Comment by drphilmarshall** [comment]
@danielsf Nope, that's on the table too - and a good idea although we may
not get everyone to burn a weekend with us. I imagine Michael will be
unavailable, but we out of towers could carry on hacking no problem.

I am hearing little appetite for going to Pittsburgh *before* the hack
week, though. That's no problem: we could aim to get out data in shape
during hack week, then work on analysis and writing the week after?

**Comment by rbiswas4** [comment]
> I am hearing little appetite for going to Pittsburgh *before* the hack
week, though.

If that is a comment about me, I am OK meeting up before the hack week, particularly if that is the only we can connect to some people. I am less optimistic about making Twinkles progress during the DESC hack week. My personal suggestion would be adding a remote/virtual Twinkles retreat week somewhere.

**Comment by drphilmarshall** [comment]
Yeah, Hack Week could be potentially be distracting. On the other hand, we on the SL/SN side of the project could commit to Twinkles hacks so that we make sure we make progress. And then we'll have the weekend and Mon/Tues as well, if you're up for it. I think I'm ready to commit to this, and am at least 80% in. @rmandelb is collecting statements of interest, so I just filled out her two-line form [here](http://goo.gl/forms/TeDtzv1iK4QnEY4q1) - it would be great if anyone else planning on joining would sign up too (and let us know on here if you're coming too :-) ) I said "Twinkles SL/SN light curve analysis" for my hack (on the understanding that this might involve some lower level enabling work in concert with the CI folks). You could make something like this up too! :-)

**Comment by drphilmarshall** [comment]
Hack week it is! Closing this out, will issue hack week stuff elsewhere.
