### ISSUE TITLE
Twinkle Sprinkler

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#20]
Write a small piece of python that reads in the output of CatSim, adds twinkles, and writes out PhoSim input files. For example, each galaxy could be given an AGN. Or a supernova. Rahul? Curtis?

**Comment by rbiswas4** [comment]
Curtis and I both wanted to try this with supernovae

**Comment by drphilmarshall** [comment]
Alright, we now have some [prototype sprinkler code](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/twinkles/sprinkler.py), that just puts in OM10 lensed quasars at present but can be refactored to be more general. Keep an eye on this repo's issues, @rbiswas4. Thanks, @cmccully and @jbkalmbach!
