### ISSUE TITLE
Overlay new coadds to check astrometry

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#202]
New coadds are at: bullet0002.slac.stanford.edu:/lustre/ki/pfs/fermi_scratch/Twinkles/2.

**Comment by drphilmarshall** [comment]
Hey @jbkalmbach  - anything to report on the registration problem from these new coadds?

**Comment by jbkalmbach** [comment]
No, sorry. But is this maybe duplicating in part @SimonKrughoff's work in #175 based upon what we heard today?

**Comment by drphilmarshall** [comment]
I think so - let's discreetly close this away :-)
