### ISSUE TITLE
Re-run DM workflow on Run 1 images

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#206]
But only when the prerequisites in #187 are done!

**Comment by drphilmarshall** [comment]
I think this is now done, right @tony-johnson ?

**Comment by SimonKrughoff** [comment]
We have re-run, but I don't think this is the last run for Run1.1.

**Comment by tony-johnson** [comment]
I think we can now declare this as closed. More details can be found in #163.
