### ISSUE TITLE
What happened to the script for generating phosim inputs?

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#215]
There used to be a script called generatePhosimInput.py, but I can't find it.  Was it renamed?

I need to make updates to it for the new reference catalog format.

**Comment by jchiang87** [comment]
https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/python/desc/twinkles/generatePhosimInput.py

**Comment by SimonKrughoff** [comment]
Thanks, just found it.  Sorry for the noise.  I don't know why a search for that exact name didn't turn anything up.  I guess github search does not search file names.
