### ISSUE TITLE
Database plan

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#216]
In response to the DB epic in #191: we need to start a simple markdown document, and use it to sketch as succinctly as possible our database needs for Run 1.1, Run 2 and Twinkles 2, so that we can communicate well with our colleagues at SLAC and NERSC (ie so we can send them a URL and ask for feedback). I'll make a stub and then pass it on!

**Comment by drphilmarshall** [comment]
Alright, check out our new [Database Plan](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Database.md), as committed at https://github.com/DarkEnergyScienceCollaboration/Twinkles/commit/daae4834415f87b1a78a3372320d92239f628261 . It has lots of "XXX"'s in it - want to have a go at filling in the blanks, @jchiang87 ? The main thing I am missing is the numbers of records - and maybe the rough size of the database in bytes would be good to have, too. I may have made some mistakes too, you'll want to fix those I expect :-) Thanks!

**Comment by jchiang87** [comment]
I've updated the [Database Plan](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Database.md) with some numbers.   In the db I have setup here at SLAC, the ForcedSource table dominates everything and has 40M rows corresponding to 4.7GB.  Note that the [ForcedSource schema](https://lsst-web.ncsa.illinois.edu/schema/index.php?sVer=baseline&t=ForcedSource) is pretty minimal.  If we expand it (#205) or implement the [DiaSource table](https://lsst-web.ncsa.illinois.edu/schema/index.php?sVer=baseline&t=DiaSource) that will increase the size estimate by as much as a factor of 10.  Here are the current stats:
```
mysql> show table status;
+--------------+--------+---------+------------+----------+----------------+-------------+-----------------+--------------+--------------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| Name         | Engine | Version | Row_format | Rows     | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free    | Auto_increment | Create_time         | Update_time | Check_time | Collation         | Checksum | Create_options | Comment |
+--------------+--------+---------+------------+----------+----------------+-------------+-----------------+--------------+--------------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| CcdVisit     | InnoDB |      10 | Compact    |     1042 |             78 |       81920 |               0 |            0 | 194566422528 |           NULL | 2016-03-17 14:05:02 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| Chisq        | InnoDB |      10 | Compact    |    57906 |             45 |     2637824 |               0 |            0 | 194566422528 |           NULL | 2016-03-20 13:58:32 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| ForcedSource | InnoDB |      10 | Compact    | 36860118 |            127 |  4702863360 |               0 |            0 | 194566422528 |           NULL | 2016-03-17 12:38:17 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| Object       | InnoDB |      10 | Compact    |    60831 |             60 |     3686400 |               0 |            0 | 194566422528 |           NULL | 2016-03-21 10:21:08 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
+--------------+--------+---------+------------+----------+----------------+-------------+-----------------+--------------+--------------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
4 rows in set (0.01 sec)
```

**Comment by drphilmarshall** [comment]
Cool, thanks @jchiang87 . We decided to try and include image differencing from Run 2 onwards ( #197 ), so I think we will indeed need that extra order of magnitude... Let's cite some issues in the plan to help us navigate all this - I'll add a few, if you see any gaps maybe do likewise? Thanks!

**Comment by drphilmarshall** [comment]
OK - 100M in Run 2 became 1B, and then 3B in Twinkles 1 became 30B. (although I think I am using both 'B' and 'G' to denote billion...) Is it really a factor of 10 to include the DIASources? If we switch to image differencing I guess we can stop tracking the ForcedSources as well, at least in Run 3 (we'll want both in Run 2 for testing, I expect).

**Comment by jchiang87** [comment]
The DIASources table looks like it has about 70 columns vs 5 for ForcedSources.  Given that the indexing contributes negligibly for these tables (which runs contrary to what I've been told previously), the db size will scale with the "average_row_length", which is just the number of columns times the average entry size in bytes.  (BTW, "B" for bytes probably precludes using it for billion).

**Comment by drphilmarshall** [comment]
Good, thanks! Edited page, [see what you think.](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Database.md)

**Comment by jchiang87** [comment]
I think we do have a realizable plan, certainly through Run 2, and are moving forward on a path to implement something for Twinkles 1.   Closing.
