### ISSUE TITLE
Start Level 2 database emulation project in spin-off repo

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#218]
The idea is to emulate the Level 2 database that the DM stack will make, as simply and cheaply as possible, just so we can start analyzing the Twinkles 1 Run 1/2/3 data. We'll need a suitably-named DESC repo made with the cookie-cutter, a README that explains what we are trying to do (and what we are not trying to do) and then the code that @jchiang87 and @rbiswas4 have been playing with. Oh, and this project needs a good name, that evokes the temporary nature of this tool (since we hope to retire it soon, when we move to using the DM ingestion scripts). 

It's name need not be Twinkles-related, but I think it should be whimsical and non-threatening - this really is a quick, interim fix. How about "tempDB"? or maybe "Tserv"? (where 'T' is for either "Twinkles" or "temporary"...) Assigning to @jchiang87 who volunteered to set this up - thanks Jim!

**Comment by jchiang87** [comment]
I sort of like "Tserv", though maybe "Kserv" where we explain that 'K' stands for kludge would be more descriptive.

**Comment by drphilmarshall** [comment]
K is also for "Krughoff". Hah! Also Kindergarten.

There's also Pserv, which comes before Qserv (and evokes politeness). P is
for Phil, Pragmatism, Pinch, Preliminary.

Or Iserv, because there's no queue, just one machine providing data access
- and we're writing it ourselves, and it's an Interim solution. This one's
a bit corporate though.

Uchoose!

**Comment by jchiang87** [comment]
oooh. Pserv is good.  I'll go with that, unless someone objects.

**Comment by drphilmarshall** [comment]
Also "pea-brained"

**Comment by jchiang87** [comment]
The new package is at 

https://github.com/DarkEnergyScienceCollaboration/pserv

I've used this to install a db instance at NERSC and loaded it with the original Run1 985visit data:
```
mysql> show tables;
+---------------------------------+
| Tables_in_DESC_Twinkles_Level_2 |
+---------------------------------+
| CcdVisit                        |
| ForcedSource                    |
| Object                          |
+---------------------------------+
3 rows in set (0.02 sec)

mysql> select count(1) from CcdVisit;
+----------+
| count(1) |
+----------+
|      985 |
+----------+
1 row in set (0.01 sec)

mysql> select count(1) from Object;
+----------+
| count(1) |
+----------+
|    60554 |
+----------+
1 row in set (1.29 sec)

mysql> select count(1)/1e6 from ForcedSource;
+--------------+
| count(1)/1e6 |
+--------------+
|    46.026073 |
+--------------+
1 row in set (49.31 sec)

```
Once the new Run1 data are available, we can reload the data.  BTW, I've sped up the forced source table ingest.  It took about 82 minutes to load all 985 visits at NERSC.

**Comment by tonyj321** [comment]
Is this database publicly accessible? If so are there instructions for doing so?

**Comment by jchiang87** [comment]
We have a read-only account available.  I can send the userid/password on request.   I haven't written any instructions yet.
