### ISSUE TITLE
Transfer Run 1.1 outputs to NERSC when they are made

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#220]
So that everyone can work on them. We did this for Run 1, right @tony-johnson? Great if we can open up the pipe and flush everything down it again.

**Comment by drphilmarshall** [comment]
Hi Tony! Is it easy to transfer the Run 1.1 images and catalogs to NERSC, like you did last time? Thanks!

**Comment by tony-johnson** [comment]
This is now done, the output is here:

/global/homes/t/tony_j/Twinkles/Run1.1/

**Comment by jchiang87** [comment]
The Run1.1 data have been ingested into the MySQL tables at NERSC.  Here are the stats:
```
mysql> select count(1) from ForcedSource;
+----------+
| count(1) |
+----------+
| 33799285 |
+----------+
1 row in set (29.61 sec)

mysql> select count(1) from CcdVisit;
+----------+
| count(1) |
+----------+
|     1120 |
+----------+
1 row in set (0.01 sec)

mysql> select count(1) from Object;
+----------+
| count(1) |
+----------+
|    41653 |
+----------+
1 row in set (0.11 sec)

mysql> 
```
I've only had a cursory look so far, but things seem ok.   I'll try to do more tests before this afternoon's meeting.

Let me know if you want the connection info, and I'll email you the details.

**Comment by SimonKrughoff** [comment]
I'd love the connection details.

**Comment by jchiang87** [comment]
btw, the `obsStart` column in `CcdVisits` is filled with incorrect values....investigating.

**Comment by SimonKrughoff** [comment]
@jchiang87 Thanks for the connection details, but I think I also need the endpoint to where the database is (is it accessible from outside NERSC?).

**Comment by jchiang87** [comment]
Right, sorry.  The host is `scidb1.nersc.gov`.   From outside of NERSC, Bryce notes that he needed to ssh tunnel to connect.

**Comment by jchiang87** [comment]
`obsStart` should be fixed now.

**Comment by jchiang87** [comment]
@jbkalmbach @rbiswas4 FYI:  I've reloaded the ForcedSource table with fluxes converted to nanomaggies.
