### ISSUE TITLE
Compile a list of lessons learned

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#224]
We are learning things as we go along and I'd like to see if we can capture that.  My current thinking is just to keep a running list of things [here](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/lessons_learned.md).

**Comment by drphilmarshall** [comment]
Good idea! Something about the need for provenance, based on recent issues - @tony-johnson you had an idea for helping with that, you were going to issue it?

Also this relates to [this Computing Infrastructure issue](https://github.com/DarkEnergyScienceCollaboration/ComputingInfrastructure/issues/18) - so if we can get some ideas about the pathfinder side of things going here, maybe we can prepare to report to the CI group?

**Comment by tony-johnson** [comment]
I have created #228 which I think is somewhat related to this issue.

**Comment by drphilmarshall** [comment]
Cool. Passing to @SimonKrughoff to get the ball rolling. Post a lesson learned, and pass the assignment on!

**Comment by SimonKrughoff** [comment]
Tag @rbiswas4. We are passing the ball around adding some lessons learned.  When you have added one to the page linked in the initial message in this issue, re-assign to someone else.

**Comment by drphilmarshall** [comment]
I just added a few lessons learned to our ["Lessons Learned"](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/lessons_learned.md) page. Please start each one with a single sentence summary in bold, to aid readability! I also split the document into Runs 1 and 1.1, and Run 2, also to keep it readable. Let's all please contribute to this document today, so we can make sure to have good coverage in our talks. [Click on this link](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/lessons_learned.md) and edit in your thoughts! Thanks, everyone.

cc. @DarkEnergyScienceCollaboration/twinkles

**Comment by rbiswas4** [comment]
I put in a few. Will add more if I can think of them.

**Comment by drphilmarshall** [comment]
Thanks Rahul! @tony-johnson I put one in with your name on it! You'd better
check that I have it right. And then maybe add some more :-)

**Comment by drphilmarshall** [comment]
Thanks for all your contributions to the ["Lessons Learned"](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/lessons_learned.md) list - hopefully this'll be useful in formulating conclusions to our LSST DESC Notes series #284. We'll want to check back to this list when we are finishing those off, to make sure we don't miss anything. In the end, though, the record will be in the Notes, and this temporary list will be able to be retired.
