### ISSUE TITLE
Switch to lower case naming

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#231]
@cwwalter recommended we not capitalize "Twinkles" so as to avoid the problems the `GalSim` team had working on both linux and Mac OS X. I'm not sure where this needs to be done, possibly everywhere?

**Comment by cwwalter** [comment]
Here is a little background info on what I was saying based on our GalSim experience.

Basic background: OSX doesn’t really distinguish between case. For example, Look in your home directory and then type something like:

ls Music
ls MUSIC
ls music

you will see the same thing in all three cases.

But, the way eups is written it actually pays attention.  So if you actually do it properly by typing 

setup Twinkles

it will work OK.

But if you type

setup twinkles 

by mistake, it will start to work but then nothing in eups will work properly and you wind up in a very bad state that is really messed up.  You have to close what you are doing and start all over again.  So, this is really a eups issue, but all other LSST stack packages are lower case so we were making this mistake a lot.

For that reason I suggest making the eups package names lowercase.

**Comment by jchiang87** [comment]
It applies just to filenames I think, since filenames on OSX aren't case-sensitive.  We can still use mixed case internally in code, e.g., for module or class names within a file.

**Comment by jchiang87** [comment]
btw, eups determines the package name from the filenames in the ups folder.

**Comment by cwwalter** [comment]
Right I am only referring to the eups package name.  Nothing else.
