### ISSUE TITLE
Additional code checking in .travis.yml: pylint and coverage

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#233]
In addition to unit tests and python 3 compatibility checks (see #211), we should add standard pylint (2.7) checking.   We'll probably want to have a `pylintrc` file to customize which checks are applied.

It was also suggested that [coveralls](https://coveralls.zendesk.com/hc/en-us) could be used to track coverage via travis.

**Comment by jchiang87** [comment]
I added coverage tests and `coveralls` integration via 2631fede.  See https://coveralls.io/github/DarkEnergyScienceCollaboration/Twinkles for the coverage stats.

**Comment by drphilmarshall** [comment]
Cool - I didn't know the term ["coverage"](https://coveralls.io/) before. But now our README tells everyone that 40% of our code is covered by our test suite! :-)  

What do you suggest we do about a `pylintrc` file? I guess we'll want the same one in other DESC projects, no?

**Comment by jchiang87** [comment]
It's that final 60% to get it over the finish line that's the hard part!

One can generate a `pylintrc` file with the default configs and then tweak things from there.   I'll put one in the [desc_package_template](https://github.com/DarkEnergyScienceCollaboration/desc_package_template) repo (and here) which we can leave up to the individual groups to tweak.

**Comment by drphilmarshall** [comment]
Sounds good. Because its in the package template, does that mean that each
package should have one? How might the Twinkles `pylintrc` be different
from the 2pt_validation one, for example?

**Comment by jchiang87** [comment]
Each package created with the template would get one and we could configure the generatated `.travis.yml` to use it as part of the default build, but since we're not requiring any particular set of coding conventions, it would be up to the package owners/developers whether they wanted to continue using it or modify it to suit their group's needs.

**Comment by drphilmarshall** [comment]
Got it! So we could start tweaking the Twinkles one, and maybe push the
changes back to the package template after a while, if we make some good
general choices? I can see how a sensible collaboration-wide default could
evolve like that. That makes me think: I wonder what the GalSim `pylintrc`
looks like? We should ask @rmjarvis, and see if we can adopt come existing
conventions (lots of GalSim developers are DESC members). Mike?

**Comment by jchiang87** [comment]
Added `.pylintrc` at [`desc_package_template`](https://github.com/DarkEnergyScienceCollaboration/desc_package_template/commit/5cff11a5a88521552b68670b47c8318c160befe7).

**Comment by heather999** [comment]
Pretty sure we can close this, @jchiang87 has kindly set up pylint and coverage in our travis-ci builds.
