### ISSUE TITLE
new lsst_apps sims compatible conda install on dev channel

### ISSUE THREAD

**Issue by heather999** [DarkEnergyScienceCollaboration/Twinkles#235]
@danielsf We had a meeting about setting up NERSC for another round of runs.  The need of an updated version of the stack came up. We were wondering if it would be possible to make another conda installation of lsst_apps available on the dev channel. #163 mentions b2016 as our target. I am making a fresh attempt to build from source, but a conda installation is clearly preferable, if it is possible.
Here's a link to the meeting notes:
https://docs.google.com/document/d/1NnsW3XZTQcJNqVi-3RZQivCqSMlY753S2MZk9dsbMNg/edit?usp=sharing

**Comment by cwwalter** [comment]
Hi Heather, that URL has a problem for me.  I fixed the "a" in google but it still says page not found.

**Comment by heather999** [comment]
Thanks, @cwwalter - better now?  I hope!

**Comment by cwwalter** [comment]
Yes thanks!

**Comment by cwwalter** [comment]
One comment: On Cori if you are running a single CPU job you want to run in the "shared queue".  That queue has a 48 hour limit.

There were recently some increased time options but I think they were only in the regular queue and are limited.  @djbard can comment more about this and if special run conditions are possible.

**Comment by danielsf** [comment]
@heather999 Which weekly do you need the conda install built against?

**Comment by heather999** [comment]
I want to say b2016 @danielsf, but I would owe @jchiang87 a beverage if he can confirm that.

**Comment by jchiang87** [comment]
@danielsf I'm not sure there is a weekly build that has what we want.   @SimonKrughoff would know what weekly would be needed, if such a thing exists.

**Comment by danielsf** [comment]
I agree.  It does not look like the weeklies have been updated since the last version was built.  Let me talk to some folk about how to handle this (usually our policy has been to build against weeklies on the assumption that they are more stable than the average build; I'm not sure if there is a compelling reason for this policy or not).

**Comment by heather999** [comment]
@SimonKrughoff @danielsf In the interest of allowing this NERSC test to proceed - I'm wondering (and perhaps this was your initial suggestion at the Twinkles meeting, I assumed you were intending we just take the binaries) if we can just copy the source that exists in /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw to NERSC and rebuild it?
So some questions.. is that the right directory location at SLAC for the code used in the Twinkles run?
Is this a feasible idea?  I'm used to doing builds where we're downloading the code and then building.. is there some way to use lsstsw to handle a rebuild?  I haven't played with lsstsw, but I really should learn how to use it. I'll start with the doc, but guidance would be very appreciated.

**Comment by heather999** [comment]
@tony-johnson can you confirm that /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw is the copy of the code used in the Twinkles run at SLAC?

**Comment by tony-johnson** [comment]
Yep, that is the code that we used.

**Comment by SimonKrughoff** [comment]
@heather999 I was hoping that we could literally copy the binaries over to NERSC and just use them (that's basically what a conda install does anyway).  I know the anaconda distribution is not relocatable, but maybe we can just patch a new one on top.

**Comment by heather999** [comment]
@SimonKrughoff My concern is that rather than using the more generic Cent OS5 used for the conda install ( I think that's still the case ).. we'd be going from RH6-64 and build that wasn't intended to be ported anywhere else, but maybe I'm being pessimistic. I'm open to zipping this up and copying it over to try it.
It wouldn't hurt to try to do an actual build from source at NERSC - just to see how that goes. Building might necessary in the future.

**Comment by heather999** [comment]
@SimonKrughoff There are 2 bits:
/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/build/boost/libs: Cannot open: Permission denied
and
cannot open `/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack/ups_db/Linux64.pickleDB1_3_0' for reading: Permission denied
I also receive complaints about afw's .git directory, but I think that's safely ignored. Is it possible modify the permissions?

**Comment by SimonKrughoff** [comment]
O.K.  I'll have a look.

Simon

**Comment by heather999** [comment]
In the good news department, I see how to update the python install very easily by introducing a fresh miniconda install and then doing:
conda install --file etc/conda_packages-linux-64.txt
but I'm stuck otherwise

**Comment by danielsf** [comment]
@heather999 Are you still trying to figure out how to port over Jim's b2016, or are you just trying to update the conda release of the stack in general?

**Comment by heather999** [comment]
@danielsf We're still hoping to port over b2016 to NERSC.  The hope is to demonstrate that they can reproduce the results obtained from the runs at SLAC, and for that we seem to need a duplicate of this particular snapshot of the code.

**Comment by SimonKrughoff** [comment]
@heather999 I'm tarring up a version of that stack.  I hope that will get around the perms problem.  That seems easier than trying to modify each of the funny places by hand.  Sorry to have forgotten about this until today.

**Comment by SimonKrughoff** [comment]
@heather999 Here is the tarball.  Let me know if you make any headway.  /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw-b2016.tar.gz

I chatted with TimJ a little about how to do this in a general way and it's a bit tricky.  Probably what we should to is to build against a tagged weekly and then install deltas on top of that.  Unfortunately, we can't do that with this stack because it was a master build (not tagged).  I'll try to be more careful in the future.

**Comment by heather999** [comment]
Thanks, @SimonKrughoff!  Here's what I did so far:

- Copied over the tarball and unpacked on Cori into:
/project/projectdirs/lsst/lsstDM/Cori/b2016/lsstsw
- Removed the miniconda subdirectry
- Installed a fresh miniconda 
- sourced bin/setup.sh
- installed the stack-specific python modules via:  conda install --file etc/conda_pacakges-linux64.txt

Now to test this out.. do you, @jchiang87 or @tony-johnson have a simple suggestion?  For the moment, I haven't made any modification to the NERSC environment itself such as 
module swap PrgEnv-intel PrgEnv-gnu
module swap gcc gcc/4.9.3
module rm craype-network-aries
module rm cray-libsci/13.3.0
module unload craype
it may not be necessary.. though I'm not sure yet :)

**Comment by jchiang87** [comment]
How did you get the bin/setup.sh script not fall down?  This is what I see:
```
[cori06] source /project/projectdirs/lsst/lsstDM/Cori/b2016/lsstsw/bin/setup.sh 
-bash: /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python: No such file or directory
-bash: /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/eups/2.0.1/bin/eups_setup: No such file or directory
If 'setup' is not a typo you can run the following command to lookup the package that contains the binary:
    command-not-found setup
-bash: setup: command not found
notice: lsstsw tools have been set up.
[cori06] 
```
It looks like some site-specific configuration needs to be done to make this usable, although I have no idea what  incantations are needed.

**Comment by SimonKrughoff** [comment]
@heather999 if you are brave, you can try running one of the CI packages: https://github.com/lsst/lsst_dm_stack_demo.

To do this, clone that repo and source the `bin/setup.sh` script.  Then:
```
$> cd lsst_dm_stack_demo
$> setup -t b2016 obs_sdss
$> ./bin/demo.sh
```
There is also a script to compare the results to a known good set of results if that happens to work.

**Comment by SimonKrughoff** [comment]
@jchiang87 I'll have a look.  I think it shouldn't be much.

**Comment by SimonKrughoff** [comment]
It looks like eups hardcodes some paths.  I don't know if this means eups needs to be rebuilt or if it just means the paths need to be changed in the bin scripts.
```
eups/2.0.1/bin/setups.csh:   setenv EUPS_DIR "/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/eups/2.0.1"
eups/2.0.1/bin/setups.csh:if not "/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack" in pp:
eups/2.0.1/bin/setups.csh:    pp = ["/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack"] + pp
eups/2.0.1/bin/setups.sh:export EUPS_DIR=${EUPS_DIR:-/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/eups/2.0.1}
eups/2.0.1/bin/setups.sh:export EUPS_PATH=`/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python -E -S -c '
eups/2.0.1/bin/setups.sh:print(":".join(pp))' "$EUPS_PATH" "/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack"`
eups/2.0.1/bin/setups.zsh:export EUPS_DIR=${EUPS_DIR:-/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/eups/2.0.1}
eups/2.0.1/bin/setups.zsh:export EUPS_PATH=`/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python -E -S -c '
eups/2.0.1/bin/setups.zsh:print(":".join(pp))' "$EUPS_PATH" "/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack"`
eups/2.0.1/bin/eups:/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python -S "$EUPS_DIR/bin/eups_impl.py" "$@"
eups/2.0.1/bin/eups_impl.py:#!/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python
eups/2.0.1/bin/eups_setup:/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python -S "$EUPS_DIR/bin/eups_setup_impl.py" "$@"
eups/2.0.1/bin/eups_setup_impl.py:#!/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python
eups/2.0.1/ups/eups.table:envAppend(EUPS_PATH, /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack)
eups/2.0.1/doc/eups.html:The <A HREF=/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/eups/2.0.1/doc/eups.pdf>pdf documentation</A> was built successfully.
eups/2.0.1/Makefile:prefix = /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/eups/2.0.1
eups/2.0.1/Makefile:EUPS_PATH = /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack
eups/2.0.1/Makefile:EUPS_DIR = /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/eups/2.0.1
eups/2.0.1/Makefile:EUPS_PYTHON = /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python
eups/2.0.1/Makefile:	@echo "Eups will use                               /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/miniconda/bin/python"

**Comment by heather999** [comment]
I started updating a few of the setup scripts.. I'm not sure yet how deep I have to go.. so far the path is hard-coded in:
eups/current/bin/setups.sh
and
eups/2.0.1/bin/eups_setup
but updating those hasn't totally fixed the problem yet.. I'm still receiving an error:
/nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw/stack in $EUPS_PATH does not contain a ups_db directory, and is being ignored

Is there a simple way to rebuild just eups?  Otherwise I'll dig around for instances of "kipac" and see what that reveals.

**Comment by heather999** [comment]
@jchiang87 Just so you know that I didn't abandon this yet!
https://community.lsst.org/t/using-lsstsw-to-rebuild-relocated-dmstack/767/13
Getting there.. I remain hopeful :)

**Comment by heather999** [comment]
@SimonKrughoff @danielsf @tony-johnson @jchiang87   If we have a Twinkles meeting.. I'm hoping we can discuss "What Now?" concerning a NERSC installation of DMstack and the plan to try to reproduce the Run 1.1 results from SLAC.

**Comment by heather999** [comment]
closing this issue as we've moved on..
