### ISSUE TITLE
New TDC Lens catalog missing TwinklesId numbers

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#236]
So, I guess we haven't been creating new Instance Catalogs because otherwise I think somebody would have mentioned this. I was trying to make a new instance catalog to get a list of sources to overlay on our new coadds and discovered I couldn't because there was no 'twinklesID' column in the new file 'data/twinkles_tdc_rung4.fits'). So, I fixed that and now since there are 872 possible lenses we need to expand the possible values we adjust galtileid by since 872*4 > 1000 and we would still like unique numbers to identify each catalog entry.

**Comment by drphilmarshall** [comment]
Seems like a straightforward change, Bryce - is it?

**Comment by jbkalmbach** [comment]
Yes, this has been done and now merged in #237

**Comment by drphilmarshall** [comment]
Great!
