### ISSUE TITLE
Overlay new coadds with sprinkled positions

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#238]
So, I compiled a list of sprinkled objects and then converted their ra,dec to pixel locations using the coadd wcs and astropy.wcs. 

First, I looked at the locations of all the sprinkled objects. Obviously, they cover a larger range than just the chip we are looking at.
![full_layout](https://cloud.githubusercontent.com/assets/4755090/15127435/8c77796c-15eb-11e6-89f8-ee1a2dbca541.png)

Then I looked just at the chip area.
![zoom_clean](https://cloud.githubusercontent.com/assets/4755090/15127436/8c7b3066-15eb-11e6-8984-4f1409291ae3.png)
![zoom_layout](https://cloud.githubusercontent.com/assets/4755090/15127438/8c7b30d4-15eb-11e6-8a80-a146f8aef764.png)

Then I picked up a few targets and zoomed in on them. It seems like they are all off just a little bit. My theories are that this is either due to something in the astropy wcs methods that may be different from the lsst dm methods or it's because the phosim catalogs are unrefracted coordinates and maybe this provides some sort of offset because it's not accounted for in the coadds? The green targets are the lens galaxies.
![zoom_targets_clean](https://cloud.githubusercontent.com/assets/4755090/15127439/8c7c9212-15eb-11e6-8eda-8f8c2922ef8d.png)
![zoom_targets](https://cloud.githubusercontent.com/assets/4755090/15127437/8c7b28e6-15eb-11e6-8244-c9abaf20b12e.png)

**Comment by jbkalmbach** [comment]
Here I've attached the location information on the sprinkled objects and the lens galaxies.

[sprinkled_agn_pixel_locs.txt](https://github.com/DarkEnergyScienceCollaboration/Twinkles/files/255876/sprinkled_agn_pixel_locs.txt)
[sprinkled_lens_galaxy_pixel_locs.txt](https://github.com/DarkEnergyScienceCollaboration/Twinkles/files/255877/sprinkled_lens_galaxy_pixel_locs.txt)

**Comment by SimonKrughoff** [comment]
Can I also get the ra, dec locations?

**Comment by jbkalmbach** [comment]
Those files above should have ra,dec as well as the pixel coordinates I derived.

**Comment by SimonKrughoff** [comment]
Following Bryce's lead, I plotted some positions of the SNe on the r-band coadd.
![image](https://cloud.githubusercontent.com/assets/945715/15132002/e1159454-1609-11e6-9178-76342f43d26e.png)
Blue circles are supernova positions.

And the coadd color composite for that galaxy:
![image](https://cloud.githubusercontent.com/assets/945715/15131988/b6a0d8fa-1609-11e6-8f7a-b1a1beb9fb6d.png)

That's a lot of supernovae!  I'm a little surprised they didn't clip out when we sigma clipped the coadds, so we should definitely think about this more before we do Run 2.

**Comment by drphilmarshall** [comment]
Who put all those supernovae there?! Biswas! ;-)

It looks as though the lensed quasar images are in the correct positions
relative to the lens galaxies, it's just the absolute positions are off -
and, it seems, somewhat systematically. Is this the case? Is the vector
offset between the ref catalog objects and the CoaddSources constant over
the field? The patterns in this vector field might tell us whether its WCS
or refraction.

The CatSim stars are being used to register the images onto a global WCS,
so you'd think that everything else in the input catalog would end up in
the right places relative to those stars. Have you tried overlaying the
positions of small samples of a) CatSim reference stars (the bright ones
used in the astrometry), b) faint CatSim stars, and c) CatSim galaxies? If
they show different offsets that could also be a clue.

**Comment by jbkalmbach** [comment]
Simon, how did you get the coordinates for the supernovae? Because your circles seem to line up perfectly with the objects. Do they come from a phosim catalog or a different one?

**Comment by SimonKrughoff** [comment]
Those are the J2000 coordinates from the catsim catalog.  I think that's the right thing to do.  The phosim catalogs will include some differential effects that may offset them: e.g. refraction, aberration, etc.  If you have J2000 coordinates, I'd use those.

**Comment by jbkalmbach** [comment]
Sorry, I should have been clearer. By catsim catalog do you mean the Instance catalogs used as input? Those are what I was using, not any sort of catalog that came out of phosim.

**Comment by SimonKrughoff** [comment]
The important thing is the coordinate system.  The instance catalogs used as inputs (what I called phosim catalogs before) are not in J2000.  They are in some intermediate system that includes several physical effects.  If you are using instance catalog positions, that may account for the offset.

**Comment by danielsf** [comment]
@jbkalmbach You will want to create a new InstanceCatalog that contains the same objects as your PhoSim input catalogs, but uses the columns 'raICRS', 'decICRS' in place of 'raPhoSim', 'decPhoSim'

**Comment by jbkalmbach** [comment]
Ah, okay, I understand. Thanks @SimonKrughoff and @danielsf, I will make a new catalog with those coordinates and update.

**Comment by jbkalmbach** [comment]
Ok, I redid them with J2000 coordinates and it seems now they lie in the correct area, but looking closely at the second set it still seems just a bit off, but maybe those are phosim effects, I'm not sure.

![zoom_targets_clean](https://cloud.githubusercontent.com/assets/4755090/15190861/f40e3742-1766-11e6-8bfa-83fd6eadf988.png)
![zoom_targets_icrs](https://cloud.githubusercontent.com/assets/4755090/15190825/cccfb44e-1766-11e6-930b-622d3069b210.png)
![zoom_targets_icrs_clean_2](https://cloud.githubusercontent.com/assets/4755090/15190832/d3b97a4c-1766-11e6-9a9f-f41c538b04d2.png)
![zoom_targets_icrs_2](https://cloud.githubusercontent.com/assets/4755090/15190840/d7c67d42-1766-11e6-997a-e2d48f557176.png)

**Comment by SimonKrughoff** [comment]
@jbkalmbach have you been able to find any systems where the images are separated from the lens by enough that you can distinguish them by eye?

**Comment by jbkalmbach** [comment]
I'll try to find some.

**Comment by jbkalmbach** [comment]
Here, I found these. The first set are pretty faint, but you can see them, the second aren't as spread out but I think you can tell by eye without knowing that those are two point sources. I also fixed the problem that was causing the slight offsets before and it looks like I'm getting pretty good matchups on location now.
![zoom_targets_spread](https://cloud.githubusercontent.com/assets/4755090/15196736/b3b38b0e-1782-11e6-9fd5-bd878d65a355.png)
![zoom_targets_spread_clean](https://cloud.githubusercontent.com/assets/4755090/15196890/6a325090-1783-11e6-9b43-1d579f6af11f.png)
![zoom_targets_spread_2](https://cloud.githubusercontent.com/assets/4755090/15197929/1fe1f01c-1789-11e6-840f-c79cc0999fac.png)
![zoom_targets_spread_2_clean](https://cloud.githubusercontent.com/assets/4755090/15197932/24a98010-1789-11e6-93fe-0661c8ef6fbc.png)

**Comment by drphilmarshall** [comment]
These matches look close enough for believable light curve comparisons, I'd say! Are you happy to close out, @jbkalmbach ?

**Comment by jbkalmbach** [comment]
Yes, I'm happy to say we now have a way to line up sprinkled objects onto the coadds.

**Comment by drphilmarshall** [comment]
Excellent! This would be a good thing to show off in a demo notebook - can
we show the Monitor pulling out a point source and visualizing a postage
stamp around it? I know you've made such plots for the issue comments, but
it'd be good to show the code in action.
