### ISSUE TITLE
Install w.2016.20 weekly at SLAC

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#239]
I will install the latest weekly at SLAC and then ping @tony-johnson here with the build number so he can kick off a new run.

**Comment by tony-johnson** [comment]
Hi Simon, it might be useful if you could capture what commands you needed to execute to do the build, to make it easier for @heather999 to reproduce it at NERSC (plus I would be interested to know how to do this in future)

**Comment by jchiang87** [comment]
It would be helpful to provide the correct procedure to install a version of sims that can be run using that installation of the Stack.   The sims code is needed by Twinkles to run the catsim-related code as well as by the Monitor package to produce light curves.

**Comment by SimonKrughoff** [comment]
@danielsf Does sims tag with the same weekly tags as the core DM stack?

**Comment by danielsf** [comment]
Whenever we release a new lsst_sims, we build it against the latest DM weekly.  It has been a while since there has been a new sims release.  I think we are on w.2016.15

If we need to release a new sims version in concert with what you are building, that is fine.  Just let me know.

**Comment by SimonKrughoff** [comment]
Assuming you have an lsstsw distribution someplace, to install the weekly and lsst_sims on top of that do:

```
$> scl enable devtoolset-3 bash
$> cd /nfs/slac/kipac/fs1/g/desc/DMStack/lsstsw
# make sure your lsstsw and lsst_build are up to date
$> git pull
$> cd lsst_build
$> git pull
$> cd ..
$> source bin/setup.sh
# build the versions of all packages tagged with the last weekly
$> rebuild -r w.2016.20 lsst_apps
# Now build sims on top of that.
$> rebuild -r w.2016.20 lsst_sims
```

**Comment by SimonKrughoff** [comment]
I'll note you can do the last two steps in either order.

**Comment by heather999** [comment]
ok I'll give that a try, thanks @SimonKrughoff

**Comment by SimonKrughoff** [comment]
I'm closing this.  @heather999 if you have problems at NERSC, feel free to open another issue.

**Comment by tony-johnson** [comment]
Hi Simon, to use this at SLAC what tag do I need to use?

setup lsst_apps -t w.b2016.20

does not seem to work

**Comment by SimonKrughoff** [comment]
Sorry @tony-johnson! That was the deliverable for this.  For the DM stack use b2017.  @jchiang87 for the sims use b2018.

**Comment by heather999** [comment]
I have the install going now at NERSC.. holding my breath :)
Just in the interest of general knowledge @SimonKrughoff .. b2017 and b2018 are the versions of lsst_apps and lsst_sims that correspond to the w.2016.20 build?
