### ISSUE TITLE
Fix RA/Dec Issue in Sprinkler

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#24]
W/ @cmccully. Before we can merge Issue #21 we need to resolve the problem of our sprinkled objects having erroneous ra, dec values.

**Comment by SimonKrughoff** [comment]
@jbkalmbach where is the code?  I can have a look if you point me to it.

**Comment by cmccully** [comment]
The code is mostly in https://github.com/cmccully/Twinkles. The code appears to be producing the correct RA and Dec values in radians, but an parent class appears to be adding an extra transformation for the RA and Dec, attempting to transform them to another units (I think degrees but haven't confirmed that).

**Comment by jbkalmbach** [comment]
After merging of https://github.com/cmccully/Twinkles/pull/3 I going to go ahead and close this issue.
