### ISSUE TITLE
Understand why ingest runs spectacularly much slower in batch than interactive

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#258]
Observed at both SLAC and NERSC.

**Comment by tony-johnson** [comment]
At NERSC running interactively:

	User time (seconds): 3.81
	System time (seconds): 7.12
	Percent of CPU this job got: 105%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.33

At NERSC running in batch:

        User time (seconds): 15.56
        System time (seconds): 97.36
        Percent of CPU this job got: 14%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 12:47.81

10 seconds -> 13 minutes!

**Comment by tony-johnson** [comment]
Details for above

[logFile.txt](https://github.com/DarkEnergyScienceCollaboration/Twinkles/files/307518/logFile.txt)

[interactive.txt](https://github.com/DarkEnergyScienceCollaboration/Twinkles/files/307530/interactive.txt)

**Comment by SimonKrughoff** [comment]
That is pretty crazy.  I don't see how it can possible take 13min to make ~12 symbolic links.  We could instrument ingest.py to give slightly finer grained timing.

**Comment by SimonKrughoff** [comment]
Wait a sec.  The non-interactive version seems to be ingesting lots of visits whereas the interactive version is only ingesting one visit.  If you are doing 1000 visits in parallel to the same filesystem I can see it taking this long.

**Comment by tony-johnson** [comment]
The logfile does 10 visits, but each visit is timed individually, and the times above are for a single visit (visit 200 the same as the interactive).

**Comment by SimonKrughoff** [comment]
O.K. then I'm baffled.

**Comment by tony-johnson** [comment]
At SLAC, rerunning with strace turned on appeared to magically make the batch jobs run faster. I suspect that this was not the real cause, and that the very slow earlier run was perhaps related to load on the particular batch machine used.

At NERSC switching to having the software installed on /global/common/cori/contrib/lsst (see issue #268) appears to have made a dramatic difference, and the batch performance there now seems reasonable.

I am closing this issue, although for run 1/2 the ingest still takes about 5 hours (15seconds * 1120 runs) which I suspect is dominated by python/DM startup time, as opposed to doing anything useful. It might be worth considering making it so the ingest can be run in parallel on each visit, or making it possible to ingest many visits from a single invocation.
