### ISSUE TITLE
Twinkles Task Force summer 2016 report

### ISSUE THREAD

**Issue by wmwv** [DarkEnergyScienceCollaboration/Twinkles#261]
https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Summary_2016Q2.md

is a skeleton for the report to the Spokesperson.  Key thing is to fill in Section 3, which is a report of what we've done.

@drphilmarshall @TomGlanzman @tony-johnson @rbiswas4 @jbkalmbach @jchiang87 

I've added your names to Section 3.  Please update with brief (1-3) sentences summaries of what we've done so far.

**Comment by drphilmarshall** [comment]
We are close to finishing this - thanks for all your edits so far! 
Remaining sub-tasks:
* [ ] @jchiang87 Make sure all computing infrastructure work is credited, with links to repos etc
* [ ] @tony-johnson Make Run 1.1 section and report
* [ ] @tony-johnson Report on Run 2 progress so far
* [ ] @drphilmarshall Outline plans for summer
* [ ] @drphilmarshall Edit Background to call out pathfinder status

Deadline is Friday at Noon PDT at which point @wmwv will forward the link to our finished report to Rachel B, and close this issue. Don't forget to check yo box!

**Comment by drphilmarshall** [comment]
@jchiang87 @tony-johnson I've made my edits, and took a good look through the rest of the text too. Please do git pull and merge - I don't think I'll have gotten too much in your way, but you never know... Apologies if there are conflicts! Should be easy ones to fix though.

@tony-johnson Can you please check and extend what I say about the Run 1 DM processing? I think we shoudl report on the bugs and problems we found. Thanks!

**Comment by tony-johnson** [comment]
I have added some text on Run 1.1 and Run 2.0. I was pretty vague about the bugs found, can go back and add links to actual issues if I have time before the deadline tomorrow.

**Comment by jchiang87** [comment]
I added a sub-section explicitly on computing infrastructure under "Run 1".   It is populated with links to the relevant repos.

**Comment by drphilmarshall** [comment]
Excellent, report looks good to me! Thanks both :-)

Want to take a final pass through before submitting, @wmwv?

**Comment by drphilmarshall** [comment]
OK, I just updated our [README](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/README.md) with a link to the progress report. I didn't update the confluence page too, because it makes more sense to keep driving people over here to see what's up. Let's assume that Michael reported to Rachel already, last Friday - closing out! Thanks for all your input, everyone.
