### ISSUE TITLE
Rebuild DMstack installation on Cori

### ISSUE THREAD

**Issue by heather999** [DarkEnergyScienceCollaboration/Twinkles#268]
From today's NERSC newsletter:
> ** Cori New Software Defaults **
> 
> Due to the upgrade of the operating system, we must also change the defaults for the Cray-provided software libraries. This includes new versions for the MPT, perftools, scientific and math libraries, compilers, and more. For more information on specific release numbers, please see http://docs.cray.com/books/S-9408-1606/ .

Once Cori is back online (~Jun 30th), I should probably reinstall w.2016.20.  It'll also be time to install v12.0

**Comment by tony-johnson** [comment]
Hi Heather, according to the [outage calendar](https://my.nersc.gov/outagecal-cs.php) cori is supposed to be back tomorrow. Getting the rebuilt w2016.20 release would be great so we can restart testing, ideally also on the new higher performance disk area (is that setup now?)

**Comment by heather999** [comment]
@tony-johnson unfortunately the higher performance area is not set up yet - I was told on Friday that the person who could help us was out on vacation last week.  I'm hoping this will be set up early this week.
The NERSC newsletter today indicated they wouldn't be back up until June 30th - it seems to be a revised schedule.  Let me pull up the quote..

**Comment by heather999** [comment]
Just an update..I've sent a fresh poke about getting the new directory space set up this week.. I remain hopeful!

**Comment by heather999** [comment]
Another update... Cori should be available, however I still cannot log in, either via the command line or through NX. Supposedly Cori is "Up": http://www.nersc.gov/users/live-status/ but I see no evidence of activity.  I've opened an incident (INC0086770) at NERSC to see if they can clarify the situation.

**Comment by heather999** [comment]
Cori is indeed back.. Apparently my failed attempt to log in yesterday while it was still down counted against me.  I have 5 failures and my account was locked :)  That's been fixed and now I'm in.  If anyone else continues to have trouble, a locked account may be the culprit.

**Comment by heather999** [comment]
@tony-johnson I think I have w.2016.20 now available in the high performance area for Cori:
/global/common/cori/contrib/lsst/lsstDM/w.2016.20
cd into that directory and "source setupDM-w.2016.20.sh" which should set up your environment correctly.  I ran the demo, and that succeeded the comparison of detected_sources reported that all was OK.
Just let me know if you run into any problems.

**Comment by tony-johnson** [comment]
Hi @heather999 , your setupDM-w.2016.20.sh seems to have a bizarre bug that it works when invoked from the command line, but not when invoked from another bash script. It has to do with your use of BASH_SOURCE, but I do not exactly understand why.

export DM_DIR=/global/common/cori/contrib/lsst/lsstDM/w.2016.20
export DM_SETUP=setupDM-w.2016.20.sh
tony_j@cori06:~/scratch/Twinkles/trial> source ${DM_DIR}/${DM_SETUP}
notice: lsstsw tools have been set up.
This environment includes builds: lsst_apps b2120 and lsst_sims b2121
tony_j@cori06:~/scratch/Twinkles/trial> cat TwinklesTest.sh
#!/bin/bash

source ${DM_DIR}/${DM_SETUP}
tony_j@cori06:~/scratch/Twinkles/trial> ./TwinklesTest.sh 
ModuleCmd_Switch.c(172):ERROR:152: Module 'PrgEnv-intel' is currently not loaded
dirname: missing operand
Try 'dirname --help' for more information.
./TwinklesTest.sh: line 7: cd: /lsstsw: No such file or directory
./TwinklesTest.sh: line 8: /global/cscratch1/sd/tony_j/Twinkles/trial/bin/setup.sh: No such file or directory
This environment includes builds: lsst_apps b2120 and lsst_sims b2121

**Comment by tony-johnson** [comment]
Experimenting more, it appears that some of the module commands overwrite BASH_SOURCE (when it is invoked from another script as above). I don't know how that is even possible, but moving the line which uses BASH_SOURCE above the module commands seems to fix the problem.

**Comment by heather999** [comment]
@tony-johnson Thanks for figuring that out.. I will have to do some investigation and likely will end up sending a note to NERSC help.  Maybe that is some known consequence of dealing with these modules, but that's a surprise to me too!

**Comment by tony-johnson** [comment]
For the record, running with the code installed on /global/common/cori/contrib/lsst appeared to make a dramatic difference to the batch jobs throughput. Thanks to Rollin for suggesting this (and to Heather for re-installing the stack).

**Comment by drphilmarshall** [comment]
Roughly speaking, how did it compare to running at SLAC?

**Comment by heather999** [comment]
@tony-johnson Just for the record.. while doing my first PhoSim install, I played a bit more with the modules loaded.  I found leaving "craype" loaded (as it is be default), seemed to play a little more nicely.  Before the Cori upgrade, it seemed necessary to remove it, but now it seems to cause complaints.
I create a modified setup script for w.2016.20, and left the original just as it was:
/global/common/cori/contrib/lsst/lsstDM/w.2016.20/setupDM-w.2016.20-New.sh

It might be interesting to give it a try sometime to see if that eliminates the bash oddness you saw previously.

**Comment by tony-johnson** [comment]
@heather999 Yes your changes appear to have solved the problem I reported earlier.
@drphilmarshall Comparison of CPU/wallclock time between SLAC and NERSC can be found in the workflow section of slides at:  

https://docs.google.com/presentation/d/1V3uQWBDu1ZXxkb2pwMFmNF8nUckYGUeZWb4XufzQSEc

Closing issue.
