### ISSUE TITLE
Schedule a chat with Dr. Phil about doc

### ISSUE THREAD

**Issue by heather999** [DarkEnergyScienceCollaboration/Twinkles#269]
Hi Phil,
We had discussed possibly chatting about the existing doc - just to give me a lay of the land.  It would be very helpful from my perspective.  I realize, though, that you are very busy!
Take care,
Heather

**Comment by drphilmarshall** [comment]
How about tomorrow morning, pacific time? We could meet at 9am PDT, make a
plan and then a start on implementing it before our noon meeting? Let me
know!

**Comment by heather999** [comment]
9 AM PDT sounds perfect  - sorry I didn't respond sooner, I hope that still works out.

**Comment by drphilmarshall** [comment]
Yep, see you then! I am drphilmarshall on skype, maybe send me a contact
request? Thanks!
