### ISSUE TITLE
Twinkles 2015 Taskforce proposal

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#27]
DESC is defining a set of Taskforces to take on "specific high-priority and timely DESC-specific projects" - that seems to fit our description, so let's submit a proposal to the DESC mgmt. We'll need to start answering the call for proposals via some sort of shared doc (a markdown document on here), link it to the relevant confluence page and then iterate. I'll make a start. Comments welcome via this thread!

**Comment by drphilmarshall** [comment]
Hmm. My table is mangled - anyone with markdown skills want to clean it up? Note that the list of DESC members interested is incomplete: if you'd like to be listed, please do add your name to the table!

**Comment by drphilmarshall** [comment]
PS. Here's the direct link to the file so you can see what's there: https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Taskforce2015_Twinkles.md

**Comment by drphilmarshall** [comment]
I've linked our markdown proposal doc to confluence, so it will keep up with us: https://confluence.slac.stanford.edu/display/LSSTDESC/Taskforces+2015  I'll try and match the list of interested DESC members as we go. (The list is out of sync right now, but don't worry.)

**Comment by drphilmarshall** [comment]
OK, team @DarkEnergyScienceCollaboration/twinkles I think our taskforce proposal is looking in good shape. If you'd like to be listed on it as an "interested DESC member" please do add your name to the markdown table:

https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Taskforce2015_Twinkles.md

(Although of course this implies that you plan on doing more work on the project! :-)

**Comment by cwwalter** [comment]
Thanks Phil! I'm finally back in the US.  I suggest another point to add to "It addresses the following key technical issues:"  This addresses the "plugins" concept we talked about in email.   I envision a generic pipe-line with plugins (following an API)  to inject time dependent sources.  So, for example "sprinklers" could be plugins that inject over sampled SN or lensed quasars into the catalog output.

Here is some candidate text for discussion:

* Underlying the code to simulate time dependent sources will be a implementation of a end-to-end simulation pipeline. This key piece of infrastructure needs to be developed and optimized for both static and time dependent science.  With careful design, a generic end-to-end system with the ability to add many types of sources into the simulated images can serve as a basis for all of our future simulated data productions.

**Comment by cwwalter** [comment]
I suggest moving "Brief Project Summary" from the bottom of this document to the top.

Someone looking at this for the first time needs to know what it is before reading details.

**Comment by drphilmarshall** [comment]
Done, thanks @cwwalter ! Proposal text is [here](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Taskforce2015_Twinkles.md) in case anyone else wishes to comment (or add/remove their name).
