### ISSUE TITLE
Understanding Phosim 3.5.2 vs. Phosim 3.4.2 results for Twinkles visits

### ISSUE THREAD

**Issue by sethdigel** [DarkEnergyScienceCollaboration/Twinkles#288]
For the Hack Day last week at Oxford, Tom started a run of the Twinkles visits using the new version of phosim, which is said to have a more accurate (and dimmer) model of the sky brightness.  The 1227 visits have now completed (about 94 hit the 120-hour CPU time limit).

I've posted some plots comparing CPU times from the original Twinkles run (with phosim v3.4.2) [here](https://confluence.slac.stanford.edu/display/LSSTDESC/Phosim+CPU+times+for+Twinkles+Visits).  Clearly the difference is not as simple as a dimmer sky model resulting in fewer photons and shorter CPU times.  The page also includes a link to a csv file with the log file (CPU time, etc.) and OpSim metadata for this new Twinkles run.

I have not looked at the output files yet; even basic sanity checks will be interesting, and detailed comparisons for some of the runs with widely differing CPU times might be worthwhile too.

**Comment by drphilmarshall** [comment]
Interesting! From what @johnrpeterson has said in the past, it could be worth simply repeating this new run, with the exact same inputs and the new 3.5.2 code, and seeing how reproducible the run times are. He says that there can be some odd effects when using batch farms that lead to high variance in run time at constant configuration.

BTW @sethdigel you can copy and paste plots directly into this issue thread (ie with ctrl-c and ctrl-v) which might make the discussion a bit easier.

**Comment by TomGlanzman** [comment]
Following up on @sethdigel work, I've started my own investigation of phoSim execution time reproducibility, using v3.5.2 and using the first Twinkles run 1 visit.  One test was to run interactively at NERSC (edison) and at SLAC (comet).  

A second test was to create a Pipeline task to run the same visit 100 times on the SLAC batch farm.  The distribution of execution times are presented on this confluence page, https://confluence.slac.stanford.edu/display/~dragon/phoSim+Timing+II.

There are few interesting points from these results.
- phoSim does better on hequ class machines than the canonical "SLAC factor" would suggest
- it is not unusual for job run times to vary 4-7% from the mean within a given machine class
- one does **not** see huge (factors of 2x +) run time differences
- running individual jobs in isolation, e.g., on desktop machines, does not appear to make much difference in total run time

**Comment by sethdigel** [comment]
Thanks, Tom.  That's very nice.  I see that for the 100 repeated phosim runs the same random number seed was used.  And out of curiosity, I confirmed that the output eimage files were exactly the same.  This is reassuring, of course, and I'm sure not surprising.  It does mean that the variations in CPU time are not due to phosim simulating different photons in the different runs.

**Comment by sethdigel** [comment]
Just for the record in this issue, we learned recently that the phosim v3.5.2 runs were not identical to the original Twinkles 1 visits because in the original runs the intended altitude (angle above the horizon) of the observations was not interpreted by phosim, so they were all simulated at a default altitude of 89 deg.  For the v3.5.2 runs, the altitudes of the observations were as specified in the OpSim metadata, and so they generally greater sky brightness toward the observing direction.  This could explain the large number of visits for which the v3.5.2 CPU time was greater than the CPU time for the original Twinkles runs even though the v3.5.2 sky model is nominally dimmer
