### ISSUE TITLE
Who's going to Hack Week?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#302]
Mark your planned attendance on this doodle poll, please: 

http://doodle.com/poll/8yt8c4dke3629q8i

Rough plan is: infrastructure stuff Monday-Friday, science analysis Wednesday-Tuesday.
Hooray Pittsburgh! :-)

**Comment by wmwv** [comment]
> On Aug 25, 2016, at 22:00 , Phil Marshall <notifications@github.com> wrote:
> 
> Rough plan is: infrastructure stuff Monday-Friday, science analysis Wednesday-Tuesday.

Is the science analysis moving backward in time
or is it Wednesday-Thursday?

 - Michael

**Comment by drphilmarshall** [comment]
Its Weds of Hack Week to Tuesday of the following week, at your place. We
figured itd be good to let teh CI group focus on nonTwinkles stuff the
first half of the actual Hack Week, and then we can bug them on Weds-Fri.

**Comment by wmwv** [comment]
Ah, Excellent!  I will arrange some local space once I know numbers.

**Comment by drphilmarshall** [comment]
@wmwv Looks like it'll be me, Simon, Rahul and Bryce powering through the weekend after hack week and all the way through the end of Tuesday 15th, which is great! Can you find a place for the 5 of us to hack in peace on the Monday and Tuesday, please? Preferably away from any other astronomers :-)

Meanwhile, the CI team of Simon, Scott and Tom will be present all 5 days of hack week. How about you, @tony-johnson @TomGlanzman @heather999 @sethdigel ?

Our next move (apart from registration, hotel  and flight booking, and reimbursement setup) should be to edit the [Hack Week confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/Hack+Week%3A+November+7-11%2C+2016+-+CMU) to make sure it is accurate (and then continue doing that right up until November 7). A good idea is to go search for your name on that page to make sure it appears everywhere you want it to.

Oh and BTW, the General Election is November 8, so you will need an absentee ballot. Citizens, [click here to get started on saying no to authoritarianism](https://www.fvap.gov/vao/vag)

**Comment by heather999** [comment]
I'm planning to be there for all 5 days of Hack Week.. and will file my absentee ballot (I'm in a swing state!)
Can we plan an election evening get together where we're hopefully not left to cry in our beers?
