### ISSUE TITLE
Write an instance catalog generation task

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#305]
@rbiswas4 This will entail adding the scripts you ran at NCSA to generate the instance catalogs (and SEDs) for Run1.1 to the Twinkles repository and packaging it all up as a task that we can run in batch via the SLAC workflow engine.   This will also entail updating the code to accommodate recent interface changes in the Stack, consistent with the version of the sims distribution we intend to use.

**Comment by drphilmarshall** [comment]
I guess maybe @danielsf was working on this too - any news from up there? :-)

**Comment by rbiswas4** [comment]
Yes. @danielsf has the branch working .... I plan to make some changes preserving that state, but to make life a little easier than before.

**Comment by jchiang87** [comment]
closed by #327
