### ISSUE TITLE
Install the agreed-upon sims version at SLAC for Run3 data generation and analysis

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#306]
@heather999 @danielsf @rbiswas4 @jbkalmbach  Can you guys sort out which version to install?

**Comment by heather999** [comment]
I'll keep an eye on the discussion here.  @jchiang87 would you want this installed at SLAC in:
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack  ?
I'm assuming we're not using NERSC due to the Cori outage.

**Comment by jchiang87** [comment]
I think that should be fine.
