### ISSUE TITLE
Double check that quad lensing systems are present in instance catalogs

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#311]
Basically, verification of issue #192 in new instance catalogs.

**Comment by jbkalmbach** [comment]
We do indeed have the sprinkler creating quads in the instance catalogs. The notebook seen here: https://gist.github.com/jbkalmbach/37f1b42afc3764ba2b4ad696ce2c546f shows that from the agn from an instance catalog (attached file) we do indeed see twinkles systems with 4 images appearing in the phosim instance catalogs.
[agn_input_220.txt](https://github.com/DarkEnergyScienceCollaboration/Twinkles/files/488121/agn_input_220.txt)

**Comment by drphilmarshall** [comment]
Great! Looking fwd to seeing these systems in action :-)
