### ISSUE TITLE
Avoiding phoSim indexing failures in Run 3

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#312]
@drphilmarshall 
Is there a plan to avoid indexing failures due to phosim for run3 ? As a reminder in previous runs, we have found and reported that PhoSim tries to index objects by floats, and indices are messed up due to precision problems when these are large. I do not know if phosim was changed to avoid this problem. I forgot to mention this during the meeting. 

A possibility could be checking out our own branch of phosim and modfiying the index to a string before writing it out. We can then tag this and use this tagged version. I will not have time to work on it immediately.

**Comment by drphilmarshall** [comment]
Hmm. Do you know if phosim has been upgraded to use string or integer
indices, @TomGlanzman? Does anyone know whether there is an open ticket on
the phosim release bitbucket?

**Comment by jchiang87** [comment]
This doesn't seem to have been issued there:
https://bitbucket.org/phosim/phosim_release/issues

**Comment by drphilmarshall** [comment]
Good, thanks Jim. Rahul or Bryce, can you please write a phosim ticket and
ask for advice regarding a workaround? When you've made it, please post the
link to it here so we can follow along. Thanks!

**Comment by rbiswas4** [comment]
I thought I saw that Bryce had already posted a link but : https://jira.lsstcorp.org/secure/RapidBoard.jspa?rapidView=12&projectKey=PHOSIM&view=detail&selectedIssue=PHOSIM-27

**Comment by rbiswas4** [comment]
Closed through #340 for run 3 and kept track of in genral in #383
