### ISSUE TITLE
Generate reference catalogs with data for all six bands

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#316]
This involves modifying [bin/make_reference_catalog.py](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/bin/make_reference_catalog.py) to include u, z, and y bands, and then using the resulting reference catalog to generate the astrometry.net index files (as [documented in the Level 2 cookbook](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Cookbook/DM_Level2_Recipe.md)) with band-specific fluxes for each band.  This will help ensure the zero points found in the Level 2 processing are correct for each band.  See #267.

**Comment by rbiswas4** [comment]
👍 

Incidentally, does this change the few percent change in the other bands that we had been looking at? The change in catsim might also help in fixing that (it was galactic extinction which was being applied wrongly).

**Comment by jchiang87** [comment]
Comparing the magnitudes I've been seeing from CatSim to the ones in the cookbook, there will be differences in the zero points in all bands (from this morning's run, r, g, and i magnitudes also differ by 0.2 mag).   I plan to re-run `processEimage.py` on all of the Run1.1 visits (also turning on the cosmic ray repair) to get new zero points.   I can reload my local pserv db instance with the modified data to show the outcome of these corrections.  If we decide it's desirable, we can also update the Twinkles Run1.1 tables at NERSC (or add a Run1.1_new_zp project to preserve the current data).   I'm not sure it's worth re-running all of Level 2, but it may be something we want to do, depending on the Run3 status.

**Comment by jchiang87** [comment]
The index files are here `/nfs/farm/g/desc/u1/data/PhoSim-Deep-Precursor/and_files/`
