### ISSUE TITLE
ObsHistID selection for Run 3

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#329]
Are we doing all obshistID with fieldID = 1427 and propID = 56 from Minion 1016?  I should 
- [x] change the selection criteria in the phosim instance catalog generation script
- [x] If it is not a single propID, I should drop duplicates

**Comment by drphilmarshall** [comment]
Good questions, thanks Rahul. We need to be able to investigate light
curves with both the WFD cadence and the DDF cadence, so I think we need
both these proposals (just like in real life, no?). I don't know what you
mean by "duplicates" - does each visit not have a unique proposal ID? Or do
some visits get labelled with both IDs, to make it easier to do things like
"select all visits at position x,y"?

**Comment by rbiswas4** [comment]
Yes, combined would be closest to real life I think. 

>  I don't know what you
mean by "duplicates" - does each visit not have a unique proposal ID? Or do
some visits get labelled with both IDs, to make it easier to do things like
"select all visits at position x,y"?

It is an OpSim thing: there are multiple records that are identical (including obsHist), except for proposalID (ie. the visit serves the purposes of two different proposals). We deal with that routinely, so I just need to remember to do it.

**Comment by drphilmarshall** [comment]
Great, thanks! I noticed a while back that the string "kraken" appears a
lot in our code. Can you confirm that `minion_1016` is exactly the same as
`kraken_1042` (3?) please? I'm pretty sure it is, but it's important
because when we write about this project, we need to quote `minion_1016`
(because only this one is the official baseline cadence).

**Comment by rbiswas4** [comment]
>  I noticed a while back that the string "kraken" appears a
lot in our code. 
That should change. If you see kraken (except in the names of tables, please let me know). I would prefer we actually use minion if we write we are using minion.

> Can you confirm that `minion_1016` is exactly the same as
`kraken_1042`

I am going to ping @danielsf and @yoachim for the exact slight differences.

**Comment by yoachim** [comment]
There are very minor differences between the two, despite having identical inputs. 

I think this was an issue where things were stored in python dictionaries, so order of items was not guaranteed to be the same.

**Comment by drphilmarshall** [comment]
Thanks Peter. `minion_1016` it is then!

**Comment by rbiswas4** [comment]
@drphilmarshall I thought this was done and (had set it to autoclose when the setups pull request was accepted). What are you wanting us to do here?

**Comment by rbiswas4** [comment]
I am taking this as closed, please reopen if something else is wanted.
