### ISSUE TITLE
Test issue to exercise Zenhub

### ISSUE THREAD

**Issue by connolly** [DarkEnergyScienceCollaboration/Twinkles#33]
A test issue to try out Zenhub interface

**Comment by connolly** [comment]
an item of work as an issue

**Comment by connolly** [comment]
@DarkEnergyScienceCollaboration/twinkles to try out a simple agile interface to the Twinkles work go to https://www.zenhub.io/ and install the browser extension (you will need chrome to do this) and access the "boards" link on the right side of https://github.com/DarkEnergyScienceCollaboration/Twinkles We can discuss this at the DESC twinkles session

**Comment by drphilmarshall** [comment]
I like it! It's like trello on top of GitHub :-) I vote we adopt it forthwith.
