### ISSUE TITLE
Turn off per amp images when running phosim for Run3

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#339]

**Comment by drphilmarshall** [comment]
Where, in the phosim configuration, is this requested? In the physics override file or somewhere else?

**Comment by cwwalter** [comment]
Do you mean you only want e-images?  I usually do this with the "-e 0" command line option.

**Comment by jchiang87** [comment]
yes! thanks @cwwalter

**Comment by TomGlanzman** [comment]
Done (once this PR #374 is complete)
