### ISSUE TITLE
Twinkles retreat and hack week

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#343]
@drphilmarshall apologies if this is captured somewhere, but I couldn't find it.  Following are a few questions about the retreat attached to the hack week in November.

1. Where are we doing it?  Is @wmwv finding us a place at Pitt?
2. I think I remember that we were doing it after the hack week not before.  If that's true are we spending all of Monday - Wednesday or can I fly on Wednesday?
3. Are people planning on working over the weekend?  I understand that locals will probably not want to sacrifice their weekend, but maybe those who have nothing better to do would want to get together.

It would be good to get this worked out ASAP so I can buy flights.  Sorry if this is duplication.

**Comment by rbiswas4** [comment]
Can I add a question about people adding possible hotels they are finding (particularly for the part after the hack week) If we can coordinate, a cheaper off-campus location + rented cars might be better for the group?

**Comment by drphilmarshall** [comment]
Re: accommodation. I looked for a VRBO house in Pittsburgh but drew a
blank. We can't use SLAC funds to pay for AirBnb places. Does anyone know
of any other vacation rentals we could use? Sharing a house seems like a
good plan, for the weekend and two days after wards.

Simon: I am flying home from Pittsburgh on the Wednesday, and plan on
working on Twinkles with you all over the weekend.

**Comment by sethdigel** [comment]
Not a vacation rental, but the [Shadyside Inn](http://www.shadysideinn.com/) has a general recommendation from Rachel M.  It has two-bedroom suites with kitchens, and wifi, and is convenient to CMU.  She says they put up seminar speakers there, and relatively speaking the prices look good.

**Comment by SimonKrughoff** [comment]
> Simon: I am flying home from Pittsburgh on the Wednesday, and plan on
working on Twinkles with you all over the weekend.

Excellent!  That's what I'll plan on too.

**Comment by drphilmarshall** [comment]
That was a good find, Seth - but I think they're sold out :-/
A small guesthouse with a common room to hang out together in could be good?

**Comment by heather999** [comment]
You might try a small B&B..  though you will want to double check the strength of their wifi. Some might be willing to negotiate if you are reserving most or all of their rooms:
http://www.pittsburghbnb.com/locate.html

**Comment by drphilmarshall** [comment]
We moved the accommodation  discussion to Slack, and its going well! Re Monday and Tuesday, we can be flexible, and either invite Michael over to our house, or go into Pitt and hang out. Lets see what happens, and coordinate by Slack.
