### ISSUE TITLE
Problem using generatePhosimInput.py

### ISSUE THREAD

**Issue by TomGlanzman** [DarkEnergyScienceCollaboration/Twinkles#345]
Ahoy @rbiswas4.   Using instructions provided by @jchiang87 [see below] I was able to run the generatePhosimInput.py script using the included example.  The script ran to completion (elapsed time >1 hour), showed evidence of running the sprinkler, created the instanceCatalog and the directory to contain SED files.  However, the SED directory was empty.

Below are Jim's instructions, followed by a partial transcript of the script.  Note at the very end is the directory containing the instanceCatalog and (empty) SED directory.

[Jim's instructions]

The instance catalog generator script is now ready for you to use to develop the phosim pipeline task.

First you'll need to set up db credentials following the instructions in my comment here:

https://github.com/DarkEnergyScienceCollaboration/Twinkles/pull/328#pullrequestreview-3231762

Then from a rhel6-64 machine do

$ scl enable devtoolset-3 bash
bash$ source /nfs/farm/g/desc/u1/twinkles/setup.sh 
added /nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/py-2.7.11/bin, git 1.8.4.5, and git-lfs 1.4.1 to PATH
[Twinkles] 

The script will be in your PATH.  Invoking with the --help option gives

[Twinkles] generatePhosimInput.py --help
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 25 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 40 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
usage: generatePhosimInput.py [-h] [--opsimDB OPSIMDB]
                              [--OpSimDBDir OPSIMDBDIR] [--outfile OUTFILE]
                              [--seddir SEDDIR]
                              visit

Write phoSim Instance Catalogsand SN spectra to disk example : python
generatePhosimInput.py 230\ --OpSimDBDir ~/data/LSST/OpSimData/\ --seddir
"./"\ --outfile phosim_instance_catalog_220.txt

positional arguments:
  visit                 Visit number (obsHistID)

optional arguments:
  -h, --help            show this help message and exit
  --opsimDB OPSIMDB     OpSim database sqlite filename
  --OpSimDBDir OPSIMDBDIR
                        absolute path to dir with the opsimBD
  --outfile OUTFILE     output filename for instance catalog
  --seddir SEDDIR       directory to contain SED files
[Twinkles] 

​You can ignore all the cruft from the UW servers regarding "globally unique id values".
The calling sequence you might use for running at SLAC would be

​[Twinkles] generatePhosimInput.py 200 --OpSimDBDir /nfs/farm/g/desc/u1/data/Twinkles --seddir . --outfile phosim_input_200.txt

This will automatically use the minion_1016_sqlite.db file.

[script transcript]

time generatePhosimInput.py 200 --OpSimDBDir /nfs/farm/g/desc/u1/data/Twinkles --seddir . --outfile phosim_input_200.txt
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 25 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 40 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
will generate pointing for 200 and write to filename phosim_input_200.txt
{'mjd': 59580.123742999996, 'pointingRA': 56.520281137372756, 'rotSkyPos': 356.35786158359804, 'boundLength': 0.29999999999999999, 'skyBrightness': 17.300000000000001, 'OpsimMetaData': {'sunAlt': -0.53665799999999997, 'sunAz': 3.6504340000000002, 'rotSkyPos': 6.2196179999999996, 'slewDist': 0.049426999999999999, 'mieScatter': 8038.6125940000002, 'moonIllum': 7.1000000000000005e-05, 'visitExpTime': 30.0, 'lst': 1.3011459999999999, 'azimuth': 3.3564919999999998, 'moonDec': -0.409327, 'humidity': 0.0, 'ditheredRA': 0.94963807402972034, 'moonPhase': 3.893519, 'phaseAngle': 157.23943199999999, 'index': 0, 'filtSkyBrightness': 17.300000000000001, 'rawSeeing': 0.74412, 'altitude': 0.92568300000000003, 'fieldRA': 0.98646500000000004, 'rotTelPos': 0.39675199999999999, 'obsHistID': 200, 'moonAlt': -0.633266, 'solarElong': 85.061981000000003, 'moonRA': 4.4690029999999998, 'FWHMeff': 0.98029299999999997, 'airmass': 1.2515179999999999, 'expMJD': 59580.123742999996, 'night': 0, 'darkBright': 94.164088000000007, 'expDate': 10691, 'moonBright': 0.0, 'finRank': 4.5418089999999998, 'dist2Moon': 1.5671790000000001, 'propID': 53, 'moonAZ': 3.171484, 'FWHMgeom': 0.85780100000000004, 'rScatter': 242834.96840000001, 'fieldDec': -1.143187, 'sessionID': 1016, 'ditheredDec': -1.169638, 'visitTime': 34.0, 'filter': u'y', 'fiveSigmaDepth': 21.483129999999999, 'slewTime': 4.5217070000000001, 'transparency': 0.0, 'vSkyBright': 21.396433999999999, 'fieldID': 244, 'wind': 0.0}, 'site': <lsst.sims.utils.Site.Site object at 0x7fced5fb98d0>, 'boundType': 'circle', 'bandpass': u'y', 'pointingDec': -65.499790294222038}
writing starCat 
WARNING: ErfaWarning: ERFA function "taiutc" yielded 1 of "dubious year (Note 4)" [astropy._erfa.core]
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sqlalchemy/1.0.8.lsst3+2/lib/python/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/dialects/mssql/base.py:1783: SAWarning: Did not recognize type 'geography' of column 'geopoint'
  (type, name))
WARNING: ErfaWarning: ERFA function "utcut1" yielded 1 of "dubious year (Note 3)" [astropy._erfa.core]
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sqlalchemy/1.0.8.lsst3+2/lib/python/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py:3779: SAWarning: Textual SQL expression 'gmag > 11.0' should be explicitly declared as text('gmag > 11.0') (this warning may be suppressed after 10 occurrences)
  {"expr": util.ellipses_string(element)})
writing galCat
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  10000
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
Running sprinkler. Catalog Length:  1763
Gone through  0  lines of catalog.
Gone through  100  lines of catalog.
writing sne
200 4240.70430613

real	71m58.174s
user	2m48.618s
sys	0m8.817s
[Twinkles] pwd
/nfs/farm/g/desc/u1/Pipeline-tasks/TW-phoSim-r3/genIC
[Twinkles]

**Comment by jchiang87** [comment]
I've run that script numerous times at SLAC and each time it has produced SED files.  Here are the contents of the directory from the most recent run about an hour ago (using visit 230 instead of 200, though visit 200 had previously created SED files for me):
```
[Twinkles] pwd
/nfs/farm/g/desc/u1/twinkles/generatePhosimInput_tests/tmp
[Twinkles] tree | head -30
.
|-- None
|-- phosim_input_230.txt
|-- run_230.log
`-- spectra_files
    |-- specFile_6000000053819_59580.1396_r.dat
    |-- specFile_6000000453109_59580.1396_r.dat
    |-- specFile_6000000546107_59580.1396_r.dat
    |-- specFile_6000000546108_59580.1396_r.dat
    |-- specFile_6000001193801_59580.1396_r.dat
    |-- specFile_6000002425203_59580.1396_r.dat
    |-- specFile_6000003011801_59580.1396_r.dat
    |-- specFile_6000004132602_59580.1396_r.dat
    |-- specFile_6000004924900_59580.1396_r.dat
    |-- specFile_6000006235400_59580.1396_r.dat
    |-- specFile_6000006378201_59580.1396_r.dat
    |-- specFile_6000006895902_59580.1396_r.dat
    |-- specFile_6000008103508_59580.1396_r.dat
    |-- specFile_6000008189004_59580.1396_r.dat
    |-- specFile_6000008189006_59580.1396_r.dat
    |-- specFile_6000008253006_59580.1396_r.dat
    |-- specFile_6000008723602_59580.1396_r.dat
    |-- specFile_6000008741900_59580.1396_r.dat
    |-- specFile_6000012473601_59580.1396_r.dat
    |-- specFile_6000012661101_59580.1396_r.dat
    |-- specFile_6000012717300_59580.1396_r.dat
    |-- specFile_6000013172203_59580.1396_r.dat
    |-- specFile_6000013352703_59580.1396_r.dat
    |-- specFile_6000013400704_59580.1396_r.dat
    |-- specFile_6000013437501_59580.1396_r.dat
[Twinkles] 
```
In the area where Tom ran the script, I see
```
[Twinkles] pwd
/nfs/farm/g/desc/u1/Pipeline-tasks/TW-phoSim-r3/genIC
[Twinkles] tree | head -30
.
|-- README
|-- phosim_input_200.txt
|-- phosim_input_200.txt_0
|-- phosim_input_200.txt_1
`-- spectra_files

1 directory, 4 files
[Twinkles] wc phosim_input_200.txt
  321753  7348632 62253134 phosim_input_200.txt
[Twinkles] 
```
Interestingly, there is no file called `None` in Tom's area.

**Comment by danielsf** [comment]
Is it possible Tom is not using the same version of lsst_sims as Jim?  @TomGlanzman what do you see when you run `eups list lsst_sims`

**Comment by danielsf** [comment]
Actually, run `eups list sims_catUtils`; that will be more informative

**Comment by jchiang87** [comment]
It's worth checking to be sure, but Tom and I should have used the same setup procedure, i.e., executing setup scripts for slac that I wrote.  Here's what eups tells me:
```
[Twinkles] eups list sims_catUtils
   12.0-20-gd0952e3 	sims current b2323 sims_2_3_1 setup
[Twinkles] 
```

**Comment by danielsf** [comment]
@jchiang87 that is what should be set up.

I suspect it is lsst_sims because there were a lot of changes to the spetra_file API for supernovae in the latest sims release

**Comment by rbiswas4** [comment]
Possible, but I had checked before the merge. I am trying to run this on slac and getting various errors (probably related to my not setting up the database credentials on SLAC), I will try again in a bit.

**Comment by rbiswas4** [comment]
OK, I am still having permission issues on this machine, but that should be a separate issue. The problem here is the use of the obshistid 200, rather than for exmple 230. (This is one of the differences between what @jchiang87 ran and what @TomGlanzman ran). 

The point is obshitsID 200 for minion is not in the Twinkles area, but somewhere else. This can be seen from either OpSim  (This obshitsid has a fieldID of 244) or the header of the phosim instance catalog 
```
rightascension 56.5202811
declination -65.4997903
```
and supernovae are not 'sprinkled' in the region. Hence the phosim instance catalog has no SN, and consequently no spectra are written to disk.

**Comment by TomGlanzman** [comment]
It is a bit late, but for the record (and for the future), here is what I see in response to @danielsf 's request:

(Wed 00:06) dragon@rhel6-64c (bash) $  scl enable devtoolset-3 bash
(Wed 00:06) dragon@rhel6-64c (bash) $ source /nfs/farm/g/desc/u1/twinkles/setup.sh
added /nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/py-2.7.11/bin, git 1.8.4.5, and git-lfs 1.4.1 to PATH
[Twinkles] eups list lsst_sims
   12.0-1-g5aa7ebb+61   current sims b2323 sims_2_3_1 setup
[Twinkles]  eups list sims_catUtils
   12.0-20-gd0952e3     sims current b2323 sims_2_3_1 setup

=====

Which looks good.

I will try obhistID 230 rather than 200 later in the morning.

  - Tom

**Comment by drphilmarshall** [comment]
Thanks Tom!

**Comment by jchiang87** [comment]
So I learned three things from this issue:
* Visit numbers for minion_1016 are not the same as for kraken_1042.  This is a bigger difference between the two than I had understood.
* Sprinkling can only be done for the Twinkles field.  This is presumably a region of some size centered on the focalplane center for our field.  What is that region size?
* Running `generatePhosimInput.py` at SLAC can take a lot longer than I had thought.  When I did tests running it last week, it seemed to finish in ~10 minutes.  The runs Tom and I have done this week now take about ~70minutes.  I don't think this is necessarily a show stopper, but we should try to understand what affects the execution time and try to make it as fast as possible.

**Comment by rbiswas4** [comment]
- Sprinkling region for SN: 0.3 degrees around the fieldRA, fieldDec (If you would like I can change that .... (In Twinkles 1 this was 0.4 * np.sqrt(2), but we decided that this was unnecessary.)

- I think we might be able to improve the performance by playing with the `chunksize`  parameter in `twinkles_sky`, and suppressing the output to screen. Of course other methods are possible, but they might take more effort. I am surprised that you have times going from 10 min (which is what I had seen on my computer), to 70 mins (internet/fatboy issue?)

**Comment by danielsf** [comment]
@jchiang87 I think the slow down may be on fatboy's side.  I have been noticing massive variance in the length of time it takes to create InstanceCatalogs.  I am currently updating the asteroid models on fatboy.  That might be taking up fatboy's resources and slowing the database query down.  Once the asteroid models are done updating, I intend to run some tests and see if that was, indeed, the problem.

**Comment by danielsf** [comment]
Unfortunately, it looks like the asteroid update will take about 10 days.

**Comment by TomGlanzman** [comment]
Using the obsHistID of 230 rather than 200 does, indeed, cause the generatePhosimInput.py script to create SED files.  The test run took 42 minutes to complete.
Start time: Wed Oct 12 10:22:10 PDT 2016

While the reported run of obsHistID 200 took 71 min, an earlier test took only 23 min.

Given the discussion of the load on fatboy, does this suggest that running thousands of jobs, some of which will  be running simultaneously, will overload that system?  Can anyone estimate how many simultaneous queries of the sort needed by the script that machine can handle?

**Comment by danielsf** [comment]
Yusra Alsayyad pointed me to a setting which demands that my asteroid update only use one thread.  That might open fatboy up for our catalog generation.  Try running your tests again, @TomGlanzman @jchiang87

**Comment by jchiang87** [comment]
thanks @danielsf !  I'll give it a try.

**Comment by TomGlanzman** [comment]
Two more tests, exact repeats of the  one above (obsHistID=230) took 23 and 20 minutes.

**Comment by jchiang87** [comment]
My test with obsHistID 230 took 35 minutes.

**Comment by drphilmarshall** [comment]
Scott and Rahul suggested a workaround for this, now issued in #346 . Your work is done, testers! :-)
