### ISSUE TITLE
phosim configuration for Run3

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#348]
Maybe I've missed it, but I don't see an issue to set 
```
contaminationmode 0
```
in the [physics override file](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/workflows/PhoSim/twinkles_I_physics_override.txt).   Since we've decided (or so I understood) to use phosim 3.5.3 for Run3, this issue is to set that option.

**Comment by TomGlanzman** [comment]
Here is the 'working version' of the phoSim command currently used by the pipeline task.  Please comment:

# Turn on debugging file
centroidfile 1

# Does this turn off treerings too?
cleardefects

# Also turn off clouds and airglow variation
clearclouds
airglowvariation 0

# Set the nominal dark sky brightness
zenith_v 21.8

# Leave on CRs but turn off fringing.  ISR will take care of fringing, # but CRs are currently taken out in
# image characterization.
fringing 0

# Activate internal checkpointing
#   Initial conditions should be:
#   checkpointtotal = total number of desired checkpoints - 1
#   checkpointcount = 0  (but set to "%" for automated management of that value)
#checkpointtotal 8
#checkpointcount %

# Disable optics contamination
contaminationmode 0

**Comment by jchiang87** [comment]
Here is John's comment on what he thinks we should disable in this file if we are using v3.5:
https://github.com/DarkEnergyScienceCollaboration/SSim_DC1_Roadmap/issues/20#issuecomment-250494847

**Comment by drphilmarshall** [comment]
Thanks Jim. John was talking about the LSS group's requirements: I think we can leave clouds and airglowvariation off in Twinkles 1 no problem. Likewise, he points out that `zenith_v 21.8` is there to try and make sure that the visit-to-visit sky variation is not unphysically uncorrelated - so I think we should leave that line in.

This leaves the only change we need to make in  [master/workflows/PhoSim/twinkles_I_physics_override.txt](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/workflows/PhoSim/twinkles_I_physics_override.txt) as being to add 
```
# Disable optics contamination
contaminationmode 0
```
I'll make this change now.
