### ISSUE TITLE
change to generatePhosimInputs.py to put only relative paths in instance catalogs

### ISSUE THREAD

**Issue by TomGlanzman** [DarkEnergyScienceCollaboration/Twinkles#351]
Request: 

A modification to generatePhosimInputs.py so that the "--seddir" string is NOT prepended to the file path stored in the instance catalog for each object, but continues to be used as the location in which to store the generated data products.

Reason:

The generatePhosimInputs.py script takes an option to specify the directory in which to store the SED files ("--seddir"). However, the script then prepends that directory + "spectra_files/" to each object's filename in the instance catalog. By intention, I specify "--seddir" as an absolute path in a special semi-persistent store for pipeline efficiency. When I run the script in the pipeline, objects in the instance catalog then have SED references that look like: /long-path/spectra_files/...

When phoSim runs, specifying the "--sed" option causes that string to be prepended to the object's SED reference in the instance catalog. In the pipeline task, this is specified as an absolute path, e.g., /another-long-path. The production SEDs have relative paths in the instance catalog, e.g., starSED/..., so this makes sense. For the custom generated objects, that same treatment results in a bogus path, /another-long-path//long-path/spectra_files/...

**Comment by rbiswas4** [comment]
Sure .... so the point is that the seddir argument should now be the absolute path.

**Comment by TomGlanzman** [comment]
No, it is fine to have a spectra_files directory to contain the SED output files from this script, in fact that makes for a cleaner organization when manually looking through the files and trying to separate "production" from "sprinkled" SED files.  The request is to strip the --seddir string from within the instanceCatalog.

For example, this:

object 6144931887513642 53.0938903 -27.6696697 23.6904462 /lustre/ki/pfs/fermi_scratch/lsst/TW-phoSim-r3/singleSensor/0/0/spectra_files/specFile_6000910046400_59580.1396_r.dat 0.4962 0 0 0 0 0 point CCM 0.0296285059 3.1 none

should be this:

object 6144931887513642 53.0938903 -27.6696697 23.6904462 spectra_files/specFile_6000910046400_59580.1396_r.dat 0.4962 0 0 0 0 0 point CCM 0.0296285059 3.1 none

**Comment by TomGlanzman** [comment]
The forty test phoSim runs using Twinkles/bin/generatePhosimInput.py (branch Issue#351/spectraFileNameDefs, commit 3fcc01b314339a024bfb316cb278b4e263cbf2b9) was mechanically successful.  Somewhere along the line, a data/galaxy_cache.db file was created.

**Comment by jchiang87** [comment]
>  Somewhere along the line, a data/galaxy_cache.db file was created.

That is, of course, intended behavior and enables the instance catalog generation step to run efficiently.  See #349

**Comment by rbiswas4** [comment]
I was checking the instance catalogs, and have been able to confirm that sedfilepaths including 'None' are correctly not included in the catalog.
