### ISSUE TITLE
Can we remove `https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/python/desc/twinkles/generatePhosimInput.py`

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#361]
This seems to be outdated in favor of `bin/generatePhosimInput.py`. Do people think this can be deleted to avoid confusion?

**Comment by jchiang87** [comment]
yes, definitely. There are a handful of other things I'd like to clean up regarding out-of-date code.

**Comment by jbkalmbach** [comment]
Yes, this seems like a good idea.

**Comment by jchiang87** [comment]
I'll make a PR from a branch where I've removed stuff that looks outdated.

**Comment by drphilmarshall** [comment]
Great, thanks Jim!
