### ISSUE TITLE
Update Level 2 workflow scripts for Stack v12_1

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#372]
See https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/369#issuecomment-256235767

**Comment by drphilmarshall** [comment]
Good catch, Jim.

**Comment by jchiang87** [comment]
I guess since we are running v12_0 at NERSC, this change probably doesn't need to be made, but we should double check.

**Comment by tony-johnson** [comment]
This has been done.
