### ISSUE TITLE
Integrate SNe realizer into catalog framework

### ISSUE THREAD

**Issue by connolly** [DarkEnergyScienceCollaboration/Twinkles#38]
Develop code to implement the SNe into the catalog framework. The tasks associated with this SNe realizer are:
- [x] Code to query catalogs for galaxies and identify host galaxies
- [x] Code to define the probabilities of generating a SNe (e.g. SNe rate,)
- [x] Assign a start time for the SNe based on a known seed 
- [ ] Validate that the redshift distributions and properties are consistent with the input model

**Comment by drphilmarshall** [comment]
Hey Rahul - you must be so close to being able to close this issue, showing that you have "validated that the redshift distributions and properties are consistent with the input model", now that Run 1 is go!

**Comment by drphilmarshall** [comment]
PS. As extra motivation: we are now only 4 issues away from completing the [Run 1 Data Generation Start milestone](https://github.com/DarkEnergyScienceCollaboration/Twinkles/milestones/Twinkles%201%20Run%201%20Data%20Generation%20Start) :-)
