### ISSUE TITLE
PhoSim Indexing Failures

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#383]
`PhoSim` indexes astrophysical sources with floats. For very large integers used as instance catalog indices , this causes indexing failures due to precision issues. This was found in the first set of Twinkles runs. A ticket describing the problem was filed in https://jira.lsstcorp.org/secure/RapidBoard.jspa?rapidView=12&projectKey=PHOSIM&view=detail&selectedIssue=PHOSIM-27 .

For Twinkles run 3, this problem was reported in #312 and taking advantage of the restricted nature (single CCD, rather than all sky), this issue was solved for Twinkles 3 in #340  . However, in general (where there will be more objects due to larger sky area) the problem is unsolved.

**Comment by drphilmarshall** [comment]
Thanks, @rbiswas4 . I think that means that this is not an issue for Twinkles, but might be for DC1 PhoSim Deep. I'll re-issue it there!
