### ISSUE TITLE
Recommended configs for Run 3

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#395]
In doing some looking into how to do the diffim against templates, I've found a few configs I think we will want to update.  Look in the twinkles_395 branch of obs_lsstSim for the versioned versions of these.

**Comment by drphilmarshall** [comment]
For future reference, would you mind posting links to these configs please,
@SimonKrughoff? Thanks!

**Comment by SimonKrughoff** [comment]
Of course!  I think it may end up being link a link to a branch of the obs_lsstSim repository, but I'll definitely make sure they are get-toable from here.

**Comment by SimonKrughoff** [comment]
I am working on this on the `twinkles_395` branch of obs_lsstSim.  @tony-johnson ran into a problem with PSF measurement that I think was caused by CRs making it into the PSF candidate list.  I think that the config [here](https://github.com/lsst/obs_lsstSim/blob/twinkles_395/config/processEimage.py) should help with that.  Specifically, it turns on CR detection and interpolation.  It also makes a more conservative estimate of the initial PSF.

**Comment by SimonKrughoff** [comment]
@tony-johnson @heather999 I have merged this to a brand new branch in `obs_lsstSim` called [`twinkles_1`](https://github.com/lsst/obs_lsstSim/tree/twinkles_1).  We should now be using that branch whenever we run the level 2 or level 1 cookbook on twinkles data.  @heather999 can you install that on SLAC and NERSC and update the setup scripts please?

**Comment by SimonKrughoff** [comment]
FYI this was reviewed in a pull request on `obs_lsstSim` by @wmwv.
