### ISSUE TITLE
Change the ordering of ObsHistID for Twinkles Run 3

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Twinkles#402]
The `bin/get_twinkles_visit.py`  follows the prescription outlined in https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/347 . Talking to @drphilmarshall , it became apparent that there is a need to get the WFD visits first. This means, that we should stick in all the WFD visits at the beginning of Twinkles3.2  if possible

**Comment by drphilmarshall** [comment]
The logic was that in case it takes a long time to complete the DDF visits,
we could be doing a more-or-less complete analysis of the WFD survey, and
potentially even write that up on its own with the DDF analysis in a
follow-up paper. I don't think we'll necessarily be in this position, but
you never know: it seems like a good idea to enable ourselves to finish a
logical unit of analysis, as a safety net.
