### ISSUE TITLE
Twinkles active contributor list for Symmetry feature

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#417]
Hi @DarkEnergyScienceCollaboration/twinkles !

Last week Richard and I got interviewed by Symmetry (national lab HEP news and features) magazine about the Twinkles project. I'm going to follow up with the writer today and ask her to append the following footnote about your contributions - let me know if you have any edits to suggest!

> Actively working on the LSST DESC Twinkles project are: Rahul Biswas (UW), Jim Chiang (SLAC), Scott Daniel (UW), Seth Digel (SLAC), Richard Dubois (SLAC), Tom Glanzman (SLAC), Tony Johnson (SLAC), Bryce Kalmbach (UW), Heather Kelly (SLAC), Simon Krughoff (UW), Phil Marshall (SLAC), Brian Van Klaveren (SLAC), and Michael Wood-Vasey (Pitt)

Also, if we can make a high-res _g-r-i_ color composite of the Run 3.1 coadd, that would look *great* on the Symmetry website :-) The default plan is to use the old Run 1.1 version ( @SimonKrughoff do you have a high-res version you can provide a link to please? )

**Comment by rbiswas4** [comment]
I think the name Scott Daniel (UW) got missed on that list.

**Comment by drphilmarshall** [comment]
Yep! Sorry Scott - I should have checked the upstairs bedrooms :-) Thanks
Rahul.
