### ISSUE TITLE
Issues need labels, milestones and assignments

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#44]

**Comment by connolly** [comment]
I added the labels and assignments. The current milestones are:
- Requirements
- Initial Plan
- Run 1
- Analysis
- Someday

I think it might help to have more granularity/clarity in this. We could make it 
- Requirements
- Prototype generation, processing
- Final generation, processing
- Analysis 
- Someday

or break it down by component:
- Prototype 1.0 Data Generation
- Prototype 1.0 Data Processing
- Prototype 1.0 light curve extraction and analysis 1.0
- Final 1.0 Data generation 
- Final 1.0 Data Processing
- Final 1.0 light curve extraction and analysis 1.0
- Someday

**Comment by drphilmarshall** [comment]
I *think* I want fewer milestones rather than more (so that we don't have to so much changing later ;-) ) We have a deadline for the RQ document from the RoadMap, and I'd suggest we make just two others, one for Run 1 data generation (ImSim) and another for Run 1 data processing (DM). Maybe we could complete these, and then meet (at SLAC in March?) to design, issue and milestone the final Twinkles 1 DG and DP runs?

Then there'll be other milestones that crop up as required - like today's ANL2015 Hack Day one :-) What do you think?

**Comment by wmwv** [comment]
What do we plan to have done by the March meeting?

**Comment by drphilmarshall** [comment]
Hi @DarkEnergyScienceCollaboration/twinkles ,

I'm doing some issue management, as you have seen. Initial data generation experiments are going very well and I am confident of getting an useful requirements document (initial draft) done by Christmas. It's great to see :-)

Looking ahead to the New Year, and inspired by Michael's question above, I suggest we define "Run 1" as the dataset that we generate and analyze before the collaboration meeting, so that we can present our progress to the group for feedback. What do you think? To see what this looks like, check out our [new-look milestone page](https://github.com/DarkEnergyScienceCollaboration/Twinkles/milestones) :-)

I don't think we need to define what the Run 1 dataset need look like yet: let's just keep developing and see how things look around mid-January. If we aim to have a reasonable Run 1 dataset in place by the end of Jan, we can then spend a month focusing on its analysis (both DM and then DESC post-processing). We'll need to do some early science analysis at that point, which will be fun :-)

Comments welcome!

**Comment by jchiang87** [comment]
I think that having "Run 1" generated and analyzed by March is a good and feasible goal.  However, I would like to see [the document](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/doc/Run1.md) describing what goes into Run 1 updated with our latest thinking on all of the ingredients (i.e., enigma_1189 instead of `OpSim 3.61`, 6 filters instead of just r and g for Twinkles 1.0 as in the SRM) so that the workflows group has a definite set of goals/requirements to shoot for.  I realized these are moving targets, and will evolve, but it would be good to keep them updated as our thinking changes so everyone knows where we stand.

**Comment by drphilmarshall** [comment]
I agree: this must be kept *current*. Proposing changes to the Run 1 design
means proposing edits to the Run1 document.
