### ISSUE TITLE
Assign SED to Lens Galaxy

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#45]
Make sure we are assigning realistic SEDs to the lens galaxies we insert into the catalog.

**Comment by jbkalmbach** [comment]
Added to task list under #37

**Comment by jbkalmbach** [comment]
We are using 'Burst.25E09.1Z.spec.gz' from the sims_sed_library.

**Comment by drphilmarshall** [comment]
Good - that should be nice and red.
