### ISSUE TITLE
Calibrate OM10 magnitudes to PhoSim Catalog magnitudes

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#46]
Need to figure out what bands the magnitudes that come out of OM10 are in and convert to LSST magnitudes for catalogs.

**Comment by jbkalmbach** [comment]
Added to task list under #37

**Comment by jbkalmbach** [comment]
Hi @drphilmarshall,

Do you have any sort of legend for the OM10 catalog variables? I'm just wondering what values I should give for magnitudes of the images. I originally thought that the 'MAG' column was a magnification in magnitudes but when @SimonKrughoff was trying to make phosim images he was getting problems and I went to the OM10 catalog and realized some of those 'MAG' values are in the order +/- 100 so that can't be the case.

**Comment by jbkalmbach** [comment]
I found this code from the OM10 repo [here](https://github.com/drphilmarshall/OM10/blob/master/om10/db.py#L215), so I will go with what's there for RA, DEC, MAG adjustments for images for now until I hear otherwise.

**Comment by drphilmarshall** [comment]
That's right: 'MAG' is the magnification of each quasar image, so you need
to subtract -2.5log10 of MAG from the source magnitude. The magnification
is the same in each filter, since lensing (and geometric optics in general)
is achromatic.

**Comment by jbkalmbach** [comment]
With #119 we have the correct magnification definition in the sprinkler now. Also, the 'i' band magnitudes for lens galaxies has been translated into the "imsimband" for the correct magNorm values.

**Comment by drphilmarshall** [comment]
Boom!
