### ISSUE TITLE
Which OpSim

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#49]
#22 chose the location of the pointing to be one of the deep drilling fields, but not all realizations of the OpSim have the same defined deep drilling fields.  We need to choose one with the field chosen for Twinkles.

**Comment by connolly** [comment]
I think enigma_1189 would be a good run to use. It is close to the next baseline simulation

https://confluence.lsstcorp.org/display/SIM/OpSim+Datasets+for+Cadence+Workshop+LSST2015

**Comment by SimonKrughoff** [comment]
Expanding on what @connolly said...

According to [this page](https://confluence.lsstcorp.org/display/SIM/OpSim+Datasets+for+Cadence+Workshop+LSST2015), the newest version of OpSim is enigma_1189.  See [here](http://ops2.lsst.org:8080/allMetricResults?runId=1) for the results of MAF on that run.  It looks like it does indeed contain the chosen DD field:
![image](https://cloud.githubusercontent.com/assets/945715/10795719/1b39cf40-7d69-11e5-9438-49094f608147.png)
