### ISSUE TITLE
Pointing center

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#5]
@wmwv suggested a moderate galactic latitude field. On what other criteria should we choose the survey pointing center? Let's then pick one to get started, and see what it contains.

**Comment by SimonKrughoff** [comment]
Is this a dup of #22 ?

**Comment by drphilmarshall** [comment]
Yes. And since it's labelled "documentation" and not "hack", I am closing it.
