### ISSUE TITLE
Can PhoSim take FITS images and CatSim sources as input at the same time?

### ISSUE THREAD

**Issue by linan7788626** [DarkEnergyScienceCollaboration/Twinkles#53]
Seems like this would be a better way to go than providing FITS images that contain both Einstein rings and SNe as single bright pixels. @johnrpeterson ?

**Comment by linan7788626** [comment]
In which case, the Sprinkler could add in an Einstein Ring image too.

**Comment by johnrpeterson** [comment]
yes, phosim can take truth images as well as parameterized sources.

john

**Comment by drphilmarshall** [comment]
Thanks @johnrpeterson !
