### ISSUE TITLE
LSST DM Stack Reading Group, Thursdays at 1200 PDT on BlueJeans

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#54]
In order to write the Twinkles RQ document ( #34 ), we need to know what we can reasonably expect the DM stack to do in the next year or so. And then, in order to produce DM light curves from Twinkles images, we will need to know how to implement such a pipeline. To achieve these twin goals, @wmwv and I will be reading the DM docs together, in a weekly reading club. We'll meet Thursdays at 1200 (noon) PST via BlueJeans (email Phil or Michael for the number), and discuss what we've read that week (and also how the RQ doc is coming along). 

Reading for Week 1: Thursday November 5th:

Browse the following sources, understand what goes in each one, and attempt to answer the following question: how is an LSST *object* defined?

* [The LSST DM Home Page](https://confluence.lsstcorp.org/display/DM/Data+Management+Home)

* [The LSST Software User Guide](https://confluence.lsstcorp.org/display/LSWUG/LSST+Software+User+Guide)

* [DMS Requirements and Design Documents](https://confluence.lsstcorp.org/pages/viewpage.action?pageId=2065008)

* [DM Documentation about Planned Data Products](https://confluence.lsstcorp.org/display/LSWUG/Productions+and+Data+Products) 

How does that sound, Michael?

**Comment by drphilmarshall** [comment]
PS. In his [plenary talk at the ANL 2015 collaboration meeting](https://confluence.slac.stanford.edu/download/attachments/195860539/Plenary-Bosch.pdf?version=2&modificationDate=1446209798000&api=v2), Jim Bosch pointed us to the following documents: 

* [LSE-163 (data products)](https://github.com/lsst/LSE-163)

* [LDM-151 (algorithms)](https://github.com/lsst/LDM-151)

We should find ourselves pointed there by the DM documentation as we browse it, but just in case, there are the links!

**Comment by tony-johnson** [comment]
Since some others are interested in participating in the "Reading Group" Phil asked me to paste a link to a doodle poll to see if we could find a time for the weekly meeting when more people can attend (there are several meetings which clash with the proposed 9am pacific meeting time).

The doodle poll is here: http://doodle.com/poll/52wbgia4umm9spdi

Please fill it in if you are interested in joining the meeting.

**Comment by danielsf** [comment]
Hi,

This is the first I have heard of a DM Stack Reading Group.  What is the
proposed topic/purpose of the meeting?

-- Scott

**Comment by danielsf** [comment]
Sorry.  Did not realize that this email came from github

**Comment by drphilmarshall** [comment]
No problem, Scott. @wmwv, when are you free? Wednesdays at 4pm EDT?
http://doodle.com/poll/52wbgia4umm9spdi

**Comment by drphilmarshall** [comment]
OK! With some rearranging it looks as though we can *all* make Thursdays at
12 noon PST (3pm EST). Let's start tomorrow at this time, where we will
attempt an overview of the DM documentation, and to answer the question,
"How is a DM object currently defined?" I'll email the doodle repondents
with the correct Blue Jeans number to videocall in on.

**Comment by wmwv** [comment]
My apologies, but I can make all Thursdays *except* this one.

**Comment by idellant** [comment]
Apologies, thursdays at 3 also work except for today...
Ian

**Comment by drphilmarshall** [comment]
OK! Since this group is primarily for Michael and I to get up to speed, and start work on the Twinkles RQ document, we'll meet for the first time NEXT WEEK, Thursday November 12 at 1200 noon PST WITHOUT FAIL.

I already did my homework for this: [here are my notes on our first assignment](https://docs.google.com/document/d/12BLVM0zTM56qUgc90DRZQLD8TQTFr_wDHGHwdktJwJw/edit?usp=sharing) - I now know what an Object is :-) Please do request edit access if you want to supplement them!

**Comment by drphilmarshall** [comment]
Hi all,

Reminder: we are meeting to talk about our reading of the DM stack docs for the first time TOMORROW, Thursday November 12 at 1200 noon PST.

I already did my homework for this: [here are my notes on our first assignment](https://docs.google.com/document/d/12BLVM0zTM56qUgc90DRZQLD8TQTFr_wDHGHwdktJwJw/edit?usp=sharing) - I now know what an Object is :-) Please do click on that link and comment in place (or request edit access if you want to supplement them) as you do your reading. In fact, you might well find it helpful to just click on the links in my notes as you go through them.

**Comment by drphilmarshall** [comment]
Dear Readers,

Don't forget, we are meeting this Thursday (December 3rd) at 1200 noon PST for our second reading club session. I see there has been some good progress on [our shared document](https://docs.google.com/document/d/12BLVM0zTM56qUgc90DRZQLD8TQTFr_wDHGHwdktJwJw/edit#heading=h.z3g9aqyo5zkl) which is great! @wmwv let's show the group our skeleton Twinkles 1 requirements document as well, for early discussion and feedback. See you Thursday!

Phil

**Comment by drphilmarshall** [comment]
Readers - good to see you today. Here are the questions that we came up with for next time, with names attached. Have fun!

* What’s the recommended system for storing truth values of parameters in simulated objects, for comparison with DM stack output measurements? Would it be easy to use the Butler? A database to join to? **Rahul.**
* What deblending is currently employed during the making of the CoaddSources, before forced photometry is run? What PSF is used in the ForcedPhotometry? **Phil.**
* Databases: How different is qserv from mysql? What’s the best way to turn FITS tables into qserv-like mysql tables? **Jim.**
* How is the CFHTLS Reprocessing going? Does their DM pipeline look like ours? How might we coordinate efforts? **Tony and Tom.**
* What are the science analyses we want to do with Twinkles 1, and what specifications do they imply for OpSim, CatSim, PhoSim, the DM stack, and our own DESC analysis software (SN/SLMonitor, SLTimer, SNDistance)? **Michael and Phil.**

**Comment by drphilmarshall** [comment]
PS. @sethdigel, if you like you could do the reading on the PSF used in ForcedSource flux measurement - I added it as an extra after the meeting. Let me know!

**Comment by boutigny** [comment]
Following a discussion with Phil, here is the Wiki where we maintained documentation for the DESC reprocessing task force : https://github.com/DarkEnergyScienceCollaboration/ReprocessingTaskForce/wiki

I think that next week I will be ready to start looking at post-coaddition tasks. I will document things in the Wiki.

**Comment by drphilmarshall** [comment]
Thanks Dominique! Let's see if you, Tom, Tony, Jim and I can meet up in
person on Tuesday afternoon as well, once we've absorbed the group's
progress so far. Does 3pm sound OK?

On Thu, Dec 3, 2015 at 1:49 PM, Dominique Boutigny <notifications@github.com

**Comment by boutigny** [comment]
Yes, it's ok for me

**Comment by jchiang87** [comment]
Yes, me too.

**Comment by tony-johnson** [comment]
On 12/03/2015 02:31 PM, Phil Marshall wrote:
> Thanks Dominique! Let's see if you, Tom, Tony, Jim and I can meet up in
> person on Tuesday afternoon as well, once we've absorbed the group's
> progress so far. Does 3pm sound OK?
Hi, I can make 3pm today. Do we need a meeting location?

Tony

**Comment by drphilmarshall** [comment]
How about we meet in the 2nd floor conference room at 3pm this afternoon?
We can open up the CI group bluejeans as well in case anyone else wants to
drop in.

Let's plan on splitting the time half and half: Dominique can show us what
the Repro Task Force have done so far, and we can show him the state of the
Twinkles workflow. Sound good?

**Comment by jchiang87** [comment]
ok with me.

**Comment by drphilmarshall** [comment]
Dear Readers,

Don't forget, we are meeting at 12 noon PST tomorrow for our usual DM reading group. The questions we set ourselves to answer are in [our notes here]():

* What’s the recommended system for storing truth values of parameters in simulated objects, for comparison with DM stack output measurements? Would it be easy to use the Butler? A database to join to? Rahul.

* What deblending is currently employed on the CoaddSources, before forced photometry is run? Phil

* What PSF is used in the ForcedPhotometry? Seth.

* Databases: How different is qserv from mysql? What’s the best way to turn FITS tables into qserv-like mysql tables? Jim.

* How is the CFHTLS Reprocessing going? Does their DM pipeline look like ours? How might we coordinate efforts? Tony and Tom.

* What are the science analyses we want to do with Twinkles 1, and what specifications do they imply for OpSim, CatSim, PhoSim, the DM stack, and our own DESC analysis software (SN/SLMonitor, SLTimer, SNDistance)? Michael and Phil.

See you on BlueJeans tomorrow!

Phil

**Comment by rbiswas4** [comment]
Hi,

Is there a bluejeans link?
Thanks,
Rahul

**Comment by drphilmarshall** [comment]
Hi all,

Many apologies for lateness, I got caught up in something else. Ironic eh, after urging you all to do your reading before today? Sorry.

I'm going to jump into BlueJeans now, hopefully Ill catch some of you there. The directions should be in [our notes, here](https://docs.google.com/document/d/12BLVM0zTM56qUgc90DRZQLD8TQTFr_wDHGHwdktJwJw/edit). 

Phil

**Comment by drphilmarshall** [comment]
Well, sorry about that. Jim tells me that Michael, Rahul, Tony, Tom and he met at 12 and talked about two things: workflow progress (Tony and Tom) and PhoSim truth values (Rahul). I see notes on both, thank you!

I have stuff to report on deblending (although itll be clearer to me after some interaction with Simon), and also Twinkles requirements - but both can wait. Unfortunately next Thursday is a vacation day for me, so I'll have to transmit what I can electronically instead.

**Comment by drphilmarshall** [comment]
Closing this, with fondness, as we have begun regular all-group meetings instead. The notes will live on, though!
