### ISSUE TITLE
Select the density of lensed galaxies

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#55]

**Comment by jbkalmbach** [comment]
This has been incorporated into the sprinkler as a density parameter between 0 and 1.

**Comment by drphilmarshall** [comment]
Let me see: do you first CatSim a standard density of galaxies into the
field, and then select 100x% of them  to be lensed, background, AGN-hosting
galaxies, where x is the density parameter you are talking about? And then
you replace each of these galaxies with an OM10 AGN of roughly the same
redshift?

**Comment by jbkalmbach** [comment]
Almost exactly. Yes, we first pull the set of CatSim galaxies that are located in the field and then select (100*x)% of the galaxies **that already have an AGN component** to be lensed replacing them with OM10 system, where x is the density parameter.

**Comment by drphilmarshall** [comment]
Ah! If you set the density to 1, how many lenses do we get?

**Comment by jbkalmbach** [comment]
2436 lensed systems.

**Comment by drphilmarshall** [comment]
Excellent. Density of 0.2 should be plenty - I'll get hold of the right
systems.
