### ISSUE TITLE
Replace galaxy with lens galaxy

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Twinkles#57]

**Comment by jbkalmbach** [comment]
We are doing this in the sprinkler [here](https://github.com/jbkalmbach/Twinkles/blob/master/twinkles/sprinkler.py#L124).

**Comment by drphilmarshall** [comment]
Good! Your code reminds me that
```python
newlens['REFF'] = 1.0 # Hard coded for now. See issue in OM10 GitHub.
```
I'll raise this here too so I don't forget to fix this before the summer.

**Comment by SimonKrughoff** [comment]
It would be good to check this on a few images.  When I was looking around at the images I found a few quasar images on whopping bright galaxies.  Of course, it could just be coincidence.

**Comment by drphilmarshall** [comment]
Or realistic? The typical lens galaxy should be around m=19-20, z=0.5, I
think.

**Comment by SimonKrughoff** [comment]
O.K.  That's pretty bright.  I guess we should just do the plots you suggested yesterday and compare to what's coming out in the images.

**Comment by drphilmarshall** [comment]
Yeah - actually we want the lens galaxy visible, that's one of the things
that will make the LSST lens systems stand out from the crowd. When the
quasar and lens brightness is comparable, you get a much better outlier in
catalog space.
