### ISSUE TITLE
Twinkles RQ face-to-face discussion in Davis

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#65]
Hi @cdfassnacht 

@wmwv is going to be in Davis the week of December 14-18.  I could come up and visit on either Weds, Thurs or Friday, and we could finish(!) our first draft Twinkles 1 requirements document. What do you think? Which day works best for you? 

PS. We can call @saurabhwjha too so he doesn't miss out :-)

**Comment by cdfassnacht** [comment]
Hi @drphilmarshall ,

Unfortunately I will be out of town that week.  Sorry I'll miss your visit.

**Comment by drphilmarshall** [comment]
Ahhh sorry to hear it. Can we use your office please? ;-)
@wmwv, shall we go for Wednesday to allow some follow-up finishing off time
before the end of the week?

**Comment by wmwv** [comment]
Wednesday would be good.  I'll be available from 10:30am onward.

**Comment by drphilmarshall** [comment]
Great - I'll aim to be on the physics dept 5th floor shorty after that.

On Mon, Dec 7, 2015 at 6:20 AM, Michael Wood-Vasey <notifications@github.com
