### ISSUE TITLE
Generate a sample of phosim instance catalogs for benchmarking phosim execution

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#66]
These will be for all six bands and various magnitude cuts to be run using settings  identified in issue #63.

**Comment by jchiang87** [comment]
These instance catalogs will also be registered in the [DESC Data Catalog](http://srs.slac.stanford.edu/DataCatalog/?experiment=LSST-DESC) at SLAC so that they can be used for development of the phosim execution pipeline.

**Comment by jchiang87** [comment]
@SimonKrughoff I'm trying to run code similar to your [generatePhosimInput.py](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/generatePhosimInput.py) script, accessing the UW catsim db, following the instructions here https://confluence.lsstcorp.org/display/SIM/Accessing+the+UW+CATSIM+Database , but I'm having connection problems.  I have a loop implemented that executes that code and it will work fine for a couple interations, the it will die like this:
```
Traceback (most recent call last):
  File "InstcatGenerator.py", line 98, in <module>
    generator(outfile, visit)
  File "InstcatGenerator.py", line 39, in __call__
    starDBObj = CatalogDBObject.from_objid(starName)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/sims_catalogs_generation/2.1.0-4-ge1912d2+2/python/lsst/sims/catalogs/generation/db/dbConnection.py", line 393, in from_objid
    return cls(*args, **kwargs)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/sims_catalogs_generation/2.1.0-4-ge1912d2+2/python/lsst/sims/catalogs/generation/db/dbConnection.py", line 447, in __init__
    raise RuntimeError("Failed to connect to %s: sqlalchemy.%s %s" % (self.engine, e.message, message))
RuntimeError: Failed to connect to Engine(mssql+pymssql://LSST-2:***@localhost:51433/LSST): sqlalchemy.(pymssql.OperationalError) (20002, 'DB-Lib error message 20003, severity 6:\nAdaptive Server connection timed out\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed\n') 
 To connect to the UW CATSIM database:  Check that you have valid connection parameters, an open ssh tunnel and that your $HOME/.lsst/db-auth.paf contains the appropriate credientials. Please consult the following link for more information on access:  https://confluence.lsstcorp.org/display/SIM/Accessing+the+UW+CATSIM+Database 
```
Any suggestions?

**Comment by jchiang87** [comment]
FWIW, here is the actual script I am running:

https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/twinkles/InstcatGenerator.py

**Comment by SimonKrughoff** [comment]
@jchiang87 If it works for a few iterations and then dies, I think you may be running into a hardware issue with our database server.  Every Nth connection simply fails and we haven't found out why yet.

To get around this, I put my query in a try block and keep retrying until success: [see example here](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/generatePhosimInput.py#L41).

I think Scott D. is working on a version of the database connector that only gets one connection and reuses it, so this may not be a problem for much longer.  Regardless, I think the above workaround will work for you.

**Comment by jchiang87** [comment]
I was wondering about that try block.  Ok, thanks, I'll give that a go.

**Comment by SimonKrughoff** [comment]
Yes.  It's not pretty, but I think it should work.  Let me know if you have problems.

**Comment by johnrpeterson** [comment]
the phosim execution pipeline is phosim.py.  could you indicate what this is for?

john

**Comment by jchiang87** [comment]
@TomGlanzman I've generated 300 instance catalogs to be used to generate images for simulation benchmarking and for workflow development.   These include the first twenty visits for each ugrizy band and plus the next 180 visits in r, all for our deep drilling field.  These are unsprinkled.  They can be found in `/nfs/farm/g/desc/u1/data/Twinkles/phosim/instance_catalogs` on slac linux.

Once we know what should go into the physics overrides files, I can generate those as well for each visit.

**Comment by rbiswas4** [comment]
@jchiang87 @SimonKrughoff 

>  it works for a few iterations and then dies, I think you may be running into a hardware issue with our database server. Every Nth connection simply fails and we haven't found out why yet.

Also if you can rearrange the code so that line 
https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/twinkles/InstcatGenerator.py#L38

```
                db_obj = CatalogDBObject.from_objid(objid)
```
happens at the start of the code only once then you will be good. The connection drop happens only at that stage. Or/And  you could do the try except suggested by SImon. When the connection drops, it usually stays dead for 60 seconds,  so I would put in a sleep time in the try except block.

**Comment by jchiang87** [comment]
> Also if you can rearrange the code so that line ... happens at the start of the code only once then you will be good.

Excellent suggestion @rbiswas4!  I'll give that a try.

**Comment by SimonKrughoff** [comment]
@jchiang87 @rbiswas4 I don't think that helps in this case, because we already only do `from_objid` once per object type anyway.  As I said before, I think Scott is working on something that will allow this, but I don't think it's in a distribution yet.

**Comment by jchiang87** [comment]
I'm running it now with @rbiswas4 suggestion implemented, and it does seem to help.   In any case, having the fix from Scott available would be a good thing.

**Comment by SimonKrughoff** [comment]
O.K.  I must not have understood.  If it's working, great!

**Comment by TomGlanzman** [comment]
Thanks Jim.  Hopefully will be in a position to use them very soon.
