### ISSUE TITLE
DM Workflow

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#67]
Continue to improve DM workflow. In particular:

* Test functionality on SLAC RHEL6
* Complete processing of coadds
* Test visit parellelization

**Comment by tony-johnson** [comment]
Now runs on RHEL6
Now includes ability to run full "cookbook"
Still working on parallelization and report generation

**Comment by drphilmarshall** [comment]
Tony Johnson is: Running Full Cookbook

**Comment by boutigny** [comment]
Just in case you need to refer to it:
I have moved the repro. task force image processing guidelines to a dedicated wiki page. It is in : https://github.com/DarkEnergyScienceCollaboration/ReprocessingTaskForce/wiki/Image-processing-guidelines
