### ISSUE TITLE
Is there a 2% photometric reliability floor due to clouds?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#70]
@SimonKrughoff 's initial cookbook pipeline fpFlux results showed a 2% reliability floor (see #41). Is this due to clouds?

**Comment by SimonKrughoff** [comment]
@jchiang87 @drphilmarshall I've run through 10 images each in g, r, and i.  For this run, I turned off clouds.  These images contain no variability in the sources.  

This is the physics override file I used:
```
centroidfile 1
chargesharing 0
clearclouds
```
The following image shows the repeatability per band.  For g and r, the systematic floor is close to 1%.  In i, it is significantly higher.  The 5-sigma limiting magnitudes are in the ballpark for what I expect, but maybe a little on the faint side.  I'd have to check what the assumptions are for the canonical point source depths.

![image](https://cloud.githubusercontent.com/assets/945715/11986835/40009948-a989-11e5-9ce0-5f2f554b3a68.png)

**Comment by drphilmarshall** [comment]
Interesting! I wonder if z and Y are worse still? It'd be fun if this was
due to a detector issue.

**Comment by drphilmarshall** [comment]
Hey @SimonKrughoff - is your photometric reliability floor analysis/plotting code checked in? Post the URL and you get to close this issue! :-)

**Comment by drphilmarshall** [comment]
This is the validation plot that @tony-johnson wants to add to the workflow. @jchiang87 was going to make sure it's easy for him to do that - bin it to win it, Jim!

**Comment by SimonKrughoff** [comment]
This is the code:
https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/plot_point_mags_gri.py

**Comment by jchiang87** [comment]
In #147, @rbiswas4 and I already moved that script to the `bin` folder, so I'll work on it in the `reorganize` branch.  Should we consider merging #147 now?

**Comment by drphilmarshall** [comment]
Yes, let's do it before this happens again. Everyone likes the reorg I think. Thanks Jim!
