### ISSUE TITLE
Generalizing plot_point_mags.py

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#71]
@SimonKrughoff @jchiang87 I would like to include the plot_point_mags.py script into the workflow we are developing for twinkles, but currently it has a number of items hardwired (visit, directory containing butler data, ...). I would like to generalize it to be more flexible (or have one of you do it if you prefer). I am just wondering if using Argparse from the standard python library is the best (DM compatible) way of doing this?

**Comment by SimonKrughoff** [comment]
@tony-johnson I'm happy for you to improve that.  argparse is certainly the way I'd go, if I were doing it.

**Comment by jchiang87** [comment]
I can do it if you like.  Using argparse is probably fine.  We should move the calc_snr.py utility to the twinkles folder as well. (I assume you're ok with that @SimonKrughoff ?)

In the longer term, were we planning on implementing the basic cookbook as a Jenkins/CI test?

**Comment by SimonKrughoff** [comment]
That all sounds fine.

Regarding working the cookbook into a CI test: the reason I didn't make it executable to begin with is because it involves lots of different types of processing (by hand, one time only, etc.).  We just need to chop out the part that is logical to run in that context.

**Comment by tonyj321** [comment]
On 12/10/2015 10:57 AM, James Chiang wrote:
> I can do it if you like. Using argparse is probably fine. We should 
> move the calc_snr.py utility to the twinkles folder as well. (I assume 
> you're ok with that @SimonKrughoff <https://github.com/SimonKrughoff> ?)
I am sure you can do this faster than me, so if you have time that would 
be great.

> In the longer term, were we planning on implementing the basic 
> cookbook as a Jenkins/CI test?
>
Sounds like it would be worth creating a separate issue for discussing 
that, but I think it would be a good idea.

**Comment by jchiang87** [comment]
I've made plot_point_mags.py into a command line script and put it into the bin folder (and moved calc_snr.py to twinkles).  See 641cee923 .   It can be run like this:
```
$ plot_point_mags.py output_data my_plot.png --visits 840^841^842^843^844^845^846^847^848 \
--id raft=2,2 sensor=1,1 filter=r tract=0
```
The --id can be omitted and will default to what's shown above.  (I resorted to kludging the multiple component parsing of --id.  Anyone is welcome to fix it and do it right.)
