### ISSUE TITLE
Twinkles requirements brain dump 

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#74]
@wmwv don't forget we are hanging out in Davis tomorrow! Before I closed #34 I put in a table trying to summarise the possible difference between Twinkles 1 and 2: how about we start by going through that, and then pair code a two- brain dump of specifications, requirement s and validation together, that we can flesh out and tidy up offline if necessary? I'll message you when I arrive at Davis physics dept c. 10:30am. Looking fwd to it!

**Comment by wmwv** [comment]
@drphilmarshall and @wmwv had a useful and productive meeting at UC Davis on Wed Dec 16.  We laid out a draft of the specifications, requirements and validations for the Targets, Observations, CatSim, Sprinkler, Twinkles implementation.

Remain Infrastructure and work on planned use of DM.
