### ISSUE TITLE
Track down coadd detection issues

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#80]
Show in the image are the detected pixels in blue on top of an r-band coadd 10 visits deep.  There are many faint sources that are not being detected.  The config states that the threshold is set to 5 sigma.  The faint sources seem like they are more significant than 5 sigma to my eye.  I'll track down exactly what is going on.

![image](https://cloud.githubusercontent.com/assets/945715/12045134/5b9b8c9e-ae52-11e5-9e04-ead2c1d03d7b.png)

**Comment by SimonKrughoff** [comment]
Over-plotting the detected catalogs shows that many of the faint sources are actually measured (green circles).  I don't know whether the detection mask plane is fibbing or if these are detections from other bands.  On the good side, it looks like deblending is taking place.

![image](https://cloud.githubusercontent.com/assets/945715/12045187/802360b8-ae53-11e5-81b0-17595013f806.png)

**Comment by drphilmarshall** [comment]
Very nice - thanks Simon! To test the deblending a little more, could you
overlay as cyan crosses the centroids of the detected and deblended
CoaddSources please? I worry that the blue regions arecoloring in single
and not actually deblended objects. Thanks for making this! It's great to
see :-)

**Comment by SimonKrughoff** [comment]
I think I can make the plot your requesting, but to be clear, the blue regions are just the pixels that are marked "Detected."  The contiguous detected regions are sent to the deblender.  I think the fact that there are two sources (green circles) within a single contiguous region of detected pixels is evidence that deblending is happening.

**Comment by drphilmarshall** [comment]
Ah, I beg your pardon - I misread your message, and thought that the green
circles marked *input* object positions. Good! Looks like the deblender is
indeed separating some close pairs (although not all, I notice).

**Comment by SimonKrughoff** [comment]
I'm going to close this now as it's not obvious that there is something fundamentally wrong.  We'll, of course, want to quantify the deblender and detection thresholds through completeness studies etc. but we can file more targeted issues for those.

**Comment by drphilmarshall** [comment]
Good! Nice work.
