### ISSUE TITLE
Add code to do multi band repeatability plots and color composites

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#81]
I have code I hacked together to make figures and images.  The code needs to be cleaned up and added to the repo (yes, yes, should have been doing this as I went along).

**Comment by drphilmarshall** [comment]
@SimonKrughoff I think I unwittingly just called this out in #111 ! Can I suggest that you add your validation code to the repo first, and then clean it up? If you put it in a folder called "validation" that will make it easier for @jchiang87 to reorganize (as in #105). I guess we'll want to `import * from desc.twinkles.validation` or somesuch. Thanks!

**Comment by SimonKrughoff** [comment]
All the code for the plots I made lives in the repository.  I agree that we'll want to make it all easier to use.  I haven't had time to reorganize the repo.  @jchiang87 feel free to take that on if you are eager to do it.

**Comment by drphilmarshall** [comment]
Great! Glad to have you home, safe.
