### ISSUE TITLE
ZenHub decision point

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#82]
Hi @connolly 

Looks like our ZenHub grace period has expired, so it's time to [decide whether or not to buy a license for it](https://dashboard.zenhub.io/#/organizations/DarkEnergyScienceCollaboration). I was getting some value out of it - how about you, @cwwalter @richardxdubois @wmwv ? 

Cheers

Phil

**Comment by wmwv** [comment]
Didn't use it enough to understand the benefit.

**Comment by connolly** [comment]
@drphilmarshall zenhub boards should still work with the public repos (e.g.
twinkles). At least it does for me. Seems that if you have any private
repos you dont get a free license for your organization. I'll contact them
to see what the deal is.

On Mon, Jan 4, 2016 at 7:55 AM, Michael Wood-Vasey <notifications@github.com

**Comment by connolly** [comment]
Zenhub said that if we can document that we have an academic status then they will give us a 100% discount on licenses.  I'll get details but I assume that a letter from SLAC would do the trick. Can @richardxdubois get such a letter from SLAC/Stanford

**Comment by cwwalter** [comment]
Good news!

**Comment by drphilmarshall** [comment]
@richardxdubois We need documentary proof that SLAC is an academic outfit, so that ZenHub give us a free license. Do you have such a letter handy? Where could we get one? @brianv0 ?

**Comment by cwwalter** [comment]
How about taking a picture of how people are dressed?

**Comment by richardxdubois** [comment]
@connolly was taking care of this. He has a letter on KIPAC stationery from Tom Abel making the case. The picture is a pretty good idea, though :-)

**Comment by richardxdubois** [comment]
though it wasn't clear there was a consensus we wanted to use ZenHub. Was there?

**Comment by drphilmarshall** [comment]
I don't see anyone managing this project using any other tool! :-) More
seriously, I think the lack of consensus came from lack of usage: I have
not met anyone else who's really tried using it. I thought it was a useful
addition to the issues, and am sad that I can no longer access it - but I
wouldn't advise paying a lot of money for it. Just enough to cover Andy's
time sending the letter, I guess.

**Comment by connolly** [comment]
Letter was sent to them 3 weeks ago. I'll followup to see what is happening

**Comment by connolly** [comment]
Zenhub said they gave us a perpetual license. Can someone check as it
doesnt seem to have been unlocked when I try to access it

cheers
Andy

**Comment by drphilmarshall** [comment]
I can see the ZenHub board for Twinkles, but not for ComputingModel (which is private). Error message from ZenHub dashboard is "Thank you for trying ZenHub! This organization's ZenHub account is currently frozen. To unlock your Boards and stay connected with your team, please purchase licenses."  Closing this issue, as Twinkles is AOK!
