### ISSUE TITLE
Update CI group on workflow and repository needs 

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Twinkles#83]
Hi @DarkEnergyScienceCollaboration/twinkles 

There's a CI group telecon on Monday 11th Jan, 10amPST. I cannot make it, but @dodelson would like us to phone in and give them an update on "how the various elements of the Twinkles pipeline require framework and workflow tools" and our "needs for a distributed repository and suitable package organization". The email that went to the CI group is below, I'm passing it on here for anyone who is not on the CI list who wants to join in this discussion. 

@SimonKrughoff @tony-johnson @jchiang87 @TomGlanzman you've seen the pipeline/workflow system interaction and GitHub use up close;  @wmwv @jbkalmbach @danielsf do you have additional thoughts to add on our needs regarding package organization and working with repositories? If any of you can join Monday's discussion, please let us all know. That way we'll know that Scott's bases are covered. Feel free to ask for clarifications too. 

Thanks!

Phil

 
> Please join the Computing and Infrastructure telecon on Monday January 11 at 10AM Pacific/noon Chicago/1PM Eastern, as we discuss 3 key tasks in the SRM. 
> 
> Agenda: 
> 
> 1] CI3.1.1: Work with the Twinkles Task Force to determine how the various elements of the pipeline require framework and workflow tools. 
> 
> 2] CI3.2.1: Provide a documented list of guidelines, generated via interaction with TJP, for module development and testing and for data formatting and passing.
> 
> 3] CI4.1.1: Evaluate functional needs for the distributed repository and suitable package organization.
> 
> Connection Info:
> Recommended: VOIP and view the slides through the shared desktop, connect to http://bluejeans.com/476071800 (or use the desktop or mobile apps)

**Comment by jchiang87** [comment]
I'll be at the Jan 11 meeting.

-Jim

**Comment by TomGlanzman** [comment]
I will attend the Jan 11th mtg.

   - Tom

**Comment by wmwv** [comment]
I will attend the Jan 11 meeting.
MWV

**Comment by tony-johnson** [comment]
I will be flying to Chile on Saturday for two weeks. I don't remember my 
exact schedule and have not even understood the time difference but it 
is unlikely I will be able to attend the meeting on Jan 11.

I am a little unclear on why we are discussing these issues in the CI 
general meeting, since they all seem to be topics that belong more 
naturally in the CI software meeting (which we are about to have)?

Tony

**Comment by drphilmarshall** [comment]
@tony-johnson  I was confused too, until I registered that the tasks we're talking about on Monday are from CI3 and CI4 - that is, thinking about those specific CI key projects should help us think about our software needs and recommendations that we'll write about in CI2. If we take on the Twinkles-specific [CI2 use cases](https://github.com/DarkEnergyScienceCollaboration/ComputingModel/blob/master/Notes/CI2-Software-Use-Cases.md) then the thinking and writing we do for them this week will be useful for Monday's discussion as well as the CI2 report. I think.

Jim, Tom, Michael - thanks for joining on Monday!

**Comment by dodelson** [comment]
I agree that we're not going at this linearly. There are 4 CI key projects in the SRM due within the next 6 months that overlap. The study groups are the first 2, but the second 2 are also geared to this general goal. So, yes there will be overlap, but that is the way the SRM lays it out, and it probably makes sense to proceed in this way: the study groups looking at things from a high level and having CI telecons with the analysis WG to talk about more specific ideas. But, if people think we should hold back on 3 and 4, I'm happy to skip the telecons until the study groups report.

**Comment by SimonKrughoff** [comment]
@drphilmarshall @dodelson I have a conflicting meeting at that time.  I can probably skip it, but it sounds like there is plenty of representation.  Let me  know if you need anything specific from me.

**Comment by drphilmarshall** [comment]
@dodelson I think Monday's discussion will be useful for the CI2 group - as you say, it's all work towards the same general goal in the end. The specifics covered on Monday will be useful for the CI2 group to digest - I encouraged them to attend in our meeting just now.

I think @jchiang87 and @TomGlanzman can report ably on the Twinkles workflow experience so far, @SimonKrughoff - thanks!
