### ISSUE TITLE
What dithering scheme do we use?

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#9]
OpSim offers a dithering scheme.  The OpSim scheme is just an example and has not been studied in detail, but does seem to do the right thing to first order.  

The highlights of the scheme are:
* Up to half field offsets
* Offsets per night
* All fields dithered no matter the proposal
* Does not include explicit field rotation.  Rotation is handled via core OpSim functionality, but is not driven by anything other than technical limitations of the cable wrap mechanism.

We should pin down other dithering schemes: both rotation and field dithering.  We'll need to simulate a large enough area so that we can trim the edges and still have enough area with full coverage to be useful.  I say this because it is far easier to simulate and reduce full chips than it is to simulate partial chips.

This may involve writing the code to produce the dithered offsets from OpSim inputs.

**Comment by SimonKrughoff** [comment]
For Run 1 I think we should simply let rotational dithering happen.  I'm open to suggestions for Twinkles I.

**Comment by drphilmarshall** [comment]
@SimonKrughoff I think the Run 1 field is indeed just rotating quietly. Let's come back to this issue later in the year.

**Comment by drphilmarshall** [comment]
Dithering: @SimonKrughoff I think we can continue with "natural" rotational dithering and no  translational dithering for Twinkles 1 (Run 3). This seems like it should be realistic enough.
