### ISSUE TITLE
Try condor-based checkpointing on SLAC linux

### ISSUE THREAD

**Issue by TomGlanzman** [DarkEnergyScienceCollaboration/Twinkles#90]
This involves a couple of technical issues.  First, reliably exercising the two signals needed to invoke Condor-based checkpointing ( 1. SIGUSR2 to create checkpoint file and continue; 2. SIGTSTP to create checkpoint file and stop).  The second issue involves utilizing the needed behavior within the context of the SLAC (and NERSC) batch systems, LSF and SLURM, respectively.  It may be that only the 'create checkpoint file and stop' is necessary -- wired into the warning signals provided by the batch systems prior to killing a job.

Ref: http://research.cs.wisc.edu/htcondor/manual/v7.6/4_2Condor_s_Checkpoint.html

**Comment by drphilmarshall** [comment]
Hey @TomGlanzman - is it worth fiddling with this while doing the Run 1 data generation? If you feel like taking it on, please do reset the milestone to "Run 1 Analysis Start" - thanks!

**Comment by TomGlanzman** [comment]
I see these two projects as completely independent.  Would not wish to endanger the "production" phoSim runs with condor tinkering.  This will simply need a bit of time.

**Comment by drphilmarshall** [comment]
Good call.

**Comment by drphilmarshall** [comment]
Hi @TomGlanzman - while looking for issues to cite in this week's Twinkles Weekly, I searched for "checkpointing" and found only this issue. Can it be closed?

**Comment by TomGlanzman** [comment]
Hi Phil, I suppose so, although there are some loose ends dangling.

   - Tom
