### ISSUE TITLE
Simulation technology for Twinkles one.

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#93]
This is related to #92 .  Turning things on and off in phosim is very difficult and is exacerbated by the fact that everything is turned on by default.  This combined with the fact that we still haven't reached a resolution on #73 or #63 makes me worried that we will continue to run into roadblocks that will cost significant time.

This has me wondering if we should go with Galsim instead of Phosim for Twinkles one.  This has the benefits of:
1. being faster (up to an order of magnitude)
2. it only has the effects that we explicitly put in, so no surprises
3. easier to develop, so allows us to put in our own models for things.

Galsim is missing a full optical model, so we miss out on vignetting and other subtle optical effects.  It also does not include any of the subtle sensor effects.  I'm not sure we care about those things at this point, though, since we are only using the central chip and are planning on turning off many of the sensor effects for now.  Thoughts?

**Comment by SimonKrughoff** [comment]
We should maybe talk about this more on the Friday call.  I didn't take into account the work required to get Galsim running through the DM pipes.  I don't know how hard that will be.  Closing for now, until I can get more info.

**Comment by cwwalter** [comment]
I think one reason to go with PhoSim is that we are using this as a pathfinder to test a lot of our workflows.  Removing PhoSim would be removing a important piece in terms of CPU cycles, book keeping etc.  It's relevant both for future Twinkles work and other simulation work in the DESC.

This is of course different than Twinkles science goals but it is something to keep in mind.

**Comment by cwwalter** [comment]
Oops crossed Simon commenting and closing this.

**Comment by SimonKrughoff** [comment]
@cwwalter I agree, and thanks for the comment.  Sorry for the spam.

**Comment by johnrpeterson** [comment]
wrote:
> This has me wondering if we should go with Galsim instead of Phosim for Twinkles one. This has the benefits of:
> 1. being faster (up to an order of magnitude)
> 

phosim is faster by a factor of few.
> 2. it only has the effects that we explicitly put in, so no surprises
> 3. easier to develop, so allows us to put in our own models for things.
> 

phosim is not a collection of models— it is the interaction of basic electron/photon physics with the components of a telescope/camera & its site.  hence, you should not think of it as turning on and off models, but as possibly ignoring certain aspects of physics or removing parts of the telescope/camera & its site.

**Comment by SimonKrughoff** [comment]
> phosim is faster by a factor of few.
This isn't consistent with measurements I've done recently using my version of phosim.  If you have other numbers, I'd really like to see the setup.  I ran the same catalog through phosim and galsim and got ~6hrs for phosim and ~30 min for galsim.

> phosim is not a collection of models— it is the interaction of basic electron/photon physics with the 
> components of a telescope/camera & its site.  hence, you should not think of it as turning on and off  
> models, but as possibly ignoring certain aspects of physics or removing parts of the
> telescope/camera & its site.
Unfortunately, this doesn't work very well in practice.  The project is currently developing various models and any simulation effort we use will need to be able to utilize the project blessed models.

**Comment by johnrpeterson** [comment]
> On Jan 12, 2016, at 2:26 PM, SimonKrughoff <notifications@github.com> wrote:
>> 
>> phosim is not a collection of models— it is the interaction of basic electron/photon physics with the 
>> components of a telescope/camera & its site. hence, you should not think of it as turning on and off
>> 
>> models, but as possibly ignoring certain aspects of physics or removing parts of the
>> telescope/camera & its site.
>> 
> 
> Unfortunately, this doesn't work very well in practice. The project is currently developing various models and any simulation effort we use will need to be able to utilize the project blessed models.
> 

phosim is part of the LSST project and is blessed.  furthermore, using physics should be considered blessed regardless unless you want to get into postmodernist critiques of science.  there are always mistakes though (which are usually interesting).

john

**Comment by SimonKrughoff** [comment]
>phosim is part of the LSST project and is blessed.  furthermore, using physics should be considered blessed regardless unless you want to get into postmodernist critiques of science.  there are always mistakes though (which are usually interesting).

I don't believe the sky model from phosim is the accepted sky model for the project.  The project needs a model that can be used without running phosim, so unless it is made more modular, phosim can't be the answer.

**Comment by johnrpeterson** [comment]
> On Jan 12, 2016, at 3:36 PM, SimonKrughoff <notifications@github.com> wrote:
> 
> phosim is part of the LSST project and is blessed. furthermore, using physics should be considered blessed regardless unless you want to get into postmodernist critiques of science. there are always mistakes though (which are usually interesting).
> 
> I don't believe the sky model from phosim is the accepted sky model for the project. The project needs a model that can be used without running phosim, so unless it is made more modular, phosim can't be the answer.
> 
> 

please stop.  these statements aren’t correct, and aren’t appropriate.

john

**Comment by SimonKrughoff** [comment]
The statement that the project needs a sky model that can be used in the absence of phosim is absolutely correct.  An example is that the sims team needs a sky brightness model (e.g. for MAF applications).  It's not practical to use phosim in this context.

I think the ideal thing would be for phosim to use the same model as used elsewhere in the project, but that doesn't seem to be a priority.

**Comment by drphilmarshall** [comment]
For the benefit of the watching public: having decided to press on with PhoSim, John, Simon et al are now iterating towards a consensus on the physics override file for Run 1 over at #92. Then, once we've made the resulting images, we'll have an opportunity to dissect them together at the collaboration meeting in March. Hopefully there will be beer involved at that get together! ;-)
