### ISSUE TITLE
Make minimal ISR task for eimages

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#94]
As pointed out in #92 by @johnrpeterson PhoSim can't really be run without saturation effects turned off for larger datasets.  This means that a minimal instrument signature removal (ISR) stage will be needed to detect and interpolate the saturated pixels.  This should be totally invisible to the pipeline we are currently running.

**Comment by drphilmarshall** [comment]
Good, thanks Simon!

**Comment by SimonKrughoff** [comment]
Working on this today.

The idea is to turn on saturation detection and masking to prevent things like this:
![image](https://cloud.githubusercontent.com/assets/945715/13710941/d6cd342e-e770-11e5-876c-39ffdc89363e.png)

The bleed trails rotate with the camera and form the splats on the coadds.

**Comment by drphilmarshall** [comment]
How's this going, @SimonKrughoff ?

**Comment by SimonKrughoff** [comment]
This is actually done on the ticket branch of obs_lsstSim.  Can we close it, or does it need to be merged?

**Comment by drphilmarshall** [comment]
This here is a Twinkles issue, which can be closed on delivery of proof that the ISR is good enough (at least visually, I guess). Then I guess we need to do whatever it takes to `obs_lsstSim` so that the Twinkles pipeline uses the fixed code...

**Comment by SimonKrughoff** [comment]
I showed the plot during the hack session.  I still don't know exactly what the artifacts are around the cores, but the saturation spikes are certainly greatly reduced.  Tony has already implemented the changes necessary to use the new code.

**Comment by drphilmarshall** [comment]
Ah yes - you are talking about the before/after plot below. Sounds like this is all done then! Great stuff :-) Thanks Simon!

![image](https://cloud.githubusercontent.com/assets/710903/14162973/bdd1879c-f6a5-11e5-9321-1ccbc72ee2b8.png)

**Comment by jchiang87** [comment]
@SimonKrughoff What ticket branch in obs_lsstSim is this in?  I assume we need to update the Stack at SLAC with this?   When will this be merged into master?
