### ISSUE TITLE
New opsim baseline

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#97]
The OpSim team have come up with a new baseline.  We were using enigma_1189, but the new baseline is kraken_1042.  Should we change?

Apparently, enigma_1189 was never actually a baseline and the kraken_1042 is.  Technically we should probably change, but I know enigma_1189 works and I'm slightly worried about breaking things.

[enigma_1189](http://ops2.tuc.noao.edu/runs/enigma_1189/data/enigma_1189_sqlite.db.gz)
[Page listing kraken_1042](https://confluence.lsstcorp.org/display/SIM/Operations+Simulator+Benchmark+Surveys)

**Comment by jchiang87** [comment]
I vote for changing.  We haven't yet produced any simulated images that would be considered "production" so we might as well use an actual baseline.  Also, if switching to kraken_1042 breaks anything, then we have definitely done something wrong and should fix it.

**Comment by wmwv** [comment]
I vote for changing.

I am aware that I am voting for spending other people's time...
Are we at the point where testing if kraken_1042 works is a low investment of human dev time?

**Comment by SimonKrughoff** [comment]
It should be very low investment.  The only reason I mentioned any breakage is that in a conversation in the hall, Scott Daniel mentioned that the schema may have changed in the newest baseline databases.  That would prompt a change in CatSim.  I'll check with him to see what the status is.

**Comment by drphilmarshall** [comment]
I vote for change too: it's important to be able to adapt to things like
this, so we might as well get into the habit early. BTW Lynne Jones seems
to think that `minion_1016` is the run to use now, not `kraken_1042`.
What's the difference?

**Comment by SimonKrughoff** [comment]
@drphilmarshall they are two realizations of the current baseline cadence.  They were produced on different machines with the same input parameters (but are different because of know non-deterministic behavior in phosim).  The "official" baseline is kraken_1042 according to the web page linked in the issue.

As a side note, the schema did change.  This requires an update to the CatSim code.  I have a in to them about how hard this is to fix.

**Comment by wmwv** [comment]
Where is are these runs documented?  We should take the opportunity to use Twinkles to lay out a clear provenance chain as well.

**Comment by wmwv** [comment]
Wait, why are the outputs of opSim runs dependent on phoSim behavior?  I think I must not understand all of the things OpSim is doing.

**Comment by SimonKrughoff** [comment]
> Wait, why are the outputs of opSim runs dependent on phoSim behavior? I think I must not understand all of the things OpSim is doing.

Sorry, I miss typed.  I meant non-deterministic behavior in OpSim.

> Where is are these runs documented? We should take the opportunity to use Twinkles to lay out a clear provenance chain as well.

These are documented at the link in the issue: https://confluence.lsstcorp.org/display/SIM/Operations+Simulator+Benchmark+Surveys

Unfortunately, the documentation for the previous set of baseline runs was overwritten to make this page, so you need to use the history button to look at those.  For the record, I think that's a bad idea since people will always be using the N-1 version of the baseline because that's what they started their analysis with.

**Comment by drphilmarshall** [comment]
I think we setlled on `kraken_1042`! Closing.
