### ISSUE TITLE
Run 1 description is not latest survey design

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#98]
I think having the Run 1 description linked from the front page misleads people into thinking that's what we are planning.  It would be good to make it very clear that was a first go and not in any way what twinkles will look like when run for DC1.

**Comment by jchiang87** [comment]
I think this issue duplicates #68

**Comment by SimonKrughoff** [comment]
So it does.  Sorry about that.
