### ISSUE TITLE
DESC meeting session

### ISSUE THREAD

**Issue by SimonKrughoff** [DarkEnergyScienceCollaboration/Twinkles#99]
@drphilmarshall @wmwv I added a session I labeled as "[Twinkles 1](https://confluence.slac.stanford.edu/display/LSSTDESC/Twinkles+I+data+challenge)" to the agenda for the March meeting.  The agenda was filling up.  If you don't want a session, please let me know and I'll either delete it or leave it up to @cwwalter if he thinks a join CS/SS session would be of use.

**Comment by drphilmarshall** [comment]
Thanks Simon. I think this is a good idea. I'm not sure what the SS WG
plans are, but we'll have plenty of results  to show and discuss, and
enough plans to make, to warrant a whole session.

**Comment by cwwalter** [comment]
We have a session SSim #2 on Thursday:
https://confluence.slac.stanford.edu/display/LSSTDESC/SSim+Session+%232

I imagine that we could talk about the CatSim related twinkles work there but that can also be covered in the separate Twinkles session if better. I suspect we don't need a separate CS/SSim joint session just for this purpose.
